; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-mir | FileCheck %s

define i32 @max(i32 %A, i32 %B) nounwind {
; CHECK: cmov_slt
        %gt = icmp sgt i32 %A, %B
        %R = select i1 %gt, i32 %A, i32 %B
        ret i32 %R
}
