#include "third_party/Zydis.h"

const char *get_reg_name(const ZydisRegister &data) {
  switch (data) {
  case ZYDIS_REGISTER_NONE:
    return "R_NONE";
  case ZYDIS_REGISTER_AL:
    return "R_AL";
  case ZYDIS_REGISTER_CL:
    return "R_CL";
  case ZYDIS_REGISTER_DL:
    return "R_DL";
  case ZYDIS_REGISTER_BL:
    return "R_BL";
  case ZYDIS_REGISTER_AH:
    return "R_AH";
  case ZYDIS_REGISTER_CH:
    return "R_CH";
  case ZYDIS_REGISTER_DH:
    return "R_DH";
  case ZYDIS_REGISTER_BH:
    return "R_BH";
  case ZYDIS_REGISTER_SPL:
    return "R_SPL";
  case ZYDIS_REGISTER_BPL:
    return "R_BPL";
  case ZYDIS_REGISTER_SIL:
    return "R_SIL";
  case ZYDIS_REGISTER_DIL:
    return "R_DIL";
  case ZYDIS_REGISTER_R8B:
    return "R_R8B";
  case ZYDIS_REGISTER_R9B:
    return "R_R9B";
  case ZYDIS_REGISTER_R10B:
    return "R_R10B";
  case ZYDIS_REGISTER_R11B:
    return "R_R11B";
  case ZYDIS_REGISTER_R12B:
    return "R_R12B";
  case ZYDIS_REGISTER_R13B:
    return "R_R13B";
  case ZYDIS_REGISTER_R14B:
    return "R_R14B";
  case ZYDIS_REGISTER_R15B:
    return "R_R15B";
  case ZYDIS_REGISTER_AX:
    return "R_AX";
  case ZYDIS_REGISTER_CX:
    return "R_CX";
  case ZYDIS_REGISTER_DX:
    return "R_DX";
  case ZYDIS_REGISTER_BX:
    return "R_BX";
  case ZYDIS_REGISTER_SP:
    return "R_SP";
  case ZYDIS_REGISTER_BP:
    return "R_BP";
  case ZYDIS_REGISTER_SI:
    return "R_SI";
  case ZYDIS_REGISTER_DI:
    return "R_DI";
  case ZYDIS_REGISTER_R8W:
    return "R_R8W";
  case ZYDIS_REGISTER_R9W:
    return "R_R9W";
  case ZYDIS_REGISTER_R10W:
    return "R_R10W";
  case ZYDIS_REGISTER_R11W:
    return "R_R11W";
  case ZYDIS_REGISTER_R12W:
    return "R_R12W";
  case ZYDIS_REGISTER_R13W:
    return "R_R13W";
  case ZYDIS_REGISTER_R14W:
    return "R_R14W";
  case ZYDIS_REGISTER_R15W:
    return "R_R15W";
  case ZYDIS_REGISTER_EAX:
    return "R_EAX";
  case ZYDIS_REGISTER_ECX:
    return "R_ECX";
  case ZYDIS_REGISTER_EDX:
    return "R_EDX";
  case ZYDIS_REGISTER_EBX:
    return "R_EBX";
  case ZYDIS_REGISTER_ESP:
    return "R_ESP";
  case ZYDIS_REGISTER_EBP:
    return "R_EBP";
  case ZYDIS_REGISTER_ESI:
    return "R_ESI";
  case ZYDIS_REGISTER_EDI:
    return "R_EDI";
  case ZYDIS_REGISTER_R8D:
    return "R_R8D";
  case ZYDIS_REGISTER_R9D:
    return "R_R9D";
  case ZYDIS_REGISTER_R10D:
    return "R_R10D";
  case ZYDIS_REGISTER_R11D:
    return "R_R11D";
  case ZYDIS_REGISTER_R12D:
    return "R_R12D";
  case ZYDIS_REGISTER_R13D:
    return "R_R13D";
  case ZYDIS_REGISTER_R14D:
    return "R_R14D";
  case ZYDIS_REGISTER_R15D:
    return "R_R15D";
  case ZYDIS_REGISTER_RAX:
    return "R_RAX";
  case ZYDIS_REGISTER_RCX:
    return "R_RCX";
  case ZYDIS_REGISTER_RDX:
    return "R_RDX";
  case ZYDIS_REGISTER_RBX:
    return "R_RBX";
  case ZYDIS_REGISTER_RSP:
    return "R_RSP";
  case ZYDIS_REGISTER_RBP:
    return "R_RBP";
  case ZYDIS_REGISTER_RSI:
    return "R_RSI";
  case ZYDIS_REGISTER_RDI:
    return "R_RDI";
  case ZYDIS_REGISTER_R8:
    return "R_R8";
  case ZYDIS_REGISTER_R9:
    return "R_R9";
  case ZYDIS_REGISTER_R10:
    return "R_R10";
  case ZYDIS_REGISTER_R11:
    return "R_R11";
  case ZYDIS_REGISTER_R12:
    return "R_R12";
  case ZYDIS_REGISTER_R13:
    return "R_R13";
  case ZYDIS_REGISTER_R14:
    return "R_R14";
  case ZYDIS_REGISTER_R15:
    return "R_R15";
  case ZYDIS_REGISTER_ST0:
    return "R_ST0";
  case ZYDIS_REGISTER_ST1:
    return "R_ST1";
  case ZYDIS_REGISTER_ST2:
    return "R_ST2";
  case ZYDIS_REGISTER_ST3:
    return "R_ST3";
  case ZYDIS_REGISTER_ST4:
    return "R_ST4";
  case ZYDIS_REGISTER_ST5:
    return "R_ST5";
  case ZYDIS_REGISTER_ST6:
    return "R_ST6";
  case ZYDIS_REGISTER_ST7:
    return "R_ST7";
  case ZYDIS_REGISTER_X87CONTROL:
    return "R_X87CONTROL";
  case ZYDIS_REGISTER_X87STATUS:
    return "R_X87STATUS";
  case ZYDIS_REGISTER_X87TAG:
    return "R_X87TAG";
  case ZYDIS_REGISTER_MM0:
    return "R_MM0";
  case ZYDIS_REGISTER_MM1:
    return "R_MM1";
  case ZYDIS_REGISTER_MM2:
    return "R_MM2";
  case ZYDIS_REGISTER_MM3:
    return "R_MM3";
  case ZYDIS_REGISTER_MM4:
    return "R_MM4";
  case ZYDIS_REGISTER_MM5:
    return "R_MM5";
  case ZYDIS_REGISTER_MM6:
    return "R_MM6";
  case ZYDIS_REGISTER_MM7:
    return "R_MM7";
  case ZYDIS_REGISTER_XMM0:
    return "R_XMM0";
  case ZYDIS_REGISTER_XMM1:
    return "R_XMM1";
  case ZYDIS_REGISTER_XMM2:
    return "R_XMM2";
  case ZYDIS_REGISTER_XMM3:
    return "R_XMM3";
  case ZYDIS_REGISTER_XMM4:
    return "R_XMM4";
  case ZYDIS_REGISTER_XMM5:
    return "R_XMM5";
  case ZYDIS_REGISTER_XMM6:
    return "R_XMM6";
  case ZYDIS_REGISTER_XMM7:
    return "R_XMM7";
  case ZYDIS_REGISTER_XMM8:
    return "R_XMM8";
  case ZYDIS_REGISTER_XMM9:
    return "R_XMM9";
  case ZYDIS_REGISTER_XMM10:
    return "R_XMM10";
  case ZYDIS_REGISTER_XMM11:
    return "R_XMM11";
  case ZYDIS_REGISTER_XMM12:
    return "R_XMM12";
  case ZYDIS_REGISTER_XMM13:
    return "R_XMM13";
  case ZYDIS_REGISTER_XMM14:
    return "R_XMM14";
  case ZYDIS_REGISTER_XMM15:
    return "R_XMM15";
  case ZYDIS_REGISTER_XMM16:
    return "R_XMM16";
  case ZYDIS_REGISTER_XMM17:
    return "R_XMM17";
  case ZYDIS_REGISTER_XMM18:
    return "R_XMM18";
  case ZYDIS_REGISTER_XMM19:
    return "R_XMM19";
  case ZYDIS_REGISTER_XMM20:
    return "R_XMM20";
  case ZYDIS_REGISTER_XMM21:
    return "R_XMM21";
  case ZYDIS_REGISTER_XMM22:
    return "R_XMM22";
  case ZYDIS_REGISTER_XMM23:
    return "R_XMM23";
  case ZYDIS_REGISTER_XMM24:
    return "R_XMM24";
  case ZYDIS_REGISTER_XMM25:
    return "R_XMM25";
  case ZYDIS_REGISTER_XMM26:
    return "R_XMM26";
  case ZYDIS_REGISTER_XMM27:
    return "R_XMM27";
  case ZYDIS_REGISTER_XMM28:
    return "R_XMM28";
  case ZYDIS_REGISTER_XMM29:
    return "R_XMM29";
  case ZYDIS_REGISTER_XMM30:
    return "R_XMM30";
  case ZYDIS_REGISTER_XMM31:
    return "R_XMM31";
  case ZYDIS_REGISTER_YMM0:
    return "R_YMM0";
  case ZYDIS_REGISTER_YMM1:
    return "R_YMM1";
  case ZYDIS_REGISTER_YMM2:
    return "R_YMM2";
  case ZYDIS_REGISTER_YMM3:
    return "R_YMM3";
  case ZYDIS_REGISTER_YMM4:
    return "R_YMM4";
  case ZYDIS_REGISTER_YMM5:
    return "R_YMM5";
  case ZYDIS_REGISTER_YMM6:
    return "R_YMM6";
  case ZYDIS_REGISTER_YMM7:
    return "R_YMM7";
  case ZYDIS_REGISTER_YMM8:
    return "R_YMM8";
  case ZYDIS_REGISTER_YMM9:
    return "R_YMM9";
  case ZYDIS_REGISTER_YMM10:
    return "R_YMM10";
  case ZYDIS_REGISTER_YMM11:
    return "R_YMM11";
  case ZYDIS_REGISTER_YMM12:
    return "R_YMM12";
  case ZYDIS_REGISTER_YMM13:
    return "R_YMM13";
  case ZYDIS_REGISTER_YMM14:
    return "R_YMM14";
  case ZYDIS_REGISTER_YMM15:
    return "R_YMM15";
  case ZYDIS_REGISTER_YMM16:
    return "R_YMM16";
  case ZYDIS_REGISTER_YMM17:
    return "R_YMM17";
  case ZYDIS_REGISTER_YMM18:
    return "R_YMM18";
  case ZYDIS_REGISTER_YMM19:
    return "R_YMM19";
  case ZYDIS_REGISTER_YMM20:
    return "R_YMM20";
  case ZYDIS_REGISTER_YMM21:
    return "R_YMM21";
  case ZYDIS_REGISTER_YMM22:
    return "R_YMM22";
  case ZYDIS_REGISTER_YMM23:
    return "R_YMM23";
  case ZYDIS_REGISTER_YMM24:
    return "R_YMM24";
  case ZYDIS_REGISTER_YMM25:
    return "R_YMM25";
  case ZYDIS_REGISTER_YMM26:
    return "R_YMM26";
  case ZYDIS_REGISTER_YMM27:
    return "R_YMM27";
  case ZYDIS_REGISTER_YMM28:
    return "R_YMM28";
  case ZYDIS_REGISTER_YMM29:
    return "R_YMM29";
  case ZYDIS_REGISTER_YMM30:
    return "R_YMM30";
  case ZYDIS_REGISTER_YMM31:
    return "R_YMM31";
  case ZYDIS_REGISTER_ZMM0:
    return "R_ZMM0";
  case ZYDIS_REGISTER_ZMM1:
    return "R_ZMM1";
  case ZYDIS_REGISTER_ZMM2:
    return "R_ZMM2";
  case ZYDIS_REGISTER_ZMM3:
    return "R_ZMM3";
  case ZYDIS_REGISTER_ZMM4:
    return "R_ZMM4";
  case ZYDIS_REGISTER_ZMM5:
    return "R_ZMM5";
  case ZYDIS_REGISTER_ZMM6:
    return "R_ZMM6";
  case ZYDIS_REGISTER_ZMM7:
    return "R_ZMM7";
  case ZYDIS_REGISTER_ZMM8:
    return "R_ZMM8";
  case ZYDIS_REGISTER_ZMM9:
    return "R_ZMM9";
  case ZYDIS_REGISTER_ZMM10:
    return "R_ZMM10";
  case ZYDIS_REGISTER_ZMM11:
    return "R_ZMM11";
  case ZYDIS_REGISTER_ZMM12:
    return "R_ZMM12";
  case ZYDIS_REGISTER_ZMM13:
    return "R_ZMM13";
  case ZYDIS_REGISTER_ZMM14:
    return "R_ZMM14";
  case ZYDIS_REGISTER_ZMM15:
    return "R_ZMM15";
  case ZYDIS_REGISTER_ZMM16:
    return "R_ZMM16";
  case ZYDIS_REGISTER_ZMM17:
    return "R_ZMM17";
  case ZYDIS_REGISTER_ZMM18:
    return "R_ZMM18";
  case ZYDIS_REGISTER_ZMM19:
    return "R_ZMM19";
  case ZYDIS_REGISTER_ZMM20:
    return "R_ZMM20";
  case ZYDIS_REGISTER_ZMM21:
    return "R_ZMM21";
  case ZYDIS_REGISTER_ZMM22:
    return "R_ZMM22";
  case ZYDIS_REGISTER_ZMM23:
    return "R_ZMM23";
  case ZYDIS_REGISTER_ZMM24:
    return "R_ZMM24";
  case ZYDIS_REGISTER_ZMM25:
    return "R_ZMM25";
  case ZYDIS_REGISTER_ZMM26:
    return "R_ZMM26";
  case ZYDIS_REGISTER_ZMM27:
    return "R_ZMM27";
  case ZYDIS_REGISTER_ZMM28:
    return "R_ZMM28";
  case ZYDIS_REGISTER_ZMM29:
    return "R_ZMM29";
  case ZYDIS_REGISTER_ZMM30:
    return "R_ZMM30";
  case ZYDIS_REGISTER_ZMM31:
    return "R_ZMM31";
  case ZYDIS_REGISTER_TMM0:
    return "R_TMM0";
  case ZYDIS_REGISTER_TMM1:
    return "R_TMM1";
  case ZYDIS_REGISTER_TMM2:
    return "R_TMM2";
  case ZYDIS_REGISTER_TMM3:
    return "R_TMM3";
  case ZYDIS_REGISTER_TMM4:
    return "R_TMM4";
  case ZYDIS_REGISTER_TMM5:
    return "R_TMM5";
  case ZYDIS_REGISTER_TMM6:
    return "R_TMM6";
  case ZYDIS_REGISTER_TMM7:
    return "R_TMM7";
  case ZYDIS_REGISTER_FLAGS:
    return "R_FLAGS";
  case ZYDIS_REGISTER_EFLAGS:
    return "R_EFLAGS";
  case ZYDIS_REGISTER_RFLAGS:
    return "R_RFLAGS";
  case ZYDIS_REGISTER_IP:
    return "R_IP";
  case ZYDIS_REGISTER_EIP:
    return "R_EIP";
  case ZYDIS_REGISTER_RIP:
    return "R_RIP";
  case ZYDIS_REGISTER_ES:
    return "R_ES";
  case ZYDIS_REGISTER_CS:
    return "R_CS";
  case ZYDIS_REGISTER_SS:
    return "R_SS";
  case ZYDIS_REGISTER_DS:
    return "R_DS";
  case ZYDIS_REGISTER_FS:
    return "R_FS";
  case ZYDIS_REGISTER_GS:
    return "R_GS";
  case ZYDIS_REGISTER_GDTR:
    return "R_GDTR";
  case ZYDIS_REGISTER_LDTR:
    return "R_LDTR";
  case ZYDIS_REGISTER_IDTR:
    return "R_IDTR";
  case ZYDIS_REGISTER_TR:
    return "R_TR";
  case ZYDIS_REGISTER_TR0:
    return "R_TR0";
  case ZYDIS_REGISTER_TR1:
    return "R_TR1";
  case ZYDIS_REGISTER_TR2:
    return "R_TR2";
  case ZYDIS_REGISTER_TR3:
    return "R_TR3";
  case ZYDIS_REGISTER_TR4:
    return "R_TR4";
  case ZYDIS_REGISTER_TR5:
    return "R_TR5";
  case ZYDIS_REGISTER_TR6:
    return "R_TR6";
  case ZYDIS_REGISTER_TR7:
    return "R_TR7";
  case ZYDIS_REGISTER_CR0:
    return "R_CR0";
  case ZYDIS_REGISTER_CR1:
    return "R_CR1";
  case ZYDIS_REGISTER_CR2:
    return "R_CR2";
  case ZYDIS_REGISTER_CR3:
    return "R_CR3";
  case ZYDIS_REGISTER_CR4:
    return "R_CR4";
  case ZYDIS_REGISTER_CR5:
    return "R_CR5";
  case ZYDIS_REGISTER_CR6:
    return "R_CR6";
  case ZYDIS_REGISTER_CR7:
    return "R_CR7";
  case ZYDIS_REGISTER_CR8:
    return "R_CR8";
  case ZYDIS_REGISTER_CR9:
    return "R_CR9";
  case ZYDIS_REGISTER_CR10:
    return "R_CR10";
  case ZYDIS_REGISTER_CR11:
    return "R_CR11";
  case ZYDIS_REGISTER_CR12:
    return "R_CR12";
  case ZYDIS_REGISTER_CR13:
    return "R_CR13";
  case ZYDIS_REGISTER_CR14:
    return "R_CR14";
  case ZYDIS_REGISTER_CR15:
    return "R_CR15";
  case ZYDIS_REGISTER_DR0:
    return "R_DR0";
  case ZYDIS_REGISTER_DR1:
    return "R_DR1";
  case ZYDIS_REGISTER_DR2:
    return "R_DR2";
  case ZYDIS_REGISTER_DR3:
    return "R_DR3";
  case ZYDIS_REGISTER_DR4:
    return "R_DR4";
  case ZYDIS_REGISTER_DR5:
    return "R_DR5";
  case ZYDIS_REGISTER_DR6:
    return "R_DR6";
  case ZYDIS_REGISTER_DR7:
    return "R_DR7";
  case ZYDIS_REGISTER_DR8:
    return "R_DR8";
  case ZYDIS_REGISTER_DR9:
    return "R_DR9";
  case ZYDIS_REGISTER_DR10:
    return "R_DR10";
  case ZYDIS_REGISTER_DR11:
    return "R_DR11";
  case ZYDIS_REGISTER_DR12:
    return "R_DR12";
  case ZYDIS_REGISTER_DR13:
    return "R_DR13";
  case ZYDIS_REGISTER_DR14:
    return "R_DR14";
  case ZYDIS_REGISTER_DR15:
    return "R_DR15";
  case ZYDIS_REGISTER_K0:
    return "R_K0";
  case ZYDIS_REGISTER_K1:
    return "R_K1";
  case ZYDIS_REGISTER_K2:
    return "R_K2";
  case ZYDIS_REGISTER_K3:
    return "R_K3";
  case ZYDIS_REGISTER_K4:
    return "R_K4";
  case ZYDIS_REGISTER_K5:
    return "R_K5";
  case ZYDIS_REGISTER_K6:
    return "R_K6";
  case ZYDIS_REGISTER_K7:
    return "R_K7";
  case ZYDIS_REGISTER_BND0:
    return "R_BND0";
  case ZYDIS_REGISTER_BND1:
    return "R_BND1";
  case ZYDIS_REGISTER_BND2:
    return "R_BND2";
  case ZYDIS_REGISTER_BND3:
    return "R_BND3";
  case ZYDIS_REGISTER_BNDCFG:
    return "R_BNDCFG";
  case ZYDIS_REGISTER_BNDSTATUS:
    return "R_BNDSTATUS";
  case ZYDIS_REGISTER_MXCSR:
    return "R_MXCSR";
  case ZYDIS_REGISTER_PKRU:
    return "R_PKRU";
  case ZYDIS_REGISTER_XCR0:
    return "R_XCR0";
  case ZYDIS_REGISTER_UIF:
    return "R_UIF";
  }
}
