; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Regression test for register allocator spilling of i32.
; All values are live at the same time so some of them have to be spilled,
; the stack slots have to match the size of the type (4 bytes).
; RUN: %foffcc %s --print-mir | FileCheck %s

define i32 @spill_i32(ptr %p) {
; CHECK: func spill_i32 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 96: i64
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r15: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $eax: i32 = [$rdi]: i32
; CHECK-NEXT:    [$rbp + -72]: i32 = $eax: i32
; CHECK-NEXT:    $rbx: i64 = $rdi: i64
; CHECK-NEXT:    $rbx: i64 += 8: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 8]: i32
; CHECK-NEXT:    [$rbp + -68]: i32 = $eax: i32
; CHECK-NEXT:    $rcx: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 += 16: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 16]: i32
; CHECK-NEXT:    [$rbp + -64]: i32 = $eax: i32
; CHECK-NEXT:    $rdx: i64 = $rdi: i64
; CHECK-NEXT:    $rdx: i64 += 24: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 24]: i32
; CHECK-NEXT:    [$rbp + -60]: i32 = $eax: i32
; CHECK-NEXT:    $rsi: i64 = $rdi: i64
; CHECK-NEXT:    $rsi: i64 += 32: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 32]: i32
; CHECK-NEXT:    [$rbp + -56]: i32 = $eax: i32
; CHECK-NEXT:    $r8: i64 = $rdi: i64
; CHECK-NEXT:    $r8: i64 += 40: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 40]: i32
; CHECK-NEXT:    [$rbp + -52]: i32 = $eax: i32
; CHECK-NEXT:    $r9: i64 = $rdi: i64
; CHECK-NEXT:    $r9: i64 += 48: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 48]: i32
; CHECK-NEXT:    [$rbp + -48]: i32 = $eax: i32
; CHECK-NEXT:    $r10: i64 = $rdi: i64
; CHECK-NEXT:    $r10: i64 += 56: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 56]: i32
; CHECK-NEXT:    [$rbp + -44]: i32 = $eax: i32
; CHECK-NEXT:    $r11: i64 = $rdi: i64
; CHECK-NEXT:    $r11: i64 += 64: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 64]: i32
; CHECK-NEXT:    [$rbp + -40]: i32 = $eax: i32
; CHECK-NEXT:    $r12: i64 = $rdi: i64
; CHECK-NEXT:    $r12: i64 += 72: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 72]: i32
; CHECK-NEXT:    [$rbp + -36]: i32 = $eax: i32
; CHECK-NEXT:    $r13: i64 = $rdi: i64
; CHECK-NEXT:    $r13: i64 += 80: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 80]: i32
; CHECK-NEXT:    [$rbp + -32]: i32 = $eax: i32
; CHECK-NEXT:    $r14: i64 = $rdi: i64
; CHECK-NEXT:    $r14: i64 += 88: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 88]: i32
; CHECK-NEXT:    [$rbp + -28]: i32 = $eax: i32
; CHECK-NEXT:    $r15: i64 = $rdi: i64
; CHECK-NEXT:    $r15: i64 += 96: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 96]: i32
; CHECK-NEXT:    [$rbp + -24]: i32 = $eax: i32
; CHECK-NEXT:    [$rbp + -96]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -96]: i64 += 104: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 104]: i32
; CHECK-NEXT:    [$rbp + -20]: i32 = $eax: i32
; CHECK-NEXT:    [$rbp + -88]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -88]: i64 += 112: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 112]: i32
; CHECK-NEXT:    [$rbp + -16]: i32 = $eax: i32
; CHECK-NEXT:    [$rbp + -80]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -80]: i64 += 120: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 120]: i32
; CHECK-NEXT:    [$rbp + -12]: i32 = $eax: i32
; CHECK-NEXT:    $eax: i32 = [$rdi]: i32
; CHECK-NEXT:    $eax: i32 += [$rbx]: i32
; CHECK-NEXT:    $eax: i32 += [$rcx]: i32
; CHECK-NEXT:    $eax: i32 += [$rdx]: i32
; CHECK-NEXT:    $eax: i32 += [$rsi]: i32
; CHECK-NEXT:    $eax: i32 += [$r8]: i32
; CHECK-NEXT:    $eax: i32 += [$r9]: i32
; CHECK-NEXT:    $eax: i32 += [$r10]: i32
; CHECK-NEXT:    $eax: i32 += [$r11]: i32
; CHECK-NEXT:    $eax: i32 += [$r12]: i32
; CHECK-NEXT:    $eax: i32 += [$r13]: i32
; CHECK-NEXT:    $eax: i32 += [$r14]: i32
; CHECK-NEXT:    $eax: i32 += [$r15]: i32
; CHECK-NEXT:    $rbx: i64 = [$rbp + -96]: i64
; CHECK-NEXT:    $eax: i32 += [$rbx]: i32
; CHECK-NEXT:    $rbx: i64 = [$rbp + -88]: i64
; CHECK-NEXT:    $eax: i32 += [$rbx]: i32
; CHECK-NEXT:    $rbx: i64 = [$rbp + -80]: i64
; CHECK-NEXT:    $eax: i32 += [$rbx]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -72]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -68]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -64]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -60]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -56]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -52]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -48]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -44]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -40]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -36]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -32]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -28]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -24]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -20]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -16]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -12]: i32
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($r15: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 96: i64
; CHECK-NEXT:    ret($eax: i32, )
entry:
  %g0 = getelementptr inbounds i32, ptr %p, i64 0
  %v0 = load i32, ptr %g0
  %g1 = getelementptr inbounds i32, ptr %p, i64 2
  %v1 = load i32, ptr %g1
  %g2 = getelementptr inbounds i32, ptr %p, i64 4
  %v2 = load i32, ptr %g2
  %g3 = getelementptr inbounds i32, ptr %p, i64 6
  %v3 = load i32, ptr %g3
  %g4 = getelementptr inbounds i32, ptr %p, i64 8
  %v4 = load i32, ptr %g4
  %g5 = getelementptr inbounds i32, ptr %p, i64 10
  %v5 = load i32, ptr %g5
  %g6 = getelementptr inbounds i32, ptr %p, i64 12
  %v6 = load i32, ptr %g6
  %g7 = getelementptr inbounds i32, ptr %p, i64 14
  %v7 = load i32, ptr %g7
  %g8 = getelementptr inbounds i32, ptr %p, i64 16
  %v8 = load i32, ptr %g8
  %g9 = getelementptr inbounds i32, ptr %p, i64 18
  %v9 = load i32, ptr %g9
  %g10 = getelementptr inbounds i32, ptr %p, i64 20
  %v10 = load i32, ptr %g10
  %g11 = getelementptr inbounds i32, ptr %p, i64 22
  %v11 = load i32, ptr %g11
  %g12 = getelementptr inbounds i32, ptr %p, i64 24
  %v12 = load i32, ptr %g12
  %g13 = getelementptr inbounds i32, ptr %p, i64 26
  %v13 = load i32, ptr %g13
  %g14 = getelementptr inbounds i32, ptr %p, i64 28
  %v14 = load i32, ptr %g14
  %g15 = getelementptr inbounds i32, ptr %p, i64 30
  %v15 = load i32, ptr %g15
  %s1 = add i32 %v0, %v1
  %s2 = add i32 %s1, %v2
  %s3 = add i32 %s2, %v3
  %s4 = add i32 %s3, %v4
  %s5 = add i32 %s4, %v5
  %s6 = add i32 %s5, %v6
  %s7 = add i32 %s6, %v7
  %s8 = add i32 %s7, %v8
  %s9 = add i32 %s8, %v9
  %s10 = add i32 %s9, %v10
  %s11 = add i32 %s10, %v11
  %s12 = add i32 %s11, %v12
  %s13 = add i32 %s12, %v13
  %s14 = add i32 %s13, %v14
  %s15 = add i32 %s14, %v15
  %m0 = xor i32 %s15, %v0
  %m1 = xor i32 %m0, %v1
  %m2 = xor i32 %m1, %v2
  %m3 = xor i32 %m2, %v3
  %m4 = xor i32 %m3, %v4
  %m5 = xor i32 %m4, %v5
  %m6 = xor i32 %m5, %v6
  %m7 = xor i32 %m6, %v7
  %m8 = xor i32 %m7, %v8
  %m9 = xor i32 %m8, %v9
  %m10 = xor i32 %m9, %v10
  %m11 = xor i32 %m10, %v11
  %m12 = xor i32 %m11, %v12
  %m13 = xor i32 %m12, %v13
  %m14 = xor i32 %m13, %v14
  %m15 = xor i32 %m14, %v15
  ret i32 %m15
}
