; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Regression test: a spilled destination of itrunc is folded into the
; instruction as a stack slot. The slot access has to use the (narrow)
; destination size, it was typed with the wide source and wrote 8 bytes into the
; 4 byte slot of the neighbouring vreg.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

declare void @sink(i64)
define void @f(ptr %p, ptr %q, ptr %out) {
; CHECK: func f ($2: i64, $3: i64, $4: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 128: i64
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r15: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    [$rbp + -16]: i64 = $rsi: i64
; CHECK-NEXT:    $r12: i64 = [$rdi]: i64
; CHECK-NEXT:    itrunc([$rbp + -84]: i32, $r12: i64, )
; CHECK-NEXT:    $rbx: i64 = [$rdi + 16]: i64
; CHECK-NEXT:    itrunc([$rbp + -80]: i32, $rbx: i64, )
; CHECK-NEXT:    $r13: i64 = [$rdi + 32]: i64
; CHECK-NEXT:    itrunc([$rbp + -76]: i32, $r13: i64, )
; CHECK-NEXT:    $r14: i64 = [$rdi + 48]: i64
; CHECK-NEXT:    itrunc([$rbp + -72]: i32, $r14: i64, )
; CHECK-NEXT:    $r15: i64 = [$rdi + 64]: i64
; CHECK-NEXT:    itrunc([$rbp + -68]: i32, $r15: i64, )
; CHECK-NEXT:    $rcx: i64 = [$rdi + 80]: i64
; CHECK-NEXT:    itrunc([$rbp + -64]: i32, $rcx: i64, )
; CHECK-NEXT:    $rsi: i64 = [$rdi + 96]: i64
; CHECK-NEXT:    itrunc([$rbp + -60]: i32, $rsi: i64, )
; CHECK-NEXT:    $r8: i64 = [$rdi + 112]: i64
; CHECK-NEXT:    itrunc([$rbp + -56]: i32, $r8: i64, )
; CHECK-NEXT:    $r9: i64 = [$rdi + 128]: i64
; CHECK-NEXT:    itrunc([$rbp + -52]: i32, $r9: i64, )
; CHECK-NEXT:    $r10: i64 = [$rdi + 144]: i64
; CHECK-NEXT:    itrunc([$rbp + -48]: i32, $r10: i64, )
; CHECK-NEXT:    $r11: i64 = [$rdi + 160]: i64
; CHECK-NEXT:    itrunc([$rbp + -44]: i32, $r11: i64, )
; CHECK-NEXT:    $rax: i64 = [$rdi + 176]: i64
; CHECK-NEXT:    [$rbp + -8]: i64 = $rax: i64
; CHECK-NEXT:    itrunc([$rbp + -40]: i32, $rax: i64, )
; CHECK-NEXT:    $rax: i64 = [$rdi + 192]: i64
; CHECK-NEXT:    [$rbp + -128]: i64 = $rax: i64
; CHECK-NEXT:    itrunc([$rbp + -36]: i32, $rax: i64, )
; CHECK-NEXT:    $rax: i64 = [$rdi + 208]: i64
; CHECK-NEXT:    [$rbp + -120]: i64 = $rax: i64
; CHECK-NEXT:    itrunc([$rbp + -32]: i32, $rax: i64, )
; CHECK-NEXT:    $rax: i64 = [$rdi + 224]: i64
; CHECK-NEXT:    [$rbp + -112]: i64 = $rax: i64
; CHECK-NEXT:    itrunc([$rbp + -28]: i32, $rax: i64, )
; CHECK-NEXT:    $rax: i64 = [$rdi + 240]: i64
; CHECK-NEXT:    [$rbp + -104]: i64 = $rax: i64
; CHECK-NEXT:    itrunc([$rbp + -24]: i32, $rax: i64, )
; CHECK-NEXT:    $rax: i64 = [$rdi + 256]: i64
; CHECK-NEXT:    [$rbp + -96]: i64 = $rax: i64
; CHECK-NEXT:    itrunc([$rbp + -20]: i32, $rax: i64, )
; CHECK-NEXT:    $rdi: i64 = [$rdi + 272]: i64
; CHECK-NEXT:    itrunc([$rbp + -88]: i32, $rdi: i64, )
; CHECK-NEXT:    push($rcx: i64, )
; CHECK-NEXT:    push($rdx: i64, )
; CHECK-NEXT:    push($rsi: i64, )
; CHECK-NEXT:    push($rdi: i64, )
; CHECK-NEXT:    push($r8: i64, )
; CHECK-NEXT:    push($r9: i64, )
; CHECK-NEXT:    push($r10: i64, )
; CHECK-NEXT:    push($r11: i64, )
; CHECK-NEXT:    $rdi: i64 = 1: i64
; CHECK-NEXT:    call(sink, )
; CHECK-NEXT:    pop($r11: i64, )
; CHECK-NEXT:    pop($r10: i64, )
; CHECK-NEXT:    pop($r9: i64, )
; CHECK-NEXT:    pop($r8: i64, )
; CHECK-NEXT:    pop($rdi: i64, )
; CHECK-NEXT:    pop($rsi: i64, )
; CHECK-NEXT:    pop($rdx: i64, )
; CHECK-NEXT:    pop($rcx: i64, )
; CHECK-NEXT:    $r12: i64 += $rbx: i64
; CHECK-NEXT:    $r12: i64 += $r13: i64
; CHECK-NEXT:    $r12: i64 += $r14: i64
; CHECK-NEXT:    $r12: i64 += $r15: i64
; CHECK-NEXT:    $r12: i64 += $rcx: i64
; CHECK-NEXT:    $r12: i64 += $rsi: i64
; CHECK-NEXT:    $r12: i64 += $r8: i64
; CHECK-NEXT:    $r12: i64 += $r9: i64
; CHECK-NEXT:    $r12: i64 += $r10: i64
; CHECK-NEXT:    $r12: i64 += $r11: i64
; CHECK-NEXT:    $r12: i64 += [$rbp + -8]: i64
; CHECK-NEXT:    $r12: i64 += [$rbp + -128]: i64
; CHECK-NEXT:    $r12: i64 += [$rbp + -120]: i64
; CHECK-NEXT:    $r12: i64 += [$rbp + -112]: i64
; CHECK-NEXT:    $r12: i64 += [$rbp + -104]: i64
; CHECK-NEXT:    $r12: i64 += [$rbp + -96]: i64
; CHECK-NEXT:    $r12: i64 += $rdi: i64
; CHECK-NEXT:    $ecx: i32 = [$rbp + -84]: i32
; CHECK-NEXT:    [$rdx]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -80]: i32
; CHECK-NEXT:    [$rdx + 12]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -76]: i32
; CHECK-NEXT:    [$rdx + 24]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -72]: i32
; CHECK-NEXT:    [$rdx + 36]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -68]: i32
; CHECK-NEXT:    [$rdx + 48]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -64]: i32
; CHECK-NEXT:    [$rdx + 60]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -60]: i32
; CHECK-NEXT:    [$rdx + 72]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -56]: i32
; CHECK-NEXT:    [$rdx + 84]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -52]: i32
; CHECK-NEXT:    [$rdx + 96]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -48]: i32
; CHECK-NEXT:    [$rdx + 108]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -44]: i32
; CHECK-NEXT:    [$rdx + 120]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -40]: i32
; CHECK-NEXT:    [$rdx + 132]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -36]: i32
; CHECK-NEXT:    [$rdx + 144]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -32]: i32
; CHECK-NEXT:    [$rdx + 156]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -28]: i32
; CHECK-NEXT:    [$rdx + 168]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -24]: i32
; CHECK-NEXT:    [$rdx + 180]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -20]: i32
; CHECK-NEXT:    [$rdx + 192]: i32 = $ecx: i32
; CHECK-NEXT:    $ecx: i32 = [$rbp + -88]: i32
; CHECK-NEXT:    [$rdx + 204]: i32 = $ecx: i32
; CHECK-NEXT:    $rcx: i64 = [$rbp + -16]: i64
; CHECK-NEXT:    [$rcx]: i64 = $r12: i64
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($r15: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 128: i64
; CHECK-NEXT:    ret()
  %g0 = getelementptr i64, ptr %p, i64 0
  %v0 = load i64, ptr %g0, align 8
  %t0 = trunc i64 %v0 to i32
  %g1 = getelementptr i64, ptr %p, i64 2
  %v1 = load i64, ptr %g1, align 8
  %t1 = trunc i64 %v1 to i32
  %g2 = getelementptr i64, ptr %p, i64 4
  %v2 = load i64, ptr %g2, align 8
  %t2 = trunc i64 %v2 to i32
  %g3 = getelementptr i64, ptr %p, i64 6
  %v3 = load i64, ptr %g3, align 8
  %t3 = trunc i64 %v3 to i32
  %g4 = getelementptr i64, ptr %p, i64 8
  %v4 = load i64, ptr %g4, align 8
  %t4 = trunc i64 %v4 to i32
  %g5 = getelementptr i64, ptr %p, i64 10
  %v5 = load i64, ptr %g5, align 8
  %t5 = trunc i64 %v5 to i32
  %g6 = getelementptr i64, ptr %p, i64 12
  %v6 = load i64, ptr %g6, align 8
  %t6 = trunc i64 %v6 to i32
  %g7 = getelementptr i64, ptr %p, i64 14
  %v7 = load i64, ptr %g7, align 8
  %t7 = trunc i64 %v7 to i32
  %g8 = getelementptr i64, ptr %p, i64 16
  %v8 = load i64, ptr %g8, align 8
  %t8 = trunc i64 %v8 to i32
  %g9 = getelementptr i64, ptr %p, i64 18
  %v9 = load i64, ptr %g9, align 8
  %t9 = trunc i64 %v9 to i32
  %g10 = getelementptr i64, ptr %p, i64 20
  %v10 = load i64, ptr %g10, align 8
  %t10 = trunc i64 %v10 to i32
  %g11 = getelementptr i64, ptr %p, i64 22
  %v11 = load i64, ptr %g11, align 8
  %t11 = trunc i64 %v11 to i32
  %g12 = getelementptr i64, ptr %p, i64 24
  %v12 = load i64, ptr %g12, align 8
  %t12 = trunc i64 %v12 to i32
  %g13 = getelementptr i64, ptr %p, i64 26
  %v13 = load i64, ptr %g13, align 8
  %t13 = trunc i64 %v13 to i32
  %g14 = getelementptr i64, ptr %p, i64 28
  %v14 = load i64, ptr %g14, align 8
  %t14 = trunc i64 %v14 to i32
  %g15 = getelementptr i64, ptr %p, i64 30
  %v15 = load i64, ptr %g15, align 8
  %t15 = trunc i64 %v15 to i32
  %g16 = getelementptr i64, ptr %p, i64 32
  %v16 = load i64, ptr %g16, align 8
  %t16 = trunc i64 %v16 to i32
  %g17 = getelementptr i64, ptr %p, i64 34
  %v17 = load i64, ptr %g17, align 8
  %t17 = trunc i64 %v17 to i32
  call void @sink(i64 1)
  %a1 = add i64 %v0, %v1
  %a2 = add i64 %a1, %v2
  %a3 = add i64 %a2, %v3
  %a4 = add i64 %a3, %v4
  %a5 = add i64 %a4, %v5
  %a6 = add i64 %a5, %v6
  %a7 = add i64 %a6, %v7
  %a8 = add i64 %a7, %v8
  %a9 = add i64 %a8, %v9
  %a10 = add i64 %a9, %v10
  %a11 = add i64 %a10, %v11
  %a12 = add i64 %a11, %v12
  %a13 = add i64 %a12, %v13
  %a14 = add i64 %a13, %v14
  %a15 = add i64 %a14, %v15
  %a16 = add i64 %a15, %v16
  %a17 = add i64 %a16, %v17
  %go0 = getelementptr i32, ptr %out, i64 0
  store i32 %t0, ptr %go0, align 4
  %go1 = getelementptr i32, ptr %out, i64 3
  store i32 %t1, ptr %go1, align 4
  %go2 = getelementptr i32, ptr %out, i64 6
  store i32 %t2, ptr %go2, align 4
  %go3 = getelementptr i32, ptr %out, i64 9
  store i32 %t3, ptr %go3, align 4
  %go4 = getelementptr i32, ptr %out, i64 12
  store i32 %t4, ptr %go4, align 4
  %go5 = getelementptr i32, ptr %out, i64 15
  store i32 %t5, ptr %go5, align 4
  %go6 = getelementptr i32, ptr %out, i64 18
  store i32 %t6, ptr %go6, align 4
  %go7 = getelementptr i32, ptr %out, i64 21
  store i32 %t7, ptr %go7, align 4
  %go8 = getelementptr i32, ptr %out, i64 24
  store i32 %t8, ptr %go8, align 4
  %go9 = getelementptr i32, ptr %out, i64 27
  store i32 %t9, ptr %go9, align 4
  %go10 = getelementptr i32, ptr %out, i64 30
  store i32 %t10, ptr %go10, align 4
  %go11 = getelementptr i32, ptr %out, i64 33
  store i32 %t11, ptr %go11, align 4
  %go12 = getelementptr i32, ptr %out, i64 36
  store i32 %t12, ptr %go12, align 4
  %go13 = getelementptr i32, ptr %out, i64 39
  store i32 %t13, ptr %go13, align 4
  %go14 = getelementptr i32, ptr %out, i64 42
  store i32 %t14, ptr %go14, align 4
  %go15 = getelementptr i32, ptr %out, i64 45
  store i32 %t15, ptr %go15, align 4
  %go16 = getelementptr i32, ptr %out, i64 48
  store i32 %t16, ptr %go16, align 4
  %go17 = getelementptr i32, ptr %out, i64 51
  store i32 %t17, ptr %go17, align 4
  store i64 %a17, ptr %q, align 8
  ret void
}
