; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Regression test for register allocator spilling of i8.
; All values are live at the same time so some of them have to be spilled,
; the stack slots have to match the size of the type (1 byte).
; RUN: %foffcc %s --print-mir | FileCheck %s

define i8 @spill_i8(ptr %p) {
; CHECK: func spill_i8 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 48: i64
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r15: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $al: i32 = [$rdi]: i8
; CHECK-NEXT:    [$rbp + -24]: i8 = $al: i8
; CHECK-NEXT:    $rbx: i64 = $rdi: i64
; CHECK-NEXT:    $rbx: i64 += 2: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 2]: i8
; CHECK-NEXT:    [$rbp + -23]: i8 = $al: i8
; CHECK-NEXT:    $rcx: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 += 4: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 4]: i8
; CHECK-NEXT:    [$rbp + -22]: i8 = $al: i8
; CHECK-NEXT:    $rdx: i64 = $rdi: i64
; CHECK-NEXT:    $rdx: i64 += 6: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 6]: i8
; CHECK-NEXT:    [$rbp + -21]: i8 = $al: i8
; CHECK-NEXT:    $rsi: i64 = $rdi: i64
; CHECK-NEXT:    $rsi: i64 += 8: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 8]: i8
; CHECK-NEXT:    [$rbp + -20]: i8 = $al: i8
; CHECK-NEXT:    $r8: i64 = $rdi: i64
; CHECK-NEXT:    $r8: i64 += 10: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 10]: i8
; CHECK-NEXT:    [$rbp + -19]: i8 = $al: i8
; CHECK-NEXT:    $r9: i64 = $rdi: i64
; CHECK-NEXT:    $r9: i64 += 12: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 12]: i8
; CHECK-NEXT:    [$rbp + -18]: i8 = $al: i8
; CHECK-NEXT:    $r10: i64 = $rdi: i64
; CHECK-NEXT:    $r10: i64 += 14: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 14]: i8
; CHECK-NEXT:    [$rbp + -17]: i8 = $al: i8
; CHECK-NEXT:    $r11: i64 = $rdi: i64
; CHECK-NEXT:    $r11: i64 += 16: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 16]: i8
; CHECK-NEXT:    [$rbp + -16]: i8 = $al: i8
; CHECK-NEXT:    $r12: i64 = $rdi: i64
; CHECK-NEXT:    $r12: i64 += 18: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 18]: i8
; CHECK-NEXT:    [$rbp + -15]: i8 = $al: i8
; CHECK-NEXT:    $r13: i64 = $rdi: i64
; CHECK-NEXT:    $r13: i64 += 20: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 20]: i8
; CHECK-NEXT:    [$rbp + -14]: i8 = $al: i8
; CHECK-NEXT:    $r14: i64 = $rdi: i64
; CHECK-NEXT:    $r14: i64 += 22: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 22]: i8
; CHECK-NEXT:    [$rbp + -13]: i8 = $al: i8
; CHECK-NEXT:    $r15: i64 = $rdi: i64
; CHECK-NEXT:    $r15: i64 += 24: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 24]: i8
; CHECK-NEXT:    [$rbp + -12]: i8 = $al: i8
; CHECK-NEXT:    [$rbp + -48]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -48]: i64 += 26: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 26]: i8
; CHECK-NEXT:    [$rbp + -11]: i8 = $al: i8
; CHECK-NEXT:    [$rbp + -40]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -40]: i64 += 28: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 28]: i8
; CHECK-NEXT:    [$rbp + -10]: i8 = $al: i8
; CHECK-NEXT:    [$rbp + -32]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -32]: i64 += 30: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 30]: i8
; CHECK-NEXT:    [$rbp + -9]: i8 = $al: i8
; CHECK-NEXT:    $al: i32 = [$rdi]: i8
; CHECK-NEXT:    $al: i8 += [$rbx]: i8
; CHECK-NEXT:    $al: i8 += [$rcx]: i8
; CHECK-NEXT:    $al: i8 += [$rdx]: i8
; CHECK-NEXT:    $al: i8 += [$rsi]: i8
; CHECK-NEXT:    $al: i8 += [$r8]: i8
; CHECK-NEXT:    $al: i8 += [$r9]: i8
; CHECK-NEXT:    $al: i8 += [$r10]: i8
; CHECK-NEXT:    $al: i8 += [$r11]: i8
; CHECK-NEXT:    $al: i8 += [$r12]: i8
; CHECK-NEXT:    $al: i8 += [$r13]: i8
; CHECK-NEXT:    $al: i8 += [$r14]: i8
; CHECK-NEXT:    $al: i8 += [$r15]: i8
; CHECK-NEXT:    $rbx: i64 = [$rbp + -48]: i64
; CHECK-NEXT:    $al: i8 += [$rbx]: i8
; CHECK-NEXT:    $rbx: i64 = [$rbp + -40]: i64
; CHECK-NEXT:    $al: i8 += [$rbx]: i8
; CHECK-NEXT:    $rbx: i64 = [$rbp + -32]: i64
; CHECK-NEXT:    $al: i8 += [$rbx]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -24]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -23]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -22]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -21]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -20]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -19]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -18]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -17]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -16]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -15]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -14]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -13]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -12]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -11]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -10]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -9]: i8
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($r15: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 48: i64
; CHECK-NEXT:    ret($al: i8, )
entry:
  %g0 = getelementptr inbounds i8, ptr %p, i64 0
  %v0 = load i8, ptr %g0
  %g1 = getelementptr inbounds i8, ptr %p, i64 2
  %v1 = load i8, ptr %g1
  %g2 = getelementptr inbounds i8, ptr %p, i64 4
  %v2 = load i8, ptr %g2
  %g3 = getelementptr inbounds i8, ptr %p, i64 6
  %v3 = load i8, ptr %g3
  %g4 = getelementptr inbounds i8, ptr %p, i64 8
  %v4 = load i8, ptr %g4
  %g5 = getelementptr inbounds i8, ptr %p, i64 10
  %v5 = load i8, ptr %g5
  %g6 = getelementptr inbounds i8, ptr %p, i64 12
  %v6 = load i8, ptr %g6
  %g7 = getelementptr inbounds i8, ptr %p, i64 14
  %v7 = load i8, ptr %g7
  %g8 = getelementptr inbounds i8, ptr %p, i64 16
  %v8 = load i8, ptr %g8
  %g9 = getelementptr inbounds i8, ptr %p, i64 18
  %v9 = load i8, ptr %g9
  %g10 = getelementptr inbounds i8, ptr %p, i64 20
  %v10 = load i8, ptr %g10
  %g11 = getelementptr inbounds i8, ptr %p, i64 22
  %v11 = load i8, ptr %g11
  %g12 = getelementptr inbounds i8, ptr %p, i64 24
  %v12 = load i8, ptr %g12
  %g13 = getelementptr inbounds i8, ptr %p, i64 26
  %v13 = load i8, ptr %g13
  %g14 = getelementptr inbounds i8, ptr %p, i64 28
  %v14 = load i8, ptr %g14
  %g15 = getelementptr inbounds i8, ptr %p, i64 30
  %v15 = load i8, ptr %g15
  %s1 = add i8 %v0, %v1
  %s2 = add i8 %s1, %v2
  %s3 = add i8 %s2, %v3
  %s4 = add i8 %s3, %v4
  %s5 = add i8 %s4, %v5
  %s6 = add i8 %s5, %v6
  %s7 = add i8 %s6, %v7
  %s8 = add i8 %s7, %v8
  %s9 = add i8 %s8, %v9
  %s10 = add i8 %s9, %v10
  %s11 = add i8 %s10, %v11
  %s12 = add i8 %s11, %v12
  %s13 = add i8 %s12, %v13
  %s14 = add i8 %s13, %v14
  %s15 = add i8 %s14, %v15
  %m0 = xor i8 %s15, %v0
  %m1 = xor i8 %m0, %v1
  %m2 = xor i8 %m1, %v2
  %m3 = xor i8 %m2, %v3
  %m4 = xor i8 %m3, %v4
  %m5 = xor i8 %m4, %v5
  %m6 = xor i8 %m5, %v6
  %m7 = xor i8 %m6, %v7
  %m8 = xor i8 %m7, %v8
  %m9 = xor i8 %m8, %v9
  %m10 = xor i8 %m9, %v10
  %m11 = xor i8 %m10, %v11
  %m12 = xor i8 %m11, %v12
  %m13 = xor i8 %m12, %v13
  %m14 = xor i8 %m13, %v14
  %m15 = xor i8 %m14, %v15
  ret i8 %m15
}
