; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Regression test for spilled operands of icmp/fcmp (setcc form) being folded into memory operands
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

define i64 @spill_icmp(ptr %p) {
; CHECK: func spill_icmp ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 112: i64
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r15: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $rax: i64 = [$rdi]: i64
; CHECK-NEXT:    [$rbp + -24]: i64 = $rax: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 16]: i64
; CHECK-NEXT:    [$rbp + -40]: i64 = $rax: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 32]: i64
; CHECK-NEXT:    [$rbp + -56]: i64 = $rax: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 48]: i64
; CHECK-NEXT:    [$rbp + -72]: i64 = $rax: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 64]: i64
; CHECK-NEXT:    [$rbp + -88]: i64 = $rax: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 80]: i64
; CHECK-NEXT:    [$rbp + -104]: i64 = $rax: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 96]: i64
; CHECK-NEXT:    [$rbp + -8]: i64 = $rax: i64
; CHECK-NEXT:    $r15: i64 = [$rdi + 112]: i64
; CHECK-NEXT:    $r13: i64 = [$rdi + 128]: i64
; CHECK-NEXT:    $rbx: i64 = [$rdi + 144]: i64
; CHECK-NEXT:    $r10: i64 = [$rdi + 160]: i64
; CHECK-NEXT:    $r8: i64 = [$rdi + 176]: i64
; CHECK-NEXT:    $r9: i64 = [$rdi + 192]: i64
; CHECK-NEXT:    $r11: i64 = [$rdi + 208]: i64
; CHECK-NEXT:    $r12: i64 = [$rdi + 224]: i64
; CHECK-NEXT:    $r14: i64 = [$rdi + 240]: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 256]: i64
; CHECK-NEXT:    [$rbp + -16]: i64 = $rax: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 272]: i64
; CHECK-NEXT:    [$rbp + -112]: i64 = $rax: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 288]: i64
; CHECK-NEXT:    [$rbp + -96]: i64 = $rax: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 304]: i64
; CHECK-NEXT:    [$rbp + -80]: i64 = $rax: i64
; CHECK-NEXT:    $rcx: i64 = [$rdi + 320]: i64
; CHECK-NEXT:    [$rbp + -64]: i64 = $rcx: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 336]: i64
; CHECK-NEXT:    [$rbp + -48]: i64 = $rax: i64
; CHECK-NEXT:    $rdx: i64 = [$rdi + 352]: i64
; CHECK-NEXT:    [$rbp + -32]: i64 = $rdx: i64
; CHECK-NEXT:    $rdi: i64 = [$rdi + 368]: i64
; CHECK-NEXT:    icmp_ne($lsi: i8, [$rbp + -24]: i64, $rdi: i64, )
; CHECK-NEXT:    mov_zx($rsi: i64, $lsi: i8, )
; CHECK-NEXT:    icmp_ne($dl: i8, [$rbp + -40]: i64, $rdx: i64, )
; CHECK-NEXT:    mov_zx($rdx: i64, $dl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rdx: i64
; CHECK-NEXT:    icmp_ne($al: i8, [$rbp + -56]: i64, $rax: i64, )
; CHECK-NEXT:    mov_zx($rdx: i64, $al: i8, )
; CHECK-NEXT:    $rsi: i64 += $rdx: i64
; CHECK-NEXT:    icmp_ne($cl: i8, [$rbp + -72]: i64, $rcx: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    $rcx: i64 = [$rbp + -80]: i64
; CHECK-NEXT:    icmp_ne($cl: i8, [$rbp + -88]: i64, $rcx: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    $rcx: i64 = [$rbp + -96]: i64
; CHECK-NEXT:    icmp_ne($cl: i8, [$rbp + -104]: i64, $rcx: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    $rcx: i64 = [$rbp + -8]: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $rcx: i64, [$rbp + -112]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $r15: i64, [$rbp + -16]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $r13: i64, $r14: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $rbx: i64, $r12: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $r10: i64, $r11: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $r8: i64, $r9: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $r9: i64, $r8: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $r11: i64, $r10: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $r12: i64, $rbx: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $r14: i64, $r13: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    icmp_ne($cl: i8, [$rbp + -16]: i64, $r15: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    $rcx: i64 = [$rbp + -8]: i64
; CHECK-NEXT:    icmp_ne($cl: i8, [$rbp + -112]: i64, $rcx: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    $rcx: i64 = [$rbp + -96]: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $rcx: i64, [$rbp + -104]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    $rcx: i64 = [$rbp + -80]: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $rcx: i64, [$rbp + -88]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    $rcx: i64 = [$rbp + -64]: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $rcx: i64, [$rbp + -72]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    $rcx: i64 = [$rbp + -48]: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $rcx: i64, [$rbp + -56]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    $rcx: i64 = [$rbp + -32]: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $rcx: i64, [$rbp + -40]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    icmp_ne($cl: i8, $rdi: i64, [$rbp + -24]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rsi: i64 += $rcx: i64
; CHECK-NEXT:    $rax: i64 = $rsi: i64
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($r15: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 112: i64
; CHECK-NEXT:    ret($rax: i64, )
entry:
  %g0 = getelementptr i64, ptr %p, i64 0
  %v0 = load i64, ptr %g0
  %g1 = getelementptr i64, ptr %p, i64 2
  %v1 = load i64, ptr %g1
  %g2 = getelementptr i64, ptr %p, i64 4
  %v2 = load i64, ptr %g2
  %g3 = getelementptr i64, ptr %p, i64 6
  %v3 = load i64, ptr %g3
  %g4 = getelementptr i64, ptr %p, i64 8
  %v4 = load i64, ptr %g4
  %g5 = getelementptr i64, ptr %p, i64 10
  %v5 = load i64, ptr %g5
  %g6 = getelementptr i64, ptr %p, i64 12
  %v6 = load i64, ptr %g6
  %g7 = getelementptr i64, ptr %p, i64 14
  %v7 = load i64, ptr %g7
  %g8 = getelementptr i64, ptr %p, i64 16
  %v8 = load i64, ptr %g8
  %g9 = getelementptr i64, ptr %p, i64 18
  %v9 = load i64, ptr %g9
  %g10 = getelementptr i64, ptr %p, i64 20
  %v10 = load i64, ptr %g10
  %g11 = getelementptr i64, ptr %p, i64 22
  %v11 = load i64, ptr %g11
  %g12 = getelementptr i64, ptr %p, i64 24
  %v12 = load i64, ptr %g12
  %g13 = getelementptr i64, ptr %p, i64 26
  %v13 = load i64, ptr %g13
  %g14 = getelementptr i64, ptr %p, i64 28
  %v14 = load i64, ptr %g14
  %g15 = getelementptr i64, ptr %p, i64 30
  %v15 = load i64, ptr %g15
  %g16 = getelementptr i64, ptr %p, i64 32
  %v16 = load i64, ptr %g16
  %g17 = getelementptr i64, ptr %p, i64 34
  %v17 = load i64, ptr %g17
  %g18 = getelementptr i64, ptr %p, i64 36
  %v18 = load i64, ptr %g18
  %g19 = getelementptr i64, ptr %p, i64 38
  %v19 = load i64, ptr %g19
  %g20 = getelementptr i64, ptr %p, i64 40
  %v20 = load i64, ptr %g20
  %g21 = getelementptr i64, ptr %p, i64 42
  %v21 = load i64, ptr %g21
  %g22 = getelementptr i64, ptr %p, i64 44
  %v22 = load i64, ptr %g22
  %g23 = getelementptr i64, ptr %p, i64 46
  %v23 = load i64, ptr %g23
  %c0 = icmp ne i64 %v0, %v23
  %z0 = zext i1 %c0 to i64
  %a0 = add i64 0, %z0
  %c1 = icmp ne i64 %v1, %v22
  %z1 = zext i1 %c1 to i64
  %a1 = add i64 %a0, %z1
  %c2 = icmp ne i64 %v2, %v21
  %z2 = zext i1 %c2 to i64
  %a2 = add i64 %a1, %z2
  %c3 = icmp ne i64 %v3, %v20
  %z3 = zext i1 %c3 to i64
  %a3 = add i64 %a2, %z3
  %c4 = icmp ne i64 %v4, %v19
  %z4 = zext i1 %c4 to i64
  %a4 = add i64 %a3, %z4
  %c5 = icmp ne i64 %v5, %v18
  %z5 = zext i1 %c5 to i64
  %a5 = add i64 %a4, %z5
  %c6 = icmp ne i64 %v6, %v17
  %z6 = zext i1 %c6 to i64
  %a6 = add i64 %a5, %z6
  %c7 = icmp ne i64 %v7, %v16
  %z7 = zext i1 %c7 to i64
  %a7 = add i64 %a6, %z7
  %c8 = icmp ne i64 %v8, %v15
  %z8 = zext i1 %c8 to i64
  %a8 = add i64 %a7, %z8
  %c9 = icmp ne i64 %v9, %v14
  %z9 = zext i1 %c9 to i64
  %a9 = add i64 %a8, %z9
  %c10 = icmp ne i64 %v10, %v13
  %z10 = zext i1 %c10 to i64
  %a10 = add i64 %a9, %z10
  %c11 = icmp ne i64 %v11, %v12
  %z11 = zext i1 %c11 to i64
  %a11 = add i64 %a10, %z11
  %c12 = icmp ne i64 %v12, %v11
  %z12 = zext i1 %c12 to i64
  %a12 = add i64 %a11, %z12
  %c13 = icmp ne i64 %v13, %v10
  %z13 = zext i1 %c13 to i64
  %a13 = add i64 %a12, %z13
  %c14 = icmp ne i64 %v14, %v9
  %z14 = zext i1 %c14 to i64
  %a14 = add i64 %a13, %z14
  %c15 = icmp ne i64 %v15, %v8
  %z15 = zext i1 %c15 to i64
  %a15 = add i64 %a14, %z15
  %c16 = icmp ne i64 %v16, %v7
  %z16 = zext i1 %c16 to i64
  %a16 = add i64 %a15, %z16
  %c17 = icmp ne i64 %v17, %v6
  %z17 = zext i1 %c17 to i64
  %a17 = add i64 %a16, %z17
  %c18 = icmp ne i64 %v18, %v5
  %z18 = zext i1 %c18 to i64
  %a18 = add i64 %a17, %z18
  %c19 = icmp ne i64 %v19, %v4
  %z19 = zext i1 %c19 to i64
  %a19 = add i64 %a18, %z19
  %c20 = icmp ne i64 %v20, %v3
  %z20 = zext i1 %c20 to i64
  %a20 = add i64 %a19, %z20
  %c21 = icmp ne i64 %v21, %v2
  %z21 = zext i1 %c21 to i64
  %a21 = add i64 %a20, %z21
  %c22 = icmp ne i64 %v22, %v1
  %z22 = zext i1 %c22 to i64
  %a22 = add i64 %a21, %z22
  %c23 = icmp ne i64 %v23, %v0
  %z23 = zext i1 %c23 to i64
  %a23 = add i64 %a22, %z23
  ret i64 %a23
}

define i64 @spill_fcmp(ptr %p) {
; CHECK: func spill_fcmp ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 80: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi]: f64
; CHECK-NEXT:    $mm0: f64 = $mm0: f64 * [$rdi]: f64
; CHECK-NEXT:    [$rbp + -24]: i64 = $mm0: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 16: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 16]: f64
; CHECK-NEXT:    $mm0: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    [$rbp + -32]: i64 = $mm0: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 32: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 32]: f64
; CHECK-NEXT:    $mm0: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    [$rbp + -40]: i64 = $mm0: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 48: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 48]: f64
; CHECK-NEXT:    $mm0: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    [$rbp + -48]: i64 = $mm0: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 64: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 64]: f64
; CHECK-NEXT:    $mm0: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    [$rbp + -56]: i64 = $mm0: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 80: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 80]: f64
; CHECK-NEXT:    $mm0: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    [$rbp + -64]: i64 = $mm0: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 96: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 96]: f64
; CHECK-NEXT:    $mm0: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    [$rbp + -72]: i64 = $mm0: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 112: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 112]: f64
; CHECK-NEXT:    $mm0: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    [$rbp + -80]: i64 = $mm0: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 128: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 128]: f64
; CHECK-NEXT:    $mm0: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    [$rbp + -16]: i64 = $mm0: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 144: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 144]: f64
; CHECK-NEXT:    $mm15: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 160: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 160]: f64
; CHECK-NEXT:    $mm10: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 176: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 176]: f64
; CHECK-NEXT:    $mm4: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 192: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 192]: f64
; CHECK-NEXT:    $mm1: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 208: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 208]: f64
; CHECK-NEXT:    $mm3: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 224: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 224]: f64
; CHECK-NEXT:    $mm5: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 240: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 240]: f64
; CHECK-NEXT:    $mm6: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 256: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 256]: f64
; CHECK-NEXT:    $mm7: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 272: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 272]: f64
; CHECK-NEXT:    $mm8: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 288: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 288]: f64
; CHECK-NEXT:    $mm9: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 304: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 304]: f64
; CHECK-NEXT:    $mm11: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 320: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 320]: f64
; CHECK-NEXT:    $mm12: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 336: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 336]: f64
; CHECK-NEXT:    $mm13: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 352: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 352]: f64
; CHECK-NEXT:    $mm14: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 368: i64
; CHECK-NEXT:    $mm0: f64 = [$rdi + 368]: f64
; CHECK-NEXT:    $mm2: f64 = $mm0: f64 * [$rax]: f64
; CHECK-NEXT:    $mm0: f64 = [$rbp + -24]: i64
; CHECK-NEXT:    fcmp_une($al: i8, $mm0: f64, $mm2: f64, )
; CHECK-NEXT:    mov_zx($rax: i64, $al: i8, )
; CHECK-NEXT:    $mm0: f64 = [$rbp + -32]: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm0: f64, $mm14: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    $mm0: f64 = [$rbp + -40]: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm0: f64, $mm13: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    $mm0: f64 = [$rbp + -48]: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm0: f64, $mm12: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    $mm0: f64 = [$rbp + -56]: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm0: f64, $mm11: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    $mm0: f64 = [$rbp + -64]: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm0: f64, $mm9: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    $mm0: f64 = [$rbp + -72]: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm0: f64, $mm8: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    $mm0: f64 = [$rbp + -80]: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm0: f64, $mm7: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    $mm0: f64 = [$rbp + -16]: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm0: f64, $mm6: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm15: f64, $mm5: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm10: f64, $mm3: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm4: f64, $mm1: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm1: f64, $mm4: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm3: f64, $mm10: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm5: f64, $mm15: f64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm6: f64, [$rbp + -16]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm7: f64, [$rbp + -80]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm8: f64, [$rbp + -72]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm9: f64, [$rbp + -64]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm11: f64, [$rbp + -56]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm12: f64, [$rbp + -48]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm13: f64, [$rbp + -40]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm14: f64, [$rbp + -32]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    fcmp_une($cl: i8, $mm2: f64, [$rbp + -24]: i64, )
; CHECK-NEXT:    mov_zx($rcx: i64, $cl: i8, )
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    $rsp: i64 += 80: i64
; CHECK-NEXT:    ret($rax: i64, )
entry:
  %g0 = getelementptr double, ptr %p, i64 0
  %l0 = load double, ptr %g0
  %v0 = fmul double %l0, %l0
  %g1 = getelementptr double, ptr %p, i64 2
  %l1 = load double, ptr %g1
  %v1 = fmul double %l1, %l1
  %g2 = getelementptr double, ptr %p, i64 4
  %l2 = load double, ptr %g2
  %v2 = fmul double %l2, %l2
  %g3 = getelementptr double, ptr %p, i64 6
  %l3 = load double, ptr %g3
  %v3 = fmul double %l3, %l3
  %g4 = getelementptr double, ptr %p, i64 8
  %l4 = load double, ptr %g4
  %v4 = fmul double %l4, %l4
  %g5 = getelementptr double, ptr %p, i64 10
  %l5 = load double, ptr %g5
  %v5 = fmul double %l5, %l5
  %g6 = getelementptr double, ptr %p, i64 12
  %l6 = load double, ptr %g6
  %v6 = fmul double %l6, %l6
  %g7 = getelementptr double, ptr %p, i64 14
  %l7 = load double, ptr %g7
  %v7 = fmul double %l7, %l7
  %g8 = getelementptr double, ptr %p, i64 16
  %l8 = load double, ptr %g8
  %v8 = fmul double %l8, %l8
  %g9 = getelementptr double, ptr %p, i64 18
  %l9 = load double, ptr %g9
  %v9 = fmul double %l9, %l9
  %g10 = getelementptr double, ptr %p, i64 20
  %l10 = load double, ptr %g10
  %v10 = fmul double %l10, %l10
  %g11 = getelementptr double, ptr %p, i64 22
  %l11 = load double, ptr %g11
  %v11 = fmul double %l11, %l11
  %g12 = getelementptr double, ptr %p, i64 24
  %l12 = load double, ptr %g12
  %v12 = fmul double %l12, %l12
  %g13 = getelementptr double, ptr %p, i64 26
  %l13 = load double, ptr %g13
  %v13 = fmul double %l13, %l13
  %g14 = getelementptr double, ptr %p, i64 28
  %l14 = load double, ptr %g14
  %v14 = fmul double %l14, %l14
  %g15 = getelementptr double, ptr %p, i64 30
  %l15 = load double, ptr %g15
  %v15 = fmul double %l15, %l15
  %g16 = getelementptr double, ptr %p, i64 32
  %l16 = load double, ptr %g16
  %v16 = fmul double %l16, %l16
  %g17 = getelementptr double, ptr %p, i64 34
  %l17 = load double, ptr %g17
  %v17 = fmul double %l17, %l17
  %g18 = getelementptr double, ptr %p, i64 36
  %l18 = load double, ptr %g18
  %v18 = fmul double %l18, %l18
  %g19 = getelementptr double, ptr %p, i64 38
  %l19 = load double, ptr %g19
  %v19 = fmul double %l19, %l19
  %g20 = getelementptr double, ptr %p, i64 40
  %l20 = load double, ptr %g20
  %v20 = fmul double %l20, %l20
  %g21 = getelementptr double, ptr %p, i64 42
  %l21 = load double, ptr %g21
  %v21 = fmul double %l21, %l21
  %g22 = getelementptr double, ptr %p, i64 44
  %l22 = load double, ptr %g22
  %v22 = fmul double %l22, %l22
  %g23 = getelementptr double, ptr %p, i64 46
  %l23 = load double, ptr %g23
  %v23 = fmul double %l23, %l23
  %c0 = fcmp une double %v0, %v23
  %z0 = zext i1 %c0 to i64
  %a0 = add i64 0, %z0
  %c1 = fcmp une double %v1, %v22
  %z1 = zext i1 %c1 to i64
  %a1 = add i64 %a0, %z1
  %c2 = fcmp une double %v2, %v21
  %z2 = zext i1 %c2 to i64
  %a2 = add i64 %a1, %z2
  %c3 = fcmp une double %v3, %v20
  %z3 = zext i1 %c3 to i64
  %a3 = add i64 %a2, %z3
  %c4 = fcmp une double %v4, %v19
  %z4 = zext i1 %c4 to i64
  %a4 = add i64 %a3, %z4
  %c5 = fcmp une double %v5, %v18
  %z5 = zext i1 %c5 to i64
  %a5 = add i64 %a4, %z5
  %c6 = fcmp une double %v6, %v17
  %z6 = zext i1 %c6 to i64
  %a6 = add i64 %a5, %z6
  %c7 = fcmp une double %v7, %v16
  %z7 = zext i1 %c7 to i64
  %a7 = add i64 %a6, %z7
  %c8 = fcmp une double %v8, %v15
  %z8 = zext i1 %c8 to i64
  %a8 = add i64 %a7, %z8
  %c9 = fcmp une double %v9, %v14
  %z9 = zext i1 %c9 to i64
  %a9 = add i64 %a8, %z9
  %c10 = fcmp une double %v10, %v13
  %z10 = zext i1 %c10 to i64
  %a10 = add i64 %a9, %z10
  %c11 = fcmp une double %v11, %v12
  %z11 = zext i1 %c11 to i64
  %a11 = add i64 %a10, %z11
  %c12 = fcmp une double %v12, %v11
  %z12 = zext i1 %c12 to i64
  %a12 = add i64 %a11, %z12
  %c13 = fcmp une double %v13, %v10
  %z13 = zext i1 %c13 to i64
  %a13 = add i64 %a12, %z13
  %c14 = fcmp une double %v14, %v9
  %z14 = zext i1 %c14 to i64
  %a14 = add i64 %a13, %z14
  %c15 = fcmp une double %v15, %v8
  %z15 = zext i1 %c15 to i64
  %a15 = add i64 %a14, %z15
  %c16 = fcmp une double %v16, %v7
  %z16 = zext i1 %c16 to i64
  %a16 = add i64 %a15, %z16
  %c17 = fcmp une double %v17, %v6
  %z17 = zext i1 %c17 to i64
  %a17 = add i64 %a16, %z17
  %c18 = fcmp une double %v18, %v5
  %z18 = zext i1 %c18 to i64
  %a18 = add i64 %a17, %z18
  %c19 = fcmp une double %v19, %v4
  %z19 = zext i1 %c19 to i64
  %a19 = add i64 %a18, %z19
  %c20 = fcmp une double %v20, %v3
  %z20 = zext i1 %c20 to i64
  %a20 = add i64 %a19, %z20
  %c21 = fcmp une double %v21, %v2
  %z21 = zext i1 %c21 to i64
  %a21 = add i64 %a20, %z21
  %c22 = fcmp une double %v22, %v1
  %z22 = zext i1 %c22 to i64
  %a22 = add i64 %a21, %z22
  %c23 = fcmp une double %v23, %v0
  %z23 = zext i1 %c23 to i64
  %a23 = add i64 %a22, %z23
  ret i64 %a23
}

