; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Regression test for register allocator spilling of i64.
; All values are live at the same time so some of them have to be spilled,
; the stack slots have to match the size of the type (8 bytes).
; RUN: %foffcc %s --print-mir | FileCheck %s

define i64 @spill_i64(ptr %p) {
; CHECK: func spill_i64 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 160: i64
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r15: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $rax: i64 = [$rdi]: i64
; CHECK-NEXT:    [$rbp + -136]: i64 = $rax: i64
; CHECK-NEXT:    $rbx: i64 = $rdi: i64
; CHECK-NEXT:    $rbx: i64 += 16: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 16]: i64
; CHECK-NEXT:    [$rbp + -128]: i64 = $rax: i64
; CHECK-NEXT:    $rcx: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 += 32: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 32]: i64
; CHECK-NEXT:    [$rbp + -120]: i64 = $rax: i64
; CHECK-NEXT:    $rdx: i64 = $rdi: i64
; CHECK-NEXT:    $rdx: i64 += 48: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 48]: i64
; CHECK-NEXT:    [$rbp + -112]: i64 = $rax: i64
; CHECK-NEXT:    $rsi: i64 = $rdi: i64
; CHECK-NEXT:    $rsi: i64 += 64: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 64]: i64
; CHECK-NEXT:    [$rbp + -104]: i64 = $rax: i64
; CHECK-NEXT:    $r8: i64 = $rdi: i64
; CHECK-NEXT:    $r8: i64 += 80: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 80]: i64
; CHECK-NEXT:    [$rbp + -96]: i64 = $rax: i64
; CHECK-NEXT:    $r9: i64 = $rdi: i64
; CHECK-NEXT:    $r9: i64 += 96: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 96]: i64
; CHECK-NEXT:    [$rbp + -88]: i64 = $rax: i64
; CHECK-NEXT:    $r10: i64 = $rdi: i64
; CHECK-NEXT:    $r10: i64 += 112: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 112]: i64
; CHECK-NEXT:    [$rbp + -80]: i64 = $rax: i64
; CHECK-NEXT:    $r11: i64 = $rdi: i64
; CHECK-NEXT:    $r11: i64 += 128: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 128]: i64
; CHECK-NEXT:    [$rbp + -72]: i64 = $rax: i64
; CHECK-NEXT:    $r12: i64 = $rdi: i64
; CHECK-NEXT:    $r12: i64 += 144: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 144]: i64
; CHECK-NEXT:    [$rbp + -64]: i64 = $rax: i64
; CHECK-NEXT:    $r13: i64 = $rdi: i64
; CHECK-NEXT:    $r13: i64 += 160: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 160]: i64
; CHECK-NEXT:    [$rbp + -56]: i64 = $rax: i64
; CHECK-NEXT:    $r14: i64 = $rdi: i64
; CHECK-NEXT:    $r14: i64 += 176: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 176]: i64
; CHECK-NEXT:    [$rbp + -48]: i64 = $rax: i64
; CHECK-NEXT:    $r15: i64 = $rdi: i64
; CHECK-NEXT:    $r15: i64 += 192: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 192]: i64
; CHECK-NEXT:    [$rbp + -40]: i64 = $rax: i64
; CHECK-NEXT:    [$rbp + -160]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -160]: i64 += 208: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 208]: i64
; CHECK-NEXT:    [$rbp + -32]: i64 = $rax: i64
; CHECK-NEXT:    [$rbp + -152]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -152]: i64 += 224: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 224]: i64
; CHECK-NEXT:    [$rbp + -24]: i64 = $rax: i64
; CHECK-NEXT:    [$rbp + -144]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -144]: i64 += 240: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 240]: i64
; CHECK-NEXT:    [$rbp + -16]: i64 = $rax: i64
; CHECK-NEXT:    $rax: i64 = [$rdi]: i64
; CHECK-NEXT:    $rax: i64 += [$rbx]: i64
; CHECK-NEXT:    $rax: i64 += [$rcx]: i64
; CHECK-NEXT:    $rax: i64 += [$rdx]: i64
; CHECK-NEXT:    $rax: i64 += [$rsi]: i64
; CHECK-NEXT:    $rax: i64 += [$r8]: i64
; CHECK-NEXT:    $rax: i64 += [$r9]: i64
; CHECK-NEXT:    $rax: i64 += [$r10]: i64
; CHECK-NEXT:    $rax: i64 += [$r11]: i64
; CHECK-NEXT:    $rax: i64 += [$r12]: i64
; CHECK-NEXT:    $rax: i64 += [$r13]: i64
; CHECK-NEXT:    $rax: i64 += [$r14]: i64
; CHECK-NEXT:    $rax: i64 += [$r15]: i64
; CHECK-NEXT:    $rbx: i64 = [$rbp + -160]: i64
; CHECK-NEXT:    $rax: i64 += [$rbx]: i64
; CHECK-NEXT:    $rbx: i64 = [$rbp + -152]: i64
; CHECK-NEXT:    $rax: i64 += [$rbx]: i64
; CHECK-NEXT:    $rbx: i64 = [$rbp + -144]: i64
; CHECK-NEXT:    $rax: i64 += [$rbx]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -136]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -128]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -120]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -112]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -104]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -96]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -88]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -80]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -72]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -64]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -56]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -48]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -40]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -32]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -24]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -16]: i64
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($r15: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 160: i64
; CHECK-NEXT:    ret($rax: i64, )
entry:
  %g0 = getelementptr inbounds i64, ptr %p, i64 0
  %v0 = load i64, ptr %g0
  %g1 = getelementptr inbounds i64, ptr %p, i64 2
  %v1 = load i64, ptr %g1
  %g2 = getelementptr inbounds i64, ptr %p, i64 4
  %v2 = load i64, ptr %g2
  %g3 = getelementptr inbounds i64, ptr %p, i64 6
  %v3 = load i64, ptr %g3
  %g4 = getelementptr inbounds i64, ptr %p, i64 8
  %v4 = load i64, ptr %g4
  %g5 = getelementptr inbounds i64, ptr %p, i64 10
  %v5 = load i64, ptr %g5
  %g6 = getelementptr inbounds i64, ptr %p, i64 12
  %v6 = load i64, ptr %g6
  %g7 = getelementptr inbounds i64, ptr %p, i64 14
  %v7 = load i64, ptr %g7
  %g8 = getelementptr inbounds i64, ptr %p, i64 16
  %v8 = load i64, ptr %g8
  %g9 = getelementptr inbounds i64, ptr %p, i64 18
  %v9 = load i64, ptr %g9
  %g10 = getelementptr inbounds i64, ptr %p, i64 20
  %v10 = load i64, ptr %g10
  %g11 = getelementptr inbounds i64, ptr %p, i64 22
  %v11 = load i64, ptr %g11
  %g12 = getelementptr inbounds i64, ptr %p, i64 24
  %v12 = load i64, ptr %g12
  %g13 = getelementptr inbounds i64, ptr %p, i64 26
  %v13 = load i64, ptr %g13
  %g14 = getelementptr inbounds i64, ptr %p, i64 28
  %v14 = load i64, ptr %g14
  %g15 = getelementptr inbounds i64, ptr %p, i64 30
  %v15 = load i64, ptr %g15
  %s1 = add i64 %v0, %v1
  %s2 = add i64 %s1, %v2
  %s3 = add i64 %s2, %v3
  %s4 = add i64 %s3, %v4
  %s5 = add i64 %s4, %v5
  %s6 = add i64 %s5, %v6
  %s7 = add i64 %s6, %v7
  %s8 = add i64 %s7, %v8
  %s9 = add i64 %s8, %v9
  %s10 = add i64 %s9, %v10
  %s11 = add i64 %s10, %v11
  %s12 = add i64 %s11, %v12
  %s13 = add i64 %s12, %v13
  %s14 = add i64 %s13, %v14
  %s15 = add i64 %s14, %v15
  %m0 = xor i64 %s15, %v0
  %m1 = xor i64 %m0, %v1
  %m2 = xor i64 %m1, %v2
  %m3 = xor i64 %m2, %v3
  %m4 = xor i64 %m3, %v4
  %m5 = xor i64 %m4, %v5
  %m6 = xor i64 %m5, %v6
  %m7 = xor i64 %m6, %v7
  %m8 = xor i64 %m7, %v8
  %m9 = xor i64 %m8, %v9
  %m10 = xor i64 %m9, %v10
  %m11 = xor i64 %m10, %v11
  %m12 = xor i64 %m11, %v12
  %m13 = xor i64 %m12, %v13
  %m14 = xor i64 %m13, %v14
  %m15 = xor i64 %m14, %v15
  ret i64 %m15
}
