; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Regression tests for register allocator spilling of integers.
; All values are live at the same time so some of them have to be spilled,
; the stack slots have to match the size of the type.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

define i8 @spill_i8(ptr %p) {
; CHECK: func spill_i8 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 48: i64
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r15: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $al: i32 = [$rdi]: i8
; CHECK-NEXT:    [$rbp + -24]: i8 = $al: i8
; CHECK-NEXT:    $rcx: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 += 2: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 2]: i8
; CHECK-NEXT:    [$rbp + -23]: i8 = $al: i8
; CHECK-NEXT:    $rdx: i64 = $rdi: i64
; CHECK-NEXT:    $rdx: i64 += 4: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 4]: i8
; CHECK-NEXT:    [$rbp + -22]: i8 = $al: i8
; CHECK-NEXT:    $rsi: i64 = $rdi: i64
; CHECK-NEXT:    $rsi: i64 += 6: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 6]: i8
; CHECK-NEXT:    [$rbp + -21]: i8 = $al: i8
; CHECK-NEXT:    $r8: i64 = $rdi: i64
; CHECK-NEXT:    $r8: i64 += 8: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 8]: i8
; CHECK-NEXT:    [$rbp + -20]: i8 = $al: i8
; CHECK-NEXT:    $r9: i64 = $rdi: i64
; CHECK-NEXT:    $r9: i64 += 10: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 10]: i8
; CHECK-NEXT:    [$rbp + -19]: i8 = $al: i8
; CHECK-NEXT:    $r10: i64 = $rdi: i64
; CHECK-NEXT:    $r10: i64 += 12: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 12]: i8
; CHECK-NEXT:    [$rbp + -18]: i8 = $al: i8
; CHECK-NEXT:    $r11: i64 = $rdi: i64
; CHECK-NEXT:    $r11: i64 += 14: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 14]: i8
; CHECK-NEXT:    [$rbp + -17]: i8 = $al: i8
; CHECK-NEXT:    $rbx: i64 = $rdi: i64
; CHECK-NEXT:    $rbx: i64 += 16: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 16]: i8
; CHECK-NEXT:    [$rbp + -16]: i8 = $al: i8
; CHECK-NEXT:    $r12: i64 = $rdi: i64
; CHECK-NEXT:    $r12: i64 += 18: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 18]: i8
; CHECK-NEXT:    [$rbp + -15]: i8 = $al: i8
; CHECK-NEXT:    $r13: i64 = $rdi: i64
; CHECK-NEXT:    $r13: i64 += 20: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 20]: i8
; CHECK-NEXT:    [$rbp + -14]: i8 = $al: i8
; CHECK-NEXT:    $r14: i64 = $rdi: i64
; CHECK-NEXT:    $r14: i64 += 22: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 22]: i8
; CHECK-NEXT:    [$rbp + -13]: i8 = $al: i8
; CHECK-NEXT:    $r15: i64 = $rdi: i64
; CHECK-NEXT:    $r15: i64 += 24: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 24]: i8
; CHECK-NEXT:    [$rbp + -12]: i8 = $al: i8
; CHECK-NEXT:    [$rbp + -48]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -48]: i64 += 26: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 26]: i8
; CHECK-NEXT:    [$rbp + -11]: i8 = $al: i8
; CHECK-NEXT:    [$rbp + -40]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -40]: i64 += 28: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 28]: i8
; CHECK-NEXT:    [$rbp + -10]: i8 = $al: i8
; CHECK-NEXT:    [$rbp + -32]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -32]: i64 += 30: i64
; CHECK-NEXT:    $al: i32 = [$rdi + 30]: i8
; CHECK-NEXT:    [$rbp + -9]: i8 = $al: i8
; CHECK-NEXT:    $al: i32 = [$rdi]: i8
; CHECK-NEXT:    $al: i8 += [$rcx]: i8
; CHECK-NEXT:    $al: i8 += [$rdx]: i8
; CHECK-NEXT:    $al: i8 += [$rsi]: i8
; CHECK-NEXT:    $al: i8 += [$r8]: i8
; CHECK-NEXT:    $al: i8 += [$r9]: i8
; CHECK-NEXT:    $al: i8 += [$r10]: i8
; CHECK-NEXT:    $al: i8 += [$r11]: i8
; CHECK-NEXT:    $al: i8 += [$rbx]: i8
; CHECK-NEXT:    $al: i8 += [$r12]: i8
; CHECK-NEXT:    $al: i8 += [$r13]: i8
; CHECK-NEXT:    $al: i8 += [$r14]: i8
; CHECK-NEXT:    $al: i8 += [$r15]: i8
; CHECK-NEXT:    $rcx: i64 = [$rbp + -48]: i64
; CHECK-NEXT:    $al: i8 += [$rcx]: i8
; CHECK-NEXT:    $rcx: i64 = [$rbp + -40]: i64
; CHECK-NEXT:    $al: i8 += [$rcx]: i8
; CHECK-NEXT:    $rcx: i64 = [$rbp + -32]: i64
; CHECK-NEXT:    $al: i8 += [$rcx]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -24]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -23]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -22]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -21]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -20]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -19]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -18]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -17]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -16]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -15]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -14]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -13]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -12]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -11]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -10]: i8
; CHECK-NEXT:    $al: i8 ^= [$rbp + -9]: i8
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($r15: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 48: i64
; CHECK-NEXT:    ret($al: i8, )
entry:
  %g0 = getelementptr inbounds i8, ptr %p, i64 0
  %v0 = load i8, ptr %g0
  %g1 = getelementptr inbounds i8, ptr %p, i64 2
  %v1 = load i8, ptr %g1
  %g2 = getelementptr inbounds i8, ptr %p, i64 4
  %v2 = load i8, ptr %g2
  %g3 = getelementptr inbounds i8, ptr %p, i64 6
  %v3 = load i8, ptr %g3
  %g4 = getelementptr inbounds i8, ptr %p, i64 8
  %v4 = load i8, ptr %g4
  %g5 = getelementptr inbounds i8, ptr %p, i64 10
  %v5 = load i8, ptr %g5
  %g6 = getelementptr inbounds i8, ptr %p, i64 12
  %v6 = load i8, ptr %g6
  %g7 = getelementptr inbounds i8, ptr %p, i64 14
  %v7 = load i8, ptr %g7
  %g8 = getelementptr inbounds i8, ptr %p, i64 16
  %v8 = load i8, ptr %g8
  %g9 = getelementptr inbounds i8, ptr %p, i64 18
  %v9 = load i8, ptr %g9
  %g10 = getelementptr inbounds i8, ptr %p, i64 20
  %v10 = load i8, ptr %g10
  %g11 = getelementptr inbounds i8, ptr %p, i64 22
  %v11 = load i8, ptr %g11
  %g12 = getelementptr inbounds i8, ptr %p, i64 24
  %v12 = load i8, ptr %g12
  %g13 = getelementptr inbounds i8, ptr %p, i64 26
  %v13 = load i8, ptr %g13
  %g14 = getelementptr inbounds i8, ptr %p, i64 28
  %v14 = load i8, ptr %g14
  %g15 = getelementptr inbounds i8, ptr %p, i64 30
  %v15 = load i8, ptr %g15
  %s1 = add i8 %v0, %v1
  %s2 = add i8 %s1, %v2
  %s3 = add i8 %s2, %v3
  %s4 = add i8 %s3, %v4
  %s5 = add i8 %s4, %v5
  %s6 = add i8 %s5, %v6
  %s7 = add i8 %s6, %v7
  %s8 = add i8 %s7, %v8
  %s9 = add i8 %s8, %v9
  %s10 = add i8 %s9, %v10
  %s11 = add i8 %s10, %v11
  %s12 = add i8 %s11, %v12
  %s13 = add i8 %s12, %v13
  %s14 = add i8 %s13, %v14
  %s15 = add i8 %s14, %v15
  %m0 = xor i8 %s15, %v0
  %m1 = xor i8 %m0, %v1
  %m2 = xor i8 %m1, %v2
  %m3 = xor i8 %m2, %v3
  %m4 = xor i8 %m3, %v4
  %m5 = xor i8 %m4, %v5
  %m6 = xor i8 %m5, %v6
  %m7 = xor i8 %m6, %v7
  %m8 = xor i8 %m7, %v8
  %m9 = xor i8 %m8, %v9
  %m10 = xor i8 %m9, %v10
  %m11 = xor i8 %m10, %v11
  %m12 = xor i8 %m11, %v12
  %m13 = xor i8 %m12, %v13
  %m14 = xor i8 %m13, %v14
  %m15 = xor i8 %m14, %v15
  ret i8 %m15
}

define i16 @spill_i16(ptr %p) {
; CHECK: func spill_i16 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 64: i64
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r15: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $ax: i32 = [$rdi]: i16
; CHECK-NEXT:    [$rbp + -40]: i16 = $ax: i16
; CHECK-NEXT:    $rcx: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 += 4: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 4]: i16
; CHECK-NEXT:    [$rbp + -38]: i16 = $ax: i16
; CHECK-NEXT:    $rdx: i64 = $rdi: i64
; CHECK-NEXT:    $rdx: i64 += 8: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 8]: i16
; CHECK-NEXT:    [$rbp + -36]: i16 = $ax: i16
; CHECK-NEXT:    $rsi: i64 = $rdi: i64
; CHECK-NEXT:    $rsi: i64 += 12: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 12]: i16
; CHECK-NEXT:    [$rbp + -34]: i16 = $ax: i16
; CHECK-NEXT:    $r8: i64 = $rdi: i64
; CHECK-NEXT:    $r8: i64 += 16: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 16]: i16
; CHECK-NEXT:    [$rbp + -32]: i16 = $ax: i16
; CHECK-NEXT:    $r9: i64 = $rdi: i64
; CHECK-NEXT:    $r9: i64 += 20: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 20]: i16
; CHECK-NEXT:    [$rbp + -30]: i16 = $ax: i16
; CHECK-NEXT:    $r10: i64 = $rdi: i64
; CHECK-NEXT:    $r10: i64 += 24: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 24]: i16
; CHECK-NEXT:    [$rbp + -28]: i16 = $ax: i16
; CHECK-NEXT:    $r11: i64 = $rdi: i64
; CHECK-NEXT:    $r11: i64 += 28: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 28]: i16
; CHECK-NEXT:    [$rbp + -26]: i16 = $ax: i16
; CHECK-NEXT:    $rbx: i64 = $rdi: i64
; CHECK-NEXT:    $rbx: i64 += 32: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 32]: i16
; CHECK-NEXT:    [$rbp + -24]: i16 = $ax: i16
; CHECK-NEXT:    $r12: i64 = $rdi: i64
; CHECK-NEXT:    $r12: i64 += 36: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 36]: i16
; CHECK-NEXT:    [$rbp + -22]: i16 = $ax: i16
; CHECK-NEXT:    $r13: i64 = $rdi: i64
; CHECK-NEXT:    $r13: i64 += 40: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 40]: i16
; CHECK-NEXT:    [$rbp + -20]: i16 = $ax: i16
; CHECK-NEXT:    $r14: i64 = $rdi: i64
; CHECK-NEXT:    $r14: i64 += 44: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 44]: i16
; CHECK-NEXT:    [$rbp + -18]: i16 = $ax: i16
; CHECK-NEXT:    $r15: i64 = $rdi: i64
; CHECK-NEXT:    $r15: i64 += 48: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 48]: i16
; CHECK-NEXT:    [$rbp + -16]: i16 = $ax: i16
; CHECK-NEXT:    [$rbp + -64]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -64]: i64 += 52: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 52]: i16
; CHECK-NEXT:    [$rbp + -14]: i16 = $ax: i16
; CHECK-NEXT:    [$rbp + -56]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -56]: i64 += 56: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 56]: i16
; CHECK-NEXT:    [$rbp + -12]: i16 = $ax: i16
; CHECK-NEXT:    [$rbp + -48]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -48]: i64 += 60: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 60]: i16
; CHECK-NEXT:    [$rbp + -10]: i16 = $ax: i16
; CHECK-NEXT:    $ax: i32 = [$rdi]: i16
; CHECK-NEXT:    $ax: i16 += [$rcx]: i16
; CHECK-NEXT:    $ax: i16 += [$rdx]: i16
; CHECK-NEXT:    $ax: i16 += [$rsi]: i16
; CHECK-NEXT:    $ax: i16 += [$r8]: i16
; CHECK-NEXT:    $ax: i16 += [$r9]: i16
; CHECK-NEXT:    $ax: i16 += [$r10]: i16
; CHECK-NEXT:    $ax: i16 += [$r11]: i16
; CHECK-NEXT:    $ax: i16 += [$rbx]: i16
; CHECK-NEXT:    $ax: i16 += [$r12]: i16
; CHECK-NEXT:    $ax: i16 += [$r13]: i16
; CHECK-NEXT:    $ax: i16 += [$r14]: i16
; CHECK-NEXT:    $ax: i16 += [$r15]: i16
; CHECK-NEXT:    $rcx: i64 = [$rbp + -64]: i64
; CHECK-NEXT:    $ax: i16 += [$rcx]: i16
; CHECK-NEXT:    $rcx: i64 = [$rbp + -56]: i64
; CHECK-NEXT:    $ax: i16 += [$rcx]: i16
; CHECK-NEXT:    $rcx: i64 = [$rbp + -48]: i64
; CHECK-NEXT:    $ax: i16 += [$rcx]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -40]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -38]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -36]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -34]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -32]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -30]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -28]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -26]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -24]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -22]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -20]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -18]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -16]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -14]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -12]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -10]: i16
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($r15: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 64: i64
; CHECK-NEXT:    ret($ax: i16, )
entry:
  %g0 = getelementptr inbounds i16, ptr %p, i64 0
  %v0 = load i16, ptr %g0
  %g1 = getelementptr inbounds i16, ptr %p, i64 2
  %v1 = load i16, ptr %g1
  %g2 = getelementptr inbounds i16, ptr %p, i64 4
  %v2 = load i16, ptr %g2
  %g3 = getelementptr inbounds i16, ptr %p, i64 6
  %v3 = load i16, ptr %g3
  %g4 = getelementptr inbounds i16, ptr %p, i64 8
  %v4 = load i16, ptr %g4
  %g5 = getelementptr inbounds i16, ptr %p, i64 10
  %v5 = load i16, ptr %g5
  %g6 = getelementptr inbounds i16, ptr %p, i64 12
  %v6 = load i16, ptr %g6
  %g7 = getelementptr inbounds i16, ptr %p, i64 14
  %v7 = load i16, ptr %g7
  %g8 = getelementptr inbounds i16, ptr %p, i64 16
  %v8 = load i16, ptr %g8
  %g9 = getelementptr inbounds i16, ptr %p, i64 18
  %v9 = load i16, ptr %g9
  %g10 = getelementptr inbounds i16, ptr %p, i64 20
  %v10 = load i16, ptr %g10
  %g11 = getelementptr inbounds i16, ptr %p, i64 22
  %v11 = load i16, ptr %g11
  %g12 = getelementptr inbounds i16, ptr %p, i64 24
  %v12 = load i16, ptr %g12
  %g13 = getelementptr inbounds i16, ptr %p, i64 26
  %v13 = load i16, ptr %g13
  %g14 = getelementptr inbounds i16, ptr %p, i64 28
  %v14 = load i16, ptr %g14
  %g15 = getelementptr inbounds i16, ptr %p, i64 30
  %v15 = load i16, ptr %g15
  %s1 = add i16 %v0, %v1
  %s2 = add i16 %s1, %v2
  %s3 = add i16 %s2, %v3
  %s4 = add i16 %s3, %v4
  %s5 = add i16 %s4, %v5
  %s6 = add i16 %s5, %v6
  %s7 = add i16 %s6, %v7
  %s8 = add i16 %s7, %v8
  %s9 = add i16 %s8, %v9
  %s10 = add i16 %s9, %v10
  %s11 = add i16 %s10, %v11
  %s12 = add i16 %s11, %v12
  %s13 = add i16 %s12, %v13
  %s14 = add i16 %s13, %v14
  %s15 = add i16 %s14, %v15
  %m0 = xor i16 %s15, %v0
  %m1 = xor i16 %m0, %v1
  %m2 = xor i16 %m1, %v2
  %m3 = xor i16 %m2, %v3
  %m4 = xor i16 %m3, %v4
  %m5 = xor i16 %m4, %v5
  %m6 = xor i16 %m5, %v6
  %m7 = xor i16 %m6, %v7
  %m8 = xor i16 %m7, %v8
  %m9 = xor i16 %m8, %v9
  %m10 = xor i16 %m9, %v10
  %m11 = xor i16 %m10, %v11
  %m12 = xor i16 %m11, %v12
  %m13 = xor i16 %m12, %v13
  %m14 = xor i16 %m13, %v14
  %m15 = xor i16 %m14, %v15
  ret i16 %m15
}

define i32 @spill_i32(ptr %p) {
; CHECK: func spill_i32 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 96: i64
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r15: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $eax: i32 = [$rdi]: i32
; CHECK-NEXT:    [$rbp + -72]: i32 = $eax: i32
; CHECK-NEXT:    $rcx: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 += 8: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 8]: i32
; CHECK-NEXT:    [$rbp + -68]: i32 = $eax: i32
; CHECK-NEXT:    $rdx: i64 = $rdi: i64
; CHECK-NEXT:    $rdx: i64 += 16: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 16]: i32
; CHECK-NEXT:    [$rbp + -64]: i32 = $eax: i32
; CHECK-NEXT:    $rsi: i64 = $rdi: i64
; CHECK-NEXT:    $rsi: i64 += 24: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 24]: i32
; CHECK-NEXT:    [$rbp + -60]: i32 = $eax: i32
; CHECK-NEXT:    $r8: i64 = $rdi: i64
; CHECK-NEXT:    $r8: i64 += 32: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 32]: i32
; CHECK-NEXT:    [$rbp + -56]: i32 = $eax: i32
; CHECK-NEXT:    $r9: i64 = $rdi: i64
; CHECK-NEXT:    $r9: i64 += 40: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 40]: i32
; CHECK-NEXT:    [$rbp + -52]: i32 = $eax: i32
; CHECK-NEXT:    $r10: i64 = $rdi: i64
; CHECK-NEXT:    $r10: i64 += 48: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 48]: i32
; CHECK-NEXT:    [$rbp + -48]: i32 = $eax: i32
; CHECK-NEXT:    $r11: i64 = $rdi: i64
; CHECK-NEXT:    $r11: i64 += 56: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 56]: i32
; CHECK-NEXT:    [$rbp + -44]: i32 = $eax: i32
; CHECK-NEXT:    $rbx: i64 = $rdi: i64
; CHECK-NEXT:    $rbx: i64 += 64: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 64]: i32
; CHECK-NEXT:    [$rbp + -40]: i32 = $eax: i32
; CHECK-NEXT:    $r12: i64 = $rdi: i64
; CHECK-NEXT:    $r12: i64 += 72: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 72]: i32
; CHECK-NEXT:    [$rbp + -36]: i32 = $eax: i32
; CHECK-NEXT:    $r13: i64 = $rdi: i64
; CHECK-NEXT:    $r13: i64 += 80: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 80]: i32
; CHECK-NEXT:    [$rbp + -32]: i32 = $eax: i32
; CHECK-NEXT:    $r14: i64 = $rdi: i64
; CHECK-NEXT:    $r14: i64 += 88: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 88]: i32
; CHECK-NEXT:    [$rbp + -28]: i32 = $eax: i32
; CHECK-NEXT:    $r15: i64 = $rdi: i64
; CHECK-NEXT:    $r15: i64 += 96: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 96]: i32
; CHECK-NEXT:    [$rbp + -24]: i32 = $eax: i32
; CHECK-NEXT:    [$rbp + -96]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -96]: i64 += 104: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 104]: i32
; CHECK-NEXT:    [$rbp + -20]: i32 = $eax: i32
; CHECK-NEXT:    [$rbp + -88]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -88]: i64 += 112: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 112]: i32
; CHECK-NEXT:    [$rbp + -16]: i32 = $eax: i32
; CHECK-NEXT:    [$rbp + -80]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -80]: i64 += 120: i64
; CHECK-NEXT:    $eax: i32 = [$rdi + 120]: i32
; CHECK-NEXT:    [$rbp + -12]: i32 = $eax: i32
; CHECK-NEXT:    $eax: i32 = [$rdi]: i32
; CHECK-NEXT:    $eax: i32 += [$rcx]: i32
; CHECK-NEXT:    $eax: i32 += [$rdx]: i32
; CHECK-NEXT:    $eax: i32 += [$rsi]: i32
; CHECK-NEXT:    $eax: i32 += [$r8]: i32
; CHECK-NEXT:    $eax: i32 += [$r9]: i32
; CHECK-NEXT:    $eax: i32 += [$r10]: i32
; CHECK-NEXT:    $eax: i32 += [$r11]: i32
; CHECK-NEXT:    $eax: i32 += [$rbx]: i32
; CHECK-NEXT:    $eax: i32 += [$r12]: i32
; CHECK-NEXT:    $eax: i32 += [$r13]: i32
; CHECK-NEXT:    $eax: i32 += [$r14]: i32
; CHECK-NEXT:    $eax: i32 += [$r15]: i32
; CHECK-NEXT:    $rcx: i64 = [$rbp + -96]: i64
; CHECK-NEXT:    $eax: i32 += [$rcx]: i32
; CHECK-NEXT:    $rcx: i64 = [$rbp + -88]: i64
; CHECK-NEXT:    $eax: i32 += [$rcx]: i32
; CHECK-NEXT:    $rcx: i64 = [$rbp + -80]: i64
; CHECK-NEXT:    $eax: i32 += [$rcx]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -72]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -68]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -64]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -60]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -56]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -52]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -48]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -44]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -40]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -36]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -32]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -28]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -24]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -20]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -16]: i32
; CHECK-NEXT:    $eax: i32 ^= [$rbp + -12]: i32
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($r15: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 96: i64
; CHECK-NEXT:    ret($eax: i32, )
entry:
  %g0 = getelementptr inbounds i32, ptr %p, i64 0
  %v0 = load i32, ptr %g0
  %g1 = getelementptr inbounds i32, ptr %p, i64 2
  %v1 = load i32, ptr %g1
  %g2 = getelementptr inbounds i32, ptr %p, i64 4
  %v2 = load i32, ptr %g2
  %g3 = getelementptr inbounds i32, ptr %p, i64 6
  %v3 = load i32, ptr %g3
  %g4 = getelementptr inbounds i32, ptr %p, i64 8
  %v4 = load i32, ptr %g4
  %g5 = getelementptr inbounds i32, ptr %p, i64 10
  %v5 = load i32, ptr %g5
  %g6 = getelementptr inbounds i32, ptr %p, i64 12
  %v6 = load i32, ptr %g6
  %g7 = getelementptr inbounds i32, ptr %p, i64 14
  %v7 = load i32, ptr %g7
  %g8 = getelementptr inbounds i32, ptr %p, i64 16
  %v8 = load i32, ptr %g8
  %g9 = getelementptr inbounds i32, ptr %p, i64 18
  %v9 = load i32, ptr %g9
  %g10 = getelementptr inbounds i32, ptr %p, i64 20
  %v10 = load i32, ptr %g10
  %g11 = getelementptr inbounds i32, ptr %p, i64 22
  %v11 = load i32, ptr %g11
  %g12 = getelementptr inbounds i32, ptr %p, i64 24
  %v12 = load i32, ptr %g12
  %g13 = getelementptr inbounds i32, ptr %p, i64 26
  %v13 = load i32, ptr %g13
  %g14 = getelementptr inbounds i32, ptr %p, i64 28
  %v14 = load i32, ptr %g14
  %g15 = getelementptr inbounds i32, ptr %p, i64 30
  %v15 = load i32, ptr %g15
  %s1 = add i32 %v0, %v1
  %s2 = add i32 %s1, %v2
  %s3 = add i32 %s2, %v3
  %s4 = add i32 %s3, %v4
  %s5 = add i32 %s4, %v5
  %s6 = add i32 %s5, %v6
  %s7 = add i32 %s6, %v7
  %s8 = add i32 %s7, %v8
  %s9 = add i32 %s8, %v9
  %s10 = add i32 %s9, %v10
  %s11 = add i32 %s10, %v11
  %s12 = add i32 %s11, %v12
  %s13 = add i32 %s12, %v13
  %s14 = add i32 %s13, %v14
  %s15 = add i32 %s14, %v15
  %m0 = xor i32 %s15, %v0
  %m1 = xor i32 %m0, %v1
  %m2 = xor i32 %m1, %v2
  %m3 = xor i32 %m2, %v3
  %m4 = xor i32 %m3, %v4
  %m5 = xor i32 %m4, %v5
  %m6 = xor i32 %m5, %v6
  %m7 = xor i32 %m6, %v7
  %m8 = xor i32 %m7, %v8
  %m9 = xor i32 %m8, %v9
  %m10 = xor i32 %m9, %v10
  %m11 = xor i32 %m10, %v11
  %m12 = xor i32 %m11, %v12
  %m13 = xor i32 %m12, %v13
  %m14 = xor i32 %m13, %v14
  %m15 = xor i32 %m14, %v15
  ret i32 %m15
}

define i64 @spill_i64(ptr %p) {
; CHECK: func spill_i64 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 160: i64
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r15: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $rax: i64 = [$rdi]: i64
; CHECK-NEXT:    [$rbp + -136]: i64 = $rax: i64
; CHECK-NEXT:    $rcx: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 += 16: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 16]: i64
; CHECK-NEXT:    [$rbp + -128]: i64 = $rax: i64
; CHECK-NEXT:    $rdx: i64 = $rdi: i64
; CHECK-NEXT:    $rdx: i64 += 32: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 32]: i64
; CHECK-NEXT:    [$rbp + -120]: i64 = $rax: i64
; CHECK-NEXT:    $rsi: i64 = $rdi: i64
; CHECK-NEXT:    $rsi: i64 += 48: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 48]: i64
; CHECK-NEXT:    [$rbp + -112]: i64 = $rax: i64
; CHECK-NEXT:    $r8: i64 = $rdi: i64
; CHECK-NEXT:    $r8: i64 += 64: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 64]: i64
; CHECK-NEXT:    [$rbp + -104]: i64 = $rax: i64
; CHECK-NEXT:    $r9: i64 = $rdi: i64
; CHECK-NEXT:    $r9: i64 += 80: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 80]: i64
; CHECK-NEXT:    [$rbp + -96]: i64 = $rax: i64
; CHECK-NEXT:    $r10: i64 = $rdi: i64
; CHECK-NEXT:    $r10: i64 += 96: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 96]: i64
; CHECK-NEXT:    [$rbp + -88]: i64 = $rax: i64
; CHECK-NEXT:    $r11: i64 = $rdi: i64
; CHECK-NEXT:    $r11: i64 += 112: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 112]: i64
; CHECK-NEXT:    [$rbp + -80]: i64 = $rax: i64
; CHECK-NEXT:    $rbx: i64 = $rdi: i64
; CHECK-NEXT:    $rbx: i64 += 128: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 128]: i64
; CHECK-NEXT:    [$rbp + -72]: i64 = $rax: i64
; CHECK-NEXT:    $r12: i64 = $rdi: i64
; CHECK-NEXT:    $r12: i64 += 144: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 144]: i64
; CHECK-NEXT:    [$rbp + -64]: i64 = $rax: i64
; CHECK-NEXT:    $r13: i64 = $rdi: i64
; CHECK-NEXT:    $r13: i64 += 160: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 160]: i64
; CHECK-NEXT:    [$rbp + -56]: i64 = $rax: i64
; CHECK-NEXT:    $r14: i64 = $rdi: i64
; CHECK-NEXT:    $r14: i64 += 176: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 176]: i64
; CHECK-NEXT:    [$rbp + -48]: i64 = $rax: i64
; CHECK-NEXT:    $r15: i64 = $rdi: i64
; CHECK-NEXT:    $r15: i64 += 192: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 192]: i64
; CHECK-NEXT:    [$rbp + -40]: i64 = $rax: i64
; CHECK-NEXT:    [$rbp + -160]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -160]: i64 += 208: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 208]: i64
; CHECK-NEXT:    [$rbp + -32]: i64 = $rax: i64
; CHECK-NEXT:    [$rbp + -152]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -152]: i64 += 224: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 224]: i64
; CHECK-NEXT:    [$rbp + -24]: i64 = $rax: i64
; CHECK-NEXT:    [$rbp + -144]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -144]: i64 += 240: i64
; CHECK-NEXT:    $rax: i64 = [$rdi + 240]: i64
; CHECK-NEXT:    [$rbp + -16]: i64 = $rax: i64
; CHECK-NEXT:    $rax: i64 = [$rdi]: i64
; CHECK-NEXT:    $rax: i64 += [$rcx]: i64
; CHECK-NEXT:    $rax: i64 += [$rdx]: i64
; CHECK-NEXT:    $rax: i64 += [$rsi]: i64
; CHECK-NEXT:    $rax: i64 += [$r8]: i64
; CHECK-NEXT:    $rax: i64 += [$r9]: i64
; CHECK-NEXT:    $rax: i64 += [$r10]: i64
; CHECK-NEXT:    $rax: i64 += [$r11]: i64
; CHECK-NEXT:    $rax: i64 += [$rbx]: i64
; CHECK-NEXT:    $rax: i64 += [$r12]: i64
; CHECK-NEXT:    $rax: i64 += [$r13]: i64
; CHECK-NEXT:    $rax: i64 += [$r14]: i64
; CHECK-NEXT:    $rax: i64 += [$r15]: i64
; CHECK-NEXT:    $rcx: i64 = [$rbp + -160]: i64
; CHECK-NEXT:    $rax: i64 += [$rcx]: i64
; CHECK-NEXT:    $rcx: i64 = [$rbp + -152]: i64
; CHECK-NEXT:    $rax: i64 += [$rcx]: i64
; CHECK-NEXT:    $rcx: i64 = [$rbp + -144]: i64
; CHECK-NEXT:    $rax: i64 += [$rcx]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -136]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -128]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -120]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -112]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -104]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -96]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -88]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -80]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -72]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -64]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -56]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -48]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -40]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -32]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -24]: i64
; CHECK-NEXT:    $rax: i64 ^= [$rbp + -16]: i64
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($r15: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 160: i64
; CHECK-NEXT:    ret($rax: i64, )
entry:
  %g0 = getelementptr inbounds i64, ptr %p, i64 0
  %v0 = load i64, ptr %g0
  %g1 = getelementptr inbounds i64, ptr %p, i64 2
  %v1 = load i64, ptr %g1
  %g2 = getelementptr inbounds i64, ptr %p, i64 4
  %v2 = load i64, ptr %g2
  %g3 = getelementptr inbounds i64, ptr %p, i64 6
  %v3 = load i64, ptr %g3
  %g4 = getelementptr inbounds i64, ptr %p, i64 8
  %v4 = load i64, ptr %g4
  %g5 = getelementptr inbounds i64, ptr %p, i64 10
  %v5 = load i64, ptr %g5
  %g6 = getelementptr inbounds i64, ptr %p, i64 12
  %v6 = load i64, ptr %g6
  %g7 = getelementptr inbounds i64, ptr %p, i64 14
  %v7 = load i64, ptr %g7
  %g8 = getelementptr inbounds i64, ptr %p, i64 16
  %v8 = load i64, ptr %g8
  %g9 = getelementptr inbounds i64, ptr %p, i64 18
  %v9 = load i64, ptr %g9
  %g10 = getelementptr inbounds i64, ptr %p, i64 20
  %v10 = load i64, ptr %g10
  %g11 = getelementptr inbounds i64, ptr %p, i64 22
  %v11 = load i64, ptr %g11
  %g12 = getelementptr inbounds i64, ptr %p, i64 24
  %v12 = load i64, ptr %g12
  %g13 = getelementptr inbounds i64, ptr %p, i64 26
  %v13 = load i64, ptr %g13
  %g14 = getelementptr inbounds i64, ptr %p, i64 28
  %v14 = load i64, ptr %g14
  %g15 = getelementptr inbounds i64, ptr %p, i64 30
  %v15 = load i64, ptr %g15
  %s1 = add i64 %v0, %v1
  %s2 = add i64 %s1, %v2
  %s3 = add i64 %s2, %v3
  %s4 = add i64 %s3, %v4
  %s5 = add i64 %s4, %v5
  %s6 = add i64 %s5, %v6
  %s7 = add i64 %s6, %v7
  %s8 = add i64 %s7, %v8
  %s9 = add i64 %s8, %v9
  %s10 = add i64 %s9, %v10
  %s11 = add i64 %s10, %v11
  %s12 = add i64 %s11, %v12
  %s13 = add i64 %s12, %v13
  %s14 = add i64 %s13, %v14
  %s15 = add i64 %s14, %v15
  %m0 = xor i64 %s15, %v0
  %m1 = xor i64 %m0, %v1
  %m2 = xor i64 %m1, %v2
  %m3 = xor i64 %m2, %v3
  %m4 = xor i64 %m3, %v4
  %m5 = xor i64 %m4, %v5
  %m6 = xor i64 %m5, %v6
  %m7 = xor i64 %m6, %v7
  %m8 = xor i64 %m7, %v8
  %m9 = xor i64 %m8, %v9
  %m10 = xor i64 %m9, %v10
  %m11 = xor i64 %m10, %v11
  %m12 = xor i64 %m11, %v12
  %m13 = xor i64 %m12, %v13
  %m14 = xor i64 %m13, %v14
  %m15 = xor i64 %m14, %v15
  ret i64 %m15
}
