; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Regression test for register allocator spilling of <4 x float>.
; All values are live at the same time so some of them have to be spilled,
; the stack slots have to match the size of the type (16 bytes).
; RUN: %foffcc %s --print-mir | FileCheck %s

define <4 x float> @spill_v4f32(ptr %p) {
; CHECK: func spill_v4f32 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 48: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $xmm3: f32x4 = [$rdi]: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = [$rdi + 32]: f32x4
; CHECK-NEXT:    $xmm4: f32x4 = [$rdi + 64]: f32x4
; CHECK-NEXT:    $xmm5: f32x4 = [$rdi + 96]: f32x4
; CHECK-NEXT:    $xmm6: f32x4 = [$rdi + 128]: f32x4
; CHECK-NEXT:    $xmm7: f32x4 = [$rdi + 160]: f32x4
; CHECK-NEXT:    $xmm9: f32x4 = [$rdi + 192]: f32x4
; CHECK-NEXT:    $xmm10: f32x4 = [$rdi + 224]: f32x4
; CHECK-NEXT:    $xmm12: f32x4 = [$rdi + 256]: f32x4
; CHECK-NEXT:    $xmm13: f32x4 = [$rdi + 288]: f32x4
; CHECK-NEXT:    $xmm14: f32x4 = [$rdi + 320]: f32x4
; CHECK-NEXT:    $xmm15: f32x4 = [$rdi + 352]: f32x4
; CHECK-NEXT:    $r14: i64 = $rdi: i64
; CHECK-NEXT:    $r14: i64 += 384: i64
; CHECK-NEXT:    $r13: i64 = $rdi: i64
; CHECK-NEXT:    $r13: i64 += 416: i64
; CHECK-NEXT:    $r12: i64 = $rdi: i64
; CHECK-NEXT:    $r12: i64 += 448: i64
; CHECK-NEXT:    $r11: i64 = $rdi: i64
; CHECK-NEXT:    $r11: i64 += 480: i64
; CHECK-NEXT:    $r10: i64 = $rdi: i64
; CHECK-NEXT:    $r10: i64 += 512: i64
; CHECK-NEXT:    $r9: i64 = $rdi: i64
; CHECK-NEXT:    $r9: i64 += 544: i64
; CHECK-NEXT:    $r8: i64 = $rdi: i64
; CHECK-NEXT:    $r8: i64 += 576: i64
; CHECK-NEXT:    $rsi: i64 = $rdi: i64
; CHECK-NEXT:    $rsi: i64 += 608: i64
; CHECK-NEXT:    $rdx: i64 = $rdi: i64
; CHECK-NEXT:    $rdx: i64 += 640: i64
; CHECK-NEXT:    $rcx: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 += 672: i64
; CHECK-NEXT:    $rbx: i64 = $rdi: i64
; CHECK-NEXT:    $rbx: i64 += 704: i64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 736: i64
; CHECK-NEXT:    $xmm1: f32x4 = [$rdi + 736]: f32x4
; CHECK-NEXT:    $xmm2: f32x4 = $xmm3: f32x4 * [$rax]: f32x4
; CHECK-NEXT:    [$rbp + -16]: f64x2 = $xmm2: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 * [$rbx]: f32x4
; CHECK-NEXT:    [$rbp + -32]: f64x2 = $xmm0: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm3: f32x4 * $xmm1: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + [$rbp + -32]: f64x2
; CHECK-NEXT:    $xmm1: f32x4 = $xmm4: f32x4 * [$rcx]: f32x4
; CHECK-NEXT:    [$rbp + -48]: f64x2 = $xmm1: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + [$rbp + -48]: f64x2
; CHECK-NEXT:    $xmm11: f32x4 = $xmm5: f32x4 * [$rdx]: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm11: f32x4
; CHECK-NEXT:    $xmm8: f32x4 = $xmm6: f32x4 * [$rsi]: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm8: f32x4
; CHECK-NEXT:    $xmm2: f32x4 = $xmm7: f32x4 * [$r8]: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm2: f32x4
; CHECK-NEXT:    $xmm1: f32x4 = $xmm9: f32x4 * [$r9]: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm1: f32x4
; CHECK-NEXT:    $xmm7: f32x4 = $xmm10: f32x4 * [$r10]: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm7: f32x4
; CHECK-NEXT:    $xmm6: f32x4 = $xmm12: f32x4 * [$r11]: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm6: f32x4
; CHECK-NEXT:    $xmm5: f32x4 = $xmm13: f32x4 * [$r12]: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm5: f32x4
; CHECK-NEXT:    $xmm4: f32x4 = $xmm14: f32x4 * [$r13]: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm4: f32x4
; CHECK-NEXT:    $xmm3: f32x4 = $xmm15: f32x4 * [$r14]: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm3: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm3: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm4: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm5: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm6: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm7: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm1: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm2: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm8: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + $xmm11: f32x4
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + [$rbp + -48]: f64x2
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + [$rbp + -32]: f64x2
; CHECK-NEXT:    $xmm0: f32x4 = $xmm0: f32x4 + [$rbp + -16]: f64x2
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 48: i64
; CHECK-NEXT:    ret($xmm0: f32x4, )
entry:
  %g0 = getelementptr inbounds <4 x float>, ptr %p, i64 0
  %v0 = load <4 x float>, ptr %g0
  %g1 = getelementptr inbounds <4 x float>, ptr %p, i64 2
  %v1 = load <4 x float>, ptr %g1
  %g2 = getelementptr inbounds <4 x float>, ptr %p, i64 4
  %v2 = load <4 x float>, ptr %g2
  %g3 = getelementptr inbounds <4 x float>, ptr %p, i64 6
  %v3 = load <4 x float>, ptr %g3
  %g4 = getelementptr inbounds <4 x float>, ptr %p, i64 8
  %v4 = load <4 x float>, ptr %g4
  %g5 = getelementptr inbounds <4 x float>, ptr %p, i64 10
  %v5 = load <4 x float>, ptr %g5
  %g6 = getelementptr inbounds <4 x float>, ptr %p, i64 12
  %v6 = load <4 x float>, ptr %g6
  %g7 = getelementptr inbounds <4 x float>, ptr %p, i64 14
  %v7 = load <4 x float>, ptr %g7
  %g8 = getelementptr inbounds <4 x float>, ptr %p, i64 16
  %v8 = load <4 x float>, ptr %g8
  %g9 = getelementptr inbounds <4 x float>, ptr %p, i64 18
  %v9 = load <4 x float>, ptr %g9
  %g10 = getelementptr inbounds <4 x float>, ptr %p, i64 20
  %v10 = load <4 x float>, ptr %g10
  %g11 = getelementptr inbounds <4 x float>, ptr %p, i64 22
  %v11 = load <4 x float>, ptr %g11
  %g12 = getelementptr inbounds <4 x float>, ptr %p, i64 24
  %v12 = load <4 x float>, ptr %g12
  %g13 = getelementptr inbounds <4 x float>, ptr %p, i64 26
  %v13 = load <4 x float>, ptr %g13
  %g14 = getelementptr inbounds <4 x float>, ptr %p, i64 28
  %v14 = load <4 x float>, ptr %g14
  %g15 = getelementptr inbounds <4 x float>, ptr %p, i64 30
  %v15 = load <4 x float>, ptr %g15
  %g16 = getelementptr inbounds <4 x float>, ptr %p, i64 32
  %v16 = load <4 x float>, ptr %g16
  %g17 = getelementptr inbounds <4 x float>, ptr %p, i64 34
  %v17 = load <4 x float>, ptr %g17
  %g18 = getelementptr inbounds <4 x float>, ptr %p, i64 36
  %v18 = load <4 x float>, ptr %g18
  %g19 = getelementptr inbounds <4 x float>, ptr %p, i64 38
  %v19 = load <4 x float>, ptr %g19
  %g20 = getelementptr inbounds <4 x float>, ptr %p, i64 40
  %v20 = load <4 x float>, ptr %g20
  %g21 = getelementptr inbounds <4 x float>, ptr %p, i64 42
  %v21 = load <4 x float>, ptr %g21
  %g22 = getelementptr inbounds <4 x float>, ptr %p, i64 44
  %v22 = load <4 x float>, ptr %g22
  %g23 = getelementptr inbounds <4 x float>, ptr %p, i64 46
  %v23 = load <4 x float>, ptr %g23
  %m0 = fmul <4 x float> %v0, %v23
  %m1 = fmul <4 x float> %v1, %v22
  %s1 = fadd <4 x float> %m0, %m1
  %m2 = fmul <4 x float> %v2, %v21
  %s2 = fadd <4 x float> %s1, %m2
  %m3 = fmul <4 x float> %v3, %v20
  %s3 = fadd <4 x float> %s2, %m3
  %m4 = fmul <4 x float> %v4, %v19
  %s4 = fadd <4 x float> %s3, %m4
  %m5 = fmul <4 x float> %v5, %v18
  %s5 = fadd <4 x float> %s4, %m5
  %m6 = fmul <4 x float> %v6, %v17
  %s6 = fadd <4 x float> %s5, %m6
  %m7 = fmul <4 x float> %v7, %v16
  %s7 = fadd <4 x float> %s6, %m7
  %m8 = fmul <4 x float> %v8, %v15
  %s8 = fadd <4 x float> %s7, %m8
  %m9 = fmul <4 x float> %v9, %v14
  %s9 = fadd <4 x float> %s8, %m9
  %m10 = fmul <4 x float> %v10, %v13
  %s10 = fadd <4 x float> %s9, %m10
  %m11 = fmul <4 x float> %v11, %v12
  %s11 = fadd <4 x float> %s10, %m11
  %m12 = fmul <4 x float> %v12, %v11
  %s12 = fadd <4 x float> %s11, %m12
  %m13 = fmul <4 x float> %v13, %v10
  %s13 = fadd <4 x float> %s12, %m13
  %m14 = fmul <4 x float> %v14, %v9
  %s14 = fadd <4 x float> %s13, %m14
  %m15 = fmul <4 x float> %v15, %v8
  %s15 = fadd <4 x float> %s14, %m15
  %m16 = fmul <4 x float> %v16, %v7
  %s16 = fadd <4 x float> %s15, %m16
  %m17 = fmul <4 x float> %v17, %v6
  %s17 = fadd <4 x float> %s16, %m17
  %m18 = fmul <4 x float> %v18, %v5
  %s18 = fadd <4 x float> %s17, %m18
  %m19 = fmul <4 x float> %v19, %v4
  %s19 = fadd <4 x float> %s18, %m19
  %m20 = fmul <4 x float> %v20, %v3
  %s20 = fadd <4 x float> %s19, %m20
  %m21 = fmul <4 x float> %v21, %v2
  %s21 = fadd <4 x float> %s20, %m21
  %m22 = fmul <4 x float> %v22, %v1
  %s22 = fadd <4 x float> %s21, %m22
  %m23 = fmul <4 x float> %v23, %v0
  %s23 = fadd <4 x float> %s22, %m23
  ret <4 x float> %s23
}
