; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Regression test for register allocator spilling of i16.
; All values are live at the same time so some of them have to be spilled,
; the stack slots have to match the size of the type (2 bytes).
; RUN: %foffcc %s --print-mir | FileCheck %s

define i16 @spill_i16(ptr %p) {
; CHECK: func spill_i16 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 64: i64
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r15: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $ax: i32 = [$rdi]: i16
; CHECK-NEXT:    [$rbp + -40]: i16 = $ax: i16
; CHECK-NEXT:    $rbx: i64 = $rdi: i64
; CHECK-NEXT:    $rbx: i64 += 4: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 4]: i16
; CHECK-NEXT:    [$rbp + -38]: i16 = $ax: i16
; CHECK-NEXT:    $rcx: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 += 8: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 8]: i16
; CHECK-NEXT:    [$rbp + -36]: i16 = $ax: i16
; CHECK-NEXT:    $rdx: i64 = $rdi: i64
; CHECK-NEXT:    $rdx: i64 += 12: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 12]: i16
; CHECK-NEXT:    [$rbp + -34]: i16 = $ax: i16
; CHECK-NEXT:    $rsi: i64 = $rdi: i64
; CHECK-NEXT:    $rsi: i64 += 16: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 16]: i16
; CHECK-NEXT:    [$rbp + -32]: i16 = $ax: i16
; CHECK-NEXT:    $r8: i64 = $rdi: i64
; CHECK-NEXT:    $r8: i64 += 20: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 20]: i16
; CHECK-NEXT:    [$rbp + -30]: i16 = $ax: i16
; CHECK-NEXT:    $r9: i64 = $rdi: i64
; CHECK-NEXT:    $r9: i64 += 24: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 24]: i16
; CHECK-NEXT:    [$rbp + -28]: i16 = $ax: i16
; CHECK-NEXT:    $r10: i64 = $rdi: i64
; CHECK-NEXT:    $r10: i64 += 28: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 28]: i16
; CHECK-NEXT:    [$rbp + -26]: i16 = $ax: i16
; CHECK-NEXT:    $r11: i64 = $rdi: i64
; CHECK-NEXT:    $r11: i64 += 32: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 32]: i16
; CHECK-NEXT:    [$rbp + -24]: i16 = $ax: i16
; CHECK-NEXT:    $r12: i64 = $rdi: i64
; CHECK-NEXT:    $r12: i64 += 36: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 36]: i16
; CHECK-NEXT:    [$rbp + -22]: i16 = $ax: i16
; CHECK-NEXT:    $r13: i64 = $rdi: i64
; CHECK-NEXT:    $r13: i64 += 40: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 40]: i16
; CHECK-NEXT:    [$rbp + -20]: i16 = $ax: i16
; CHECK-NEXT:    $r14: i64 = $rdi: i64
; CHECK-NEXT:    $r14: i64 += 44: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 44]: i16
; CHECK-NEXT:    [$rbp + -18]: i16 = $ax: i16
; CHECK-NEXT:    $r15: i64 = $rdi: i64
; CHECK-NEXT:    $r15: i64 += 48: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 48]: i16
; CHECK-NEXT:    [$rbp + -16]: i16 = $ax: i16
; CHECK-NEXT:    [$rbp + -64]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -64]: i64 += 52: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 52]: i16
; CHECK-NEXT:    [$rbp + -14]: i16 = $ax: i16
; CHECK-NEXT:    [$rbp + -56]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -56]: i64 += 56: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 56]: i16
; CHECK-NEXT:    [$rbp + -12]: i16 = $ax: i16
; CHECK-NEXT:    [$rbp + -48]: i64 = $rdi: i64
; CHECK-NEXT:    [$rbp + -48]: i64 += 60: i64
; CHECK-NEXT:    $ax: i32 = [$rdi + 60]: i16
; CHECK-NEXT:    [$rbp + -10]: i16 = $ax: i16
; CHECK-NEXT:    $ax: i32 = [$rdi]: i16
; CHECK-NEXT:    $ax: i16 += [$rbx]: i16
; CHECK-NEXT:    $ax: i16 += [$rcx]: i16
; CHECK-NEXT:    $ax: i16 += [$rdx]: i16
; CHECK-NEXT:    $ax: i16 += [$rsi]: i16
; CHECK-NEXT:    $ax: i16 += [$r8]: i16
; CHECK-NEXT:    $ax: i16 += [$r9]: i16
; CHECK-NEXT:    $ax: i16 += [$r10]: i16
; CHECK-NEXT:    $ax: i16 += [$r11]: i16
; CHECK-NEXT:    $ax: i16 += [$r12]: i16
; CHECK-NEXT:    $ax: i16 += [$r13]: i16
; CHECK-NEXT:    $ax: i16 += [$r14]: i16
; CHECK-NEXT:    $ax: i16 += [$r15]: i16
; CHECK-NEXT:    $rbx: i64 = [$rbp + -64]: i64
; CHECK-NEXT:    $ax: i16 += [$rbx]: i16
; CHECK-NEXT:    $rbx: i64 = [$rbp + -56]: i64
; CHECK-NEXT:    $ax: i16 += [$rbx]: i16
; CHECK-NEXT:    $rbx: i64 = [$rbp + -48]: i64
; CHECK-NEXT:    $ax: i16 += [$rbx]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -40]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -38]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -36]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -34]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -32]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -30]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -28]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -26]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -24]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -22]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -20]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -18]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -16]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -14]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -12]: i16
; CHECK-NEXT:    $ax: i16 ^= [$rbp + -10]: i16
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($r15: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 64: i64
; CHECK-NEXT:    ret($ax: i16, )
entry:
  %g0 = getelementptr inbounds i16, ptr %p, i64 0
  %v0 = load i16, ptr %g0
  %g1 = getelementptr inbounds i16, ptr %p, i64 2
  %v1 = load i16, ptr %g1
  %g2 = getelementptr inbounds i16, ptr %p, i64 4
  %v2 = load i16, ptr %g2
  %g3 = getelementptr inbounds i16, ptr %p, i64 6
  %v3 = load i16, ptr %g3
  %g4 = getelementptr inbounds i16, ptr %p, i64 8
  %v4 = load i16, ptr %g4
  %g5 = getelementptr inbounds i16, ptr %p, i64 10
  %v5 = load i16, ptr %g5
  %g6 = getelementptr inbounds i16, ptr %p, i64 12
  %v6 = load i16, ptr %g6
  %g7 = getelementptr inbounds i16, ptr %p, i64 14
  %v7 = load i16, ptr %g7
  %g8 = getelementptr inbounds i16, ptr %p, i64 16
  %v8 = load i16, ptr %g8
  %g9 = getelementptr inbounds i16, ptr %p, i64 18
  %v9 = load i16, ptr %g9
  %g10 = getelementptr inbounds i16, ptr %p, i64 20
  %v10 = load i16, ptr %g10
  %g11 = getelementptr inbounds i16, ptr %p, i64 22
  %v11 = load i16, ptr %g11
  %g12 = getelementptr inbounds i16, ptr %p, i64 24
  %v12 = load i16, ptr %g12
  %g13 = getelementptr inbounds i16, ptr %p, i64 26
  %v13 = load i16, ptr %g13
  %g14 = getelementptr inbounds i16, ptr %p, i64 28
  %v14 = load i16, ptr %g14
  %g15 = getelementptr inbounds i16, ptr %p, i64 30
  %v15 = load i16, ptr %g15
  %s1 = add i16 %v0, %v1
  %s2 = add i16 %s1, %v2
  %s3 = add i16 %s2, %v3
  %s4 = add i16 %s3, %v4
  %s5 = add i16 %s4, %v5
  %s6 = add i16 %s5, %v6
  %s7 = add i16 %s6, %v7
  %s8 = add i16 %s7, %v8
  %s9 = add i16 %s8, %v9
  %s10 = add i16 %s9, %v10
  %s11 = add i16 %s10, %v11
  %s12 = add i16 %s11, %v12
  %s13 = add i16 %s12, %v13
  %s14 = add i16 %s13, %v14
  %s15 = add i16 %s14, %v15
  %m0 = xor i16 %s15, %v0
  %m1 = xor i16 %m0, %v1
  %m2 = xor i16 %m1, %v2
  %m3 = xor i16 %m2, %v3
  %m4 = xor i16 %m3, %v4
  %m5 = xor i16 %m4, %v5
  %m6 = xor i16 %m5, %v6
  %m7 = xor i16 %m6, %v7
  %m8 = xor i16 %m7, %v8
  %m9 = xor i16 %m8, %v9
  %m10 = xor i16 %m9, %v10
  %m11 = xor i16 %m10, %v11
  %m12 = xor i16 %m11, %v12
  %m13 = xor i16 %m12, %v13
  %m14 = xor i16 %m13, %v14
  %m15 = xor i16 %m14, %v15
  ret i16 %m15
}
