; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Regression test for register allocator spilling of <4 x double>.
; All values are live at the same time so some of them have to be spilled,
; the stack slots have to match the size of the type (32 bytes).
; RUN: %foffcc %s --print-mir | FileCheck %s

define <4 x double> @spill_v4f64(ptr %p) {
; CHECK: func spill_v4f64 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 96: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $ymm3: f64x4 = [$rdi]: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = [$rdi + 64]: f64x4
; CHECK-NEXT:    $ymm4: f64x4 = [$rdi + 128]: f64x4
; CHECK-NEXT:    $ymm5: f64x4 = [$rdi + 192]: f64x4
; CHECK-NEXT:    $ymm6: f64x4 = [$rdi + 256]: f64x4
; CHECK-NEXT:    $ymm7: f64x4 = [$rdi + 320]: f64x4
; CHECK-NEXT:    $ymm9: f64x4 = [$rdi + 384]: f64x4
; CHECK-NEXT:    $ymm10: f64x4 = [$rdi + 448]: f64x4
; CHECK-NEXT:    $ymm12: f64x4 = [$rdi + 512]: f64x4
; CHECK-NEXT:    $ymm13: f64x4 = [$rdi + 576]: f64x4
; CHECK-NEXT:    $ymm14: f64x4 = [$rdi + 640]: f64x4
; CHECK-NEXT:    $ymm15: f64x4 = [$rdi + 704]: f64x4
; CHECK-NEXT:    $r14: i64 = $rdi: i64
; CHECK-NEXT:    $r14: i64 += 768: i64
; CHECK-NEXT:    $r13: i64 = $rdi: i64
; CHECK-NEXT:    $r13: i64 += 832: i64
; CHECK-NEXT:    $r12: i64 = $rdi: i64
; CHECK-NEXT:    $r12: i64 += 896: i64
; CHECK-NEXT:    $r11: i64 = $rdi: i64
; CHECK-NEXT:    $r11: i64 += 960: i64
; CHECK-NEXT:    $r10: i64 = $rdi: i64
; CHECK-NEXT:    $r10: i64 += 1024: i64
; CHECK-NEXT:    $r9: i64 = $rdi: i64
; CHECK-NEXT:    $r9: i64 += 1088: i64
; CHECK-NEXT:    $r8: i64 = $rdi: i64
; CHECK-NEXT:    $r8: i64 += 1152: i64
; CHECK-NEXT:    $rsi: i64 = $rdi: i64
; CHECK-NEXT:    $rsi: i64 += 1216: i64
; CHECK-NEXT:    $rdx: i64 = $rdi: i64
; CHECK-NEXT:    $rdx: i64 += 1280: i64
; CHECK-NEXT:    $rcx: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 += 1344: i64
; CHECK-NEXT:    $rbx: i64 = $rdi: i64
; CHECK-NEXT:    $rbx: i64 += 1408: i64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 1472: i64
; CHECK-NEXT:    $ymm1: f64x4 = [$rdi + 1472]: f64x4
; CHECK-NEXT:    $ymm2: f64x4 = $ymm3: f64x4 * [$rax]: f64x4
; CHECK-NEXT:    [$rbp + -32]: f64x4 = $ymm2: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 * [$rbx]: f64x4
; CHECK-NEXT:    [$rbp + -64]: f64x4 = $ymm0: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm3: f64x4 * $ymm1: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + [$rbp + -64]: f64x4
; CHECK-NEXT:    $ymm1: f64x4 = $ymm4: f64x4 * [$rcx]: f64x4
; CHECK-NEXT:    [$rbp + -96]: f64x4 = $ymm1: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + [$rbp + -96]: f64x4
; CHECK-NEXT:    $ymm11: f64x4 = $ymm5: f64x4 * [$rdx]: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm11: f64x4
; CHECK-NEXT:    $ymm8: f64x4 = $ymm6: f64x4 * [$rsi]: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm8: f64x4
; CHECK-NEXT:    $ymm2: f64x4 = $ymm7: f64x4 * [$r8]: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm2: f64x4
; CHECK-NEXT:    $ymm1: f64x4 = $ymm9: f64x4 * [$r9]: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm1: f64x4
; CHECK-NEXT:    $ymm7: f64x4 = $ymm10: f64x4 * [$r10]: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm7: f64x4
; CHECK-NEXT:    $ymm6: f64x4 = $ymm12: f64x4 * [$r11]: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm6: f64x4
; CHECK-NEXT:    $ymm5: f64x4 = $ymm13: f64x4 * [$r12]: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm5: f64x4
; CHECK-NEXT:    $ymm4: f64x4 = $ymm14: f64x4 * [$r13]: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm4: f64x4
; CHECK-NEXT:    $ymm3: f64x4 = $ymm15: f64x4 * [$r14]: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm3: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm3: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm4: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm5: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm6: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm7: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm1: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm2: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm8: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + $ymm11: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + [$rbp + -96]: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + [$rbp + -64]: f64x4
; CHECK-NEXT:    $ymm0: f64x4 = $ymm0: f64x4 + [$rbp + -32]: f64x4
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 96: i64
; CHECK-NEXT:    ret($ymm0: f64x4, )
entry:
  %g0 = getelementptr inbounds <4 x double>, ptr %p, i64 0
  %v0 = load <4 x double>, ptr %g0
  %g1 = getelementptr inbounds <4 x double>, ptr %p, i64 2
  %v1 = load <4 x double>, ptr %g1
  %g2 = getelementptr inbounds <4 x double>, ptr %p, i64 4
  %v2 = load <4 x double>, ptr %g2
  %g3 = getelementptr inbounds <4 x double>, ptr %p, i64 6
  %v3 = load <4 x double>, ptr %g3
  %g4 = getelementptr inbounds <4 x double>, ptr %p, i64 8
  %v4 = load <4 x double>, ptr %g4
  %g5 = getelementptr inbounds <4 x double>, ptr %p, i64 10
  %v5 = load <4 x double>, ptr %g5
  %g6 = getelementptr inbounds <4 x double>, ptr %p, i64 12
  %v6 = load <4 x double>, ptr %g6
  %g7 = getelementptr inbounds <4 x double>, ptr %p, i64 14
  %v7 = load <4 x double>, ptr %g7
  %g8 = getelementptr inbounds <4 x double>, ptr %p, i64 16
  %v8 = load <4 x double>, ptr %g8
  %g9 = getelementptr inbounds <4 x double>, ptr %p, i64 18
  %v9 = load <4 x double>, ptr %g9
  %g10 = getelementptr inbounds <4 x double>, ptr %p, i64 20
  %v10 = load <4 x double>, ptr %g10
  %g11 = getelementptr inbounds <4 x double>, ptr %p, i64 22
  %v11 = load <4 x double>, ptr %g11
  %g12 = getelementptr inbounds <4 x double>, ptr %p, i64 24
  %v12 = load <4 x double>, ptr %g12
  %g13 = getelementptr inbounds <4 x double>, ptr %p, i64 26
  %v13 = load <4 x double>, ptr %g13
  %g14 = getelementptr inbounds <4 x double>, ptr %p, i64 28
  %v14 = load <4 x double>, ptr %g14
  %g15 = getelementptr inbounds <4 x double>, ptr %p, i64 30
  %v15 = load <4 x double>, ptr %g15
  %g16 = getelementptr inbounds <4 x double>, ptr %p, i64 32
  %v16 = load <4 x double>, ptr %g16
  %g17 = getelementptr inbounds <4 x double>, ptr %p, i64 34
  %v17 = load <4 x double>, ptr %g17
  %g18 = getelementptr inbounds <4 x double>, ptr %p, i64 36
  %v18 = load <4 x double>, ptr %g18
  %g19 = getelementptr inbounds <4 x double>, ptr %p, i64 38
  %v19 = load <4 x double>, ptr %g19
  %g20 = getelementptr inbounds <4 x double>, ptr %p, i64 40
  %v20 = load <4 x double>, ptr %g20
  %g21 = getelementptr inbounds <4 x double>, ptr %p, i64 42
  %v21 = load <4 x double>, ptr %g21
  %g22 = getelementptr inbounds <4 x double>, ptr %p, i64 44
  %v22 = load <4 x double>, ptr %g22
  %g23 = getelementptr inbounds <4 x double>, ptr %p, i64 46
  %v23 = load <4 x double>, ptr %g23
  %m0 = fmul <4 x double> %v0, %v23
  %m1 = fmul <4 x double> %v1, %v22
  %s1 = fadd <4 x double> %m0, %m1
  %m2 = fmul <4 x double> %v2, %v21
  %s2 = fadd <4 x double> %s1, %m2
  %m3 = fmul <4 x double> %v3, %v20
  %s3 = fadd <4 x double> %s2, %m3
  %m4 = fmul <4 x double> %v4, %v19
  %s4 = fadd <4 x double> %s3, %m4
  %m5 = fmul <4 x double> %v5, %v18
  %s5 = fadd <4 x double> %s4, %m5
  %m6 = fmul <4 x double> %v6, %v17
  %s6 = fadd <4 x double> %s5, %m6
  %m7 = fmul <4 x double> %v7, %v16
  %s7 = fadd <4 x double> %s6, %m7
  %m8 = fmul <4 x double> %v8, %v15
  %s8 = fadd <4 x double> %s7, %m8
  %m9 = fmul <4 x double> %v9, %v14
  %s9 = fadd <4 x double> %s8, %m9
  %m10 = fmul <4 x double> %v10, %v13
  %s10 = fadd <4 x double> %s9, %m10
  %m11 = fmul <4 x double> %v11, %v12
  %s11 = fadd <4 x double> %s10, %m11
  %m12 = fmul <4 x double> %v12, %v11
  %s12 = fadd <4 x double> %s11, %m12
  %m13 = fmul <4 x double> %v13, %v10
  %s13 = fadd <4 x double> %s12, %m13
  %m14 = fmul <4 x double> %v14, %v9
  %s14 = fadd <4 x double> %s13, %m14
  %m15 = fmul <4 x double> %v15, %v8
  %s15 = fadd <4 x double> %s14, %m15
  %m16 = fmul <4 x double> %v16, %v7
  %s16 = fadd <4 x double> %s15, %m16
  %m17 = fmul <4 x double> %v17, %v6
  %s17 = fadd <4 x double> %s16, %m17
  %m18 = fmul <4 x double> %v18, %v5
  %s18 = fadd <4 x double> %s17, %m18
  %m19 = fmul <4 x double> %v19, %v4
  %s19 = fadd <4 x double> %s18, %m19
  %m20 = fmul <4 x double> %v20, %v3
  %s20 = fadd <4 x double> %s19, %m20
  %m21 = fmul <4 x double> %v21, %v2
  %s21 = fadd <4 x double> %s20, %m21
  %m22 = fmul <4 x double> %v22, %v1
  %s22 = fadd <4 x double> %s21, %m22
  %m23 = fmul <4 x double> %v23, %v0
  %s23 = fadd <4 x double> %s22, %m23
  ret <4 x double> %s23
}
