; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "InstSimplify" | FileCheck %s
; a constant on the left of a float compare moves to the right, ordering predicates flip

define i1 @olt(double %x) {
; CHECK-LABEL: func olt<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: f64):
; CHECK-NEXT:    %1: i1 = FloatOGT(%0, 0:f64){} NUses:1
; CHECK-NEXT:    %2: i1 = Return(%1){} NUses:0
; CHECK-NEXT:}
  %c = fcmp olt double 0.0, %x
  ret i1 %c
}

define i1 @uge(double %x) {
; CHECK-LABEL: func uge<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: f64):
; CHECK-NEXT:    %1: i1 = FloatULE(%0, 3FF8000000000000:f64){} NUses:1
; CHECK-NEXT:    %2: i1 = Return(%1){} NUses:0
; CHECK-NEXT:}
  %c = fcmp uge double 1.5, %x
  ret i1 %c
}

define i1 @one(double %x) {
; CHECK-LABEL: func one<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: f64):
; CHECK-NEXT:    %1: i1 = FloatONE(%0, 3FF8000000000000:f64){} NUses:1
; CHECK-NEXT:    %2: i1 = Return(%1){} NUses:0
; CHECK-NEXT:}
  %c = fcmp one double 1.5, %x
  ret i1 %c
}
