; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "Mem2Reg,InstSimplify,DCE" | FileCheck %s
; Regression test: icmp slt on two zero extended values compared the narrow
; values signed (wrong for values >= 0x8000), the predicate has to become
; unsigned. sext keeps the signed predicate.

define i1 @zext_lt(ptr %p, i16 %v) {
; CHECK-LABEL: func zext_lt<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: ptr, %1{}: i16):
; CHECK-NEXT:    %2: i16 = Load(%0){} NUses:1
; CHECK-NEXT:    %3: i1 = IntULT(%2, %1){} NUses:1
; CHECK-NEXT:    %4: i1 = Return(%3){} NUses:0
; CHECK-NEXT:}
  %a = load i16, ptr %p, align 2
  %za = zext i16 %a to i32
  %zv = zext i16 %v to i32
  %c = icmp slt i32 %za, %zv
  ret i1 %c
}

define i1 @sext_lt(ptr %p, i16 %v) {
; CHECK-LABEL: func sext_lt<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: ptr, %1{}: i16):
; CHECK-NEXT:    %2: i16 = Load(%0){} NUses:1
; CHECK-NEXT:    %3: i1 = IntSLT(%2, %1){} NUses:1
; CHECK-NEXT:    %4: i1 = Return(%3){} NUses:0
; CHECK-NEXT:}
  %a = load i16, ptr %p, align 2
  %za = sext i16 %a to i32
  %zv = sext i16 %v to i32
  %c = icmp slt i32 %za, %zv
  ret i1 %c
}
