; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "InstSimplify" | FileCheck %s

; (x udiv 8) * 8 is x & -8, an sdiv rounds towards zero so it must stay.

define i64 @udiv_mul(i64 %x) {
; CHECK-LABEL: func udiv_mul<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: i64):
; CHECK-NEXT:    %1: i64 = IntUDiv(%0, 8:i64){} NUses:0
; CHECK-NEXT:    %2: i64 = And(%0, -8:i64){} NUses:1
; CHECK-NEXT:    %3: i64 = Return(%2){} NUses:0
; CHECK-NEXT:}
  %d = udiv i64 %x, 8
  %m = mul i64 %d, 8
  ret i64 %m
}

define i64 @sdiv_mul(i64 %x) {
; CHECK-LABEL: func sdiv_mul<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: i64):
; CHECK-NEXT:    %1: i64 = IntSDiv(%0, 8:i64){} NUses:1
; CHECK-NEXT:    %2: i64 = IntMul(%1, 8:i64){} NUses:1
; CHECK-NEXT:    %3: i64 = Return(%2){} NUses:0
; CHECK-NEXT:}
  %d = sdiv i64 %x, 8
  %m = mul i64 %d, 8
  ret i64 %m
}
