; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "InstSimplify" | FileCheck %s

@g = constant [4 x i8] c"abcd"

; out of bounds load of a constant global must not be folded (or crash)
define i32 @oob() {
; CHECK-LABEL: func oob<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0():
; CHECK-NEXT:    %0: ptr = PtrAdd(G(g), 16:i64){NSW; NUW; } NUses:1
; CHECK-NEXT:    %1: i32 = Load(%0){} NUses:1
; CHECK-NEXT:    %2: i32 = Return(%1){} NUses:0
; CHECK-NEXT:}
  %p = getelementptr i8, ptr @g, i64 16
  %v = load i32, ptr %p
  ret i32 %v
}
