; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "LoopUnswitch" | FileCheck %s

; the loop invariant condition is unswitched even though %acc is used after the
; loop: both loop copies feed a merged block argument of the exit block
define i64 @unswitch_use_after(i64 %n, i1 %c) {
; CHECK-LABEL: func unswitch_use_after<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: i64, %1{}: i1):
; CHECK-NEXT:    %2: () = Branch<bb1(0:i64, 0:i64)>(){} NUses:0
; CHECK-NEXT:  bb2(%3{}: i64, %4{}: i64):
; CHECK-NEXT:    %5: i1 = IntSGE(%3, %0){} NUses:1
; CHECK-NEXT:    %6: () = CondBranch<bb3(%4), bb4()>(%5){} NUses:0
; CHECK-NEXT:  bb3(%7{}: i64):
; CHECK-NEXT:    %8: i64 = Return(%7){} NUses:0
; CHECK-NEXT:  bb4():
; CHECK-NEXT:    %9: () = Branch<bb5()>(){} NUses:0
; CHECK-NEXT:  bb5():
; CHECK-NEXT:    %10: i64 = IntAdd(%4, 3:i64){} NUses:1
; CHECK-NEXT:    %11: i64 = IntAdd(%10, 4:i64){} NUses:1
; CHECK-NEXT:    %12: i64 = IntAdd(%11, 5:i64){} NUses:1
; CHECK-NEXT:    %13: i64 = IntAdd(%12, 6:i64){} NUses:1
; CHECK-NEXT:    %14: i64 = IntAdd(%13, 7:i64){} NUses:1
; CHECK-NEXT:    %15: i64 = IntAdd(%14, 8:i64){} NUses:1
; CHECK-NEXT:    %16: i64 = IntAdd(%15, 9:i64){} NUses:1
; CHECK-NEXT:    %17: i64 = IntAdd(%16, 10:i64){} NUses:1
; CHECK-NEXT:    %18: i64 = IntAdd(%17, 11:i64){} NUses:1
; CHECK-NEXT:    %19: i64 = IntAdd(%18, 12:i64){} NUses:1
; CHECK-NEXT:    %20: i64 = IntAdd(%19, 13:i64){} NUses:1
; CHECK-NEXT:    %21: i64 = IntAdd(%20, 14:i64){} NUses:1
; CHECK-NEXT:    %22: i64 = IntAdd(%21, 15:i64){} NUses:1
; CHECK-NEXT:    %23: i64 = IntAdd(%22, 16:i64){} NUses:1
; CHECK-NEXT:    %24: () = Branch<bb6(%23)>(){} NUses:0
; CHECK-NEXT:  bb7():
; CHECK-NEXT:    %25: i64 = Xor(%4, 7:i64){} NUses:1
; CHECK-NEXT:    %26: i64 = Xor(%25, 8:i64){} NUses:1
; CHECK-NEXT:    %27: i64 = Xor(%26, 9:i64){} NUses:1
; CHECK-NEXT:    %28: i64 = Xor(%27, 10:i64){} NUses:1
; CHECK-NEXT:    %29: i64 = Xor(%28, 11:i64){} NUses:1
; CHECK-NEXT:    %30: i64 = Xor(%29, 12:i64){} NUses:1
; CHECK-NEXT:    %31: i64 = Xor(%30, 13:i64){} NUses:1
; CHECK-NEXT:    %32: i64 = Xor(%31, 14:i64){} NUses:1
; CHECK-NEXT:    %33: i64 = Xor(%32, 15:i64){} NUses:1
; CHECK-NEXT:    %34: i64 = Xor(%33, 16:i64){} NUses:1
; CHECK-NEXT:    %35: i64 = Xor(%34, 17:i64){} NUses:1
; CHECK-NEXT:    %36: i64 = Xor(%35, 18:i64){} NUses:1
; CHECK-NEXT:    %37: i64 = Xor(%36, 19:i64){} NUses:1
; CHECK-NEXT:    %38: i64 = Xor(%37, 20:i64){} NUses:1
; CHECK-NEXT:    %39: () = Branch<bb6(%38)>(){} NUses:0
; CHECK-NEXT:  bb6(%40{}: i64):
; CHECK-NEXT:    %41: i64 = IntAdd(%3, 1:i64){} NUses:1
; CHECK-NEXT:    %42: () = Branch<bb2(%41, %40)>(){} NUses:0
; CHECK-NEXT:  bb8(%43{}: i64):
; CHECK-NEXT:    %44: i64 = IntAdd(%45, 1:i64){} NUses:1
; CHECK-NEXT:    %46: () = Branch<bb9(%44, %43)>(){} NUses:0
; CHECK-NEXT:  bb10():
; CHECK-NEXT:    %47: i64 = IntAdd(%48, 3:i64){} NUses:1
; CHECK-NEXT:    %49: i64 = IntAdd(%47, 4:i64){} NUses:1
; CHECK-NEXT:    %50: i64 = IntAdd(%49, 5:i64){} NUses:1
; CHECK-NEXT:    %51: i64 = IntAdd(%50, 6:i64){} NUses:1
; CHECK-NEXT:    %52: i64 = IntAdd(%51, 7:i64){} NUses:1
; CHECK-NEXT:    %53: i64 = IntAdd(%52, 8:i64){} NUses:1
; CHECK-NEXT:    %54: i64 = IntAdd(%53, 9:i64){} NUses:1
; CHECK-NEXT:    %55: i64 = IntAdd(%54, 10:i64){} NUses:1
; CHECK-NEXT:    %56: i64 = IntAdd(%55, 11:i64){} NUses:1
; CHECK-NEXT:    %57: i64 = IntAdd(%56, 12:i64){} NUses:1
; CHECK-NEXT:    %58: i64 = IntAdd(%57, 13:i64){} NUses:1
; CHECK-NEXT:    %59: i64 = IntAdd(%58, 14:i64){} NUses:1
; CHECK-NEXT:    %60: i64 = IntAdd(%59, 15:i64){} NUses:1
; CHECK-NEXT:    %61: i64 = IntAdd(%60, 16:i64){} NUses:1
; CHECK-NEXT:    %62: () = Branch<bb8(%61)>(){} NUses:0
; CHECK-NEXT:  bb11():
; CHECK-NEXT:    %63: i64 = Xor(%48, 7:i64){} NUses:1
; CHECK-NEXT:    %64: i64 = Xor(%63, 8:i64){} NUses:1
; CHECK-NEXT:    %65: i64 = Xor(%64, 9:i64){} NUses:1
; CHECK-NEXT:    %66: i64 = Xor(%65, 10:i64){} NUses:1
; CHECK-NEXT:    %67: i64 = Xor(%66, 11:i64){} NUses:1
; CHECK-NEXT:    %68: i64 = Xor(%67, 12:i64){} NUses:1
; CHECK-NEXT:    %69: i64 = Xor(%68, 13:i64){} NUses:1
; CHECK-NEXT:    %70: i64 = Xor(%69, 14:i64){} NUses:1
; CHECK-NEXT:    %71: i64 = Xor(%70, 15:i64){} NUses:1
; CHECK-NEXT:    %72: i64 = Xor(%71, 16:i64){} NUses:1
; CHECK-NEXT:    %73: i64 = Xor(%72, 17:i64){} NUses:1
; CHECK-NEXT:    %74: i64 = Xor(%73, 18:i64){} NUses:1
; CHECK-NEXT:    %75: i64 = Xor(%74, 19:i64){} NUses:1
; CHECK-NEXT:    %76: i64 = Xor(%75, 20:i64){} NUses:1
; CHECK-NEXT:    %77: () = Branch<bb8(%76)>(){} NUses:0
; CHECK-NEXT:  bb12():
; CHECK-NEXT:    %78: () = Branch<bb11()>(){} NUses:0
; CHECK-NEXT:  bb9(%45{}: i64, %48{}: i64):
; CHECK-NEXT:    %79: i1 = IntSGE(%45, %0){} NUses:1
; CHECK-NEXT:    %80: () = CondBranch<bb3(%48), bb12()>(%79){} NUses:0
; CHECK-NEXT:  bb1(%81{}: i64, %82{}: i64):
; CHECK-NEXT:    %83: () = CondBranch<bb2(%81, %82), bb9(%81, %82)>(%1){} NUses:0
; CHECK-NEXT:}
entry:
  br label %head
head:
  %i = phi i64 [ 0, %entry ], [ %i.next, %latch ]
  %acc = phi i64 [ 0, %entry ], [ %acc.next, %latch ]
  %done = icmp sge i64 %i, %n
  br i1 %done, label %exit, label %body
body:
  br i1 %c, label %a, label %b
a:
  %a0 = add i64 %acc, 3
  %a1 = add i64 %a0, 4
  %a2 = add i64 %a1, 5
  %a3 = add i64 %a2, 6
  %a4 = add i64 %a3, 7
  %a5 = add i64 %a4, 8
  %a6 = add i64 %a5, 9
  %a7 = add i64 %a6, 10
  %a8 = add i64 %a7, 11
  %a9 = add i64 %a8, 12
  %a10 = add i64 %a9, 13
  %a11 = add i64 %a10, 14
  %a12 = add i64 %a11, 15
  %a13 = add i64 %a12, 16
  br label %latch
b:
  %b0 = xor i64 %acc, 7
  %b1 = xor i64 %b0, 8
  %b2 = xor i64 %b1, 9
  %b3 = xor i64 %b2, 10
  %b4 = xor i64 %b3, 11
  %b5 = xor i64 %b4, 12
  %b6 = xor i64 %b5, 13
  %b7 = xor i64 %b6, 14
  %b8 = xor i64 %b7, 15
  %b9 = xor i64 %b8, 16
  %b10 = xor i64 %b9, 17
  %b11 = xor i64 %b10, 18
  %b12 = xor i64 %b11, 19
  %b13 = xor i64 %b12, 20
  br label %latch
latch:
  %acc.next = phi i64 [ %a13, %a ], [ %b13, %b ]
  %i.next = add i64 %i, 1
  br label %head
exit:
  ret i64 %acc
}
