; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "LVN" | FileCheck %s

; Forwarding a scalar load out of a vector store must not drop the store:
; another load of the whole vector still reads it.
define <4 x i64> @f(ptr %p, ptr %a, <4 x i64> %v) {
; CHECK-LABEL: func f<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: ptr, %1{}: ptr, %2{}: 4@i64):
; CHECK-NEXT:    %3: 4@i64 = Store(%1, %2){} NUses:0
; CHECK-NEXT:    %4: ptr = ExtractValue(%2, 0:i32){} NUses:1
; CHECK-NEXT:    %5: ptr = Store(%0, %4){} NUses:0
; CHECK-NEXT:    %6: 4@i64 = Load(%1){} NUses:1
; CHECK-NEXT:    %7: 4@i64 = Return(%6){} NUses:0
; CHECK-NEXT:}
  store <4 x i64> %v, ptr %a, align 8
  %s = load ptr, ptr %a, align 8
  store ptr %s, ptr %p, align 8
  %w = load <4 x i64>, ptr %a, align 8
  ret <4 x i64> %w
}
