; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; An alloca that is loaded with a different size than it is stored with can't
; be turned into a value, mem2reg must leave it alone (used to abort with
; "wrong typein alloca?").
; RUN: %foffcc %s --print-fir --passes "Mem2Reg,DCE" | FileCheck %s

define i32 @partial_load(i64 %x) {
; CHECK-LABEL: func partial_load<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: i64):
; CHECK-NEXT:    %1: ptr = Alloca(8:i32){extTy: i64; } NUses:2
; CHECK-NEXT:    %2: i64 = Store(%1, %0){} NUses:0
; CHECK-NEXT:    %3: i32 = Load(%1){} NUses:1
; CHECK-NEXT:    %4: i32 = Return(%3){} NUses:0
; CHECK-NEXT:}
  %a = alloca i64, align 8
  store i64 %x, ptr %a, align 8
  %v = load i32, ptr %a, align 8
  ret i32 %v
}
