; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "Mem2Reg,DCE" | FileCheck %s
define i32 @f(i32 %x) {
; CHECK-LABEL: func f<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: i32):
; CHECK-NEXT:    %1: i32 = IntAdd(%0, 1:i32){} NUses:1
; CHECK-NEXT:    %2: i32 = Return(%1){} NUses:0
; CHECK-NEXT:}
  %a = alloca i32, align 4
  store i32 %x, ptr %a, align 4
  %v = load i32, ptr %a, align 4
  %r = add i32 %v, 1
  ret i32 %r
}
