; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "Mem2Reg" | FileCheck %s

; Both switch cases target the same block that needs a block argument, every
; edge has to receive it.

define i32 @f(i32 %x) {
; CHECK-LABEL: func f<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: i32):
; CHECK-NEXT:    %1: ptr = Alloca(4:i32){extTy: i32; } NUses:1
; CHECK-NEXT:    %2: () = Switch<bb1(%0), bb1(%0), bb2()>(0:i32, 1:i32, %0){} NUses:0
; CHECK-NEXT:  bb2():
; CHECK-NEXT:    %3: () = Branch<bb1(5:i32)>(){} NUses:0
; CHECK-NEXT:  bb1(%4{}: i32):
; CHECK-NEXT:    %5: i32 = Load(%1){} NUses:0
; CHECK-NEXT:    %6: i32 = Return(%4){} NUses:0
; CHECK-NEXT:}
entry:
  %a = alloca i32, align 4
  store i32 %x, ptr %a, align 4
  switch i32 %x, label %other [
    i32 0, label %out
    i32 1, label %out
  ]

other:
  store i32 5, ptr %a, align 4
  br label %out

out:
  %r = load i32, ptr %a, align 4
  ret i32 %r
}
