; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "InstSimplify,DCE" | FileCheck %s
define i64 @f(ptr %p, i64 %n) {
; CHECK-LABEL: func f<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: ptr, %1{}: i64):
; CHECK-NEXT:    %2: i64 = Return(%1){} NUses:0
; CHECK-NEXT:}
  %a = icmp eq ptr %p, %p
  %o = or i64 %n, %n
  %m = and i64 %o, %o
  %s = select i1 %a, i64 %m, i64 0
  ret i64 %s
}

define i1 @g(i64 %n) {
; CHECK-LABEL: func g<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: i64):
; CHECK-NEXT:    %1: i1 = Return(0:i8){} NUses:0
; CHECK-NEXT:}
  %c = icmp ult i64 %n, %n
  ret i1 %c
}
