; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "LLVMIntrinsicLowering,SCCP,DCE" | FileCheck %s
; ctlz/cttz fold with the bit width of the operand, not 128.

define i32 @lz() {
; CHECK-LABEL: func lz<CC: C, LINK: external, > Uses: 0
; CHECK:       bb0():
; CHECK-NEXT:    %0: i32 = Return(28:i32){} NUses:0
  %r = call i32 @llvm.ctlz.i32(i32 10, i1 false)
  ret i32 %r
}
define i32 @lz0() {
; CHECK-LABEL: func lz0<CC: C, LINK: external, > Uses: 0
; CHECK:       bb0():
; CHECK-NEXT:    %0: i32 = Return(32:i32){} NUses:0
  %r = call i32 @llvm.ctlz.i32(i32 0, i1 false)
  ret i32 %r
}
declare i32 @llvm.ctlz.i32(i32, i1)
