; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "SCCP,DCE" | FileCheck %s
; SCCP must not abort on splat vector constants.

define <4 x i64> @splat(<4 x i64> %a, i1 %c) {
; CHECK-LABEL: func splat<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: 4@i64, %1{}: i1):
; CHECK-NEXT:    %2: 4@i64 = Select(%1, <0:i64, 0:i64, 0:i64, 0:i64, >:4@i64, %0){} NUses:1
; CHECK-NEXT:    %3: 4@i64 = Return(%2){} NUses:0
; CHECK-NEXT:}
  %r = select i1 %c, <4 x i64> zeroinitializer, <4 x i64> %a
  ret <4 x i64> %r
}
