; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "InstSimplify" | FileCheck %s
; Regression test: inttoptr(load i64 p) is turned into a `load ptr p`, that load
; must stay where the original load was. Emitting it at the cast read the
; memory after the store to the same address (post increment of an iterator
; returned the new instead of the old value).

define ptr @post_inc(ptr %it) {
; CHECK-LABEL: func post_inc<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: ptr):
; CHECK-NEXT:    %1: ptr = Load(%0){} NUses:1
; CHECK-NEXT:    %2: ptr = Load(%0){} NUses:1
; CHECK-NEXT:    %3: ptr = Load(%2){} NUses:1
; CHECK-NEXT:    %4: ptr = Store(%0, %3){} NUses:0
; CHECK-NEXT:    %5: ptr = Return(%1){} NUses:0
; CHECK-NEXT:}
  %old = load i64, ptr %it, align 8
  %next.p = inttoptr i64 %old to ptr
  %next = load ptr, ptr %next.p, align 8
  store ptr %next, ptr %it, align 8
  %ret = inttoptr i64 %old to ptr
  ret ptr %ret
}
