; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "SimplifyCFG" | FileCheck %s

; Unreachable cycle: the dead block's pred still targets it, removing it must not leave a dangling branch.
define i32 @f(i32 %x) {
; CHECK-LABEL: func f<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: i32):
; CHECK-NEXT:    %1: i32 = Return(%0){} NUses:0
; CHECK-NEXT:}
entry:
  ret i32 %x
dead1:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %dead2, label %out
dead2:
  br label %dead1
out:
  ret i32 1
}
