; NOTE: Assertions have been autogenerated by utils/update_fir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-fir --passes "DoubleLoadElim,DCE" | FileCheck %s
@g = global i32 0

; every volatile load stays, they are neither merged nor removed when unused
define i32 @f(i1 %c) {
; CHECK-LABEL: func f<CC: C, LINK: external, > Uses: 0
; CHECK-NEXT:{
; CHECK-NEXT:  bb0(%0{}: i1):
; CHECK-NEXT:    %1: i32 = Load(G(g)){VOLATILE; } NUses:2
; CHECK-NEXT:    %2: () = CondBranch<bb1(), bb2()>(%0){} NUses:0
; CHECK-NEXT:  bb1():
; CHECK-NEXT:    %3: i32 = Load(G(g)){VOLATILE; } NUses:1
; CHECK-NEXT:    %4: i32 = IntAdd(%1, %3){} NUses:1
; CHECK-NEXT:    %5: i32 = Return(%4){} NUses:0
; CHECK-NEXT:  bb2():
; CHECK-NEXT:    %6: i32 = Load(G(g)){VOLATILE; } NUses:0
; CHECK-NEXT:    %7: i32 = Return(%1){} NUses:0
; CHECK-NEXT:}
entry:
  %a = load volatile i32, ptr @g
  br i1 %c, label %t, label %e
t:
  %b = load volatile i32, ptr @g
  %s = add i32 %a, %b
  ret i32 %s
e:
  %d = load volatile i32, ptr @g
  ret i32 %a
}
