#include "matcher_patterns.hpp"
#include "ir/instruction_data.hpp"
#include "mir/func.hpp"
#include "mir/instr.hpp"
#include "mir/matcher_helpers.hpp"
#include "third_party/Zydis.h"
#include <bit>
#include <cstring>
#include <fmt/core.h>
#include <limits>

namespace foptim::fmir {

bool is_reg(fir::ValueR val) {
  if (val.is_constant()) {
    auto consti = val.as_constant();
    if (consti->is_int()) {
      return false;
    }
    if (consti->is_global()) {
      return true;
    }
    if (consti->is_func()) {
      return true;
    }
    fmt::println("{}", val);
    ASSERT(false);
    std::abort();
  } else {
    return true;
  }
}

void move_patterns(IRVec<Pattern> &pats) {
  using Node = Pattern::Node;
  using InstrType = fir::InstrType;
  using NodeType = Pattern::NodeType;

  auto IntCmpNode = Node{NodeType::Instr, InstrType::ICmp, (u32)0};
  auto SelectNode = Node{NodeType::Instr, InstrType::SelectInstr, (u32)0};

  pats.push_back(Pattern{
      .nodes = {IntCmpNode, SelectNode},
      .edges = {{0, 1, 0}},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        // handle dumb ? 1 : 0 or ? 0 : 1 patterns that can get generated by
        // optimizations but sometimes arnt cleaned up
        fir::Instr cmp_instr = res.matched_instrs[0];
        fir::Instr slct_instr = res.matched_instrs[1];

        if (!slct_instr->value_type->is_int() ||
            !slct_instr->args[1].is_constant() ||
            !slct_instr->args[2].is_constant()) {
          return false;
        }

        auto c1 = slct_instr->args[1].as_constant()->as_int();
        auto c2 = slct_instr->args[2].as_constant()->as_int();
        auto dir1 = (c1 == 1 && c2 == 0);
        auto dir2 = (c1 == 0 && c2 == 1);
        if (!dir1 && !dir2) {
          return false;
        }
        auto res_arg =
            valueToArg(fir::ValueR(slct_instr), res.result, data.alloc);
        auto arg1 = valueToArg(cmp_instr->args[0], res.result, data.alloc);
        auto arg2 = valueToArg(cmp_instr->args[1], res.result, data.alloc);
        Opcode op = Opcode::icmp_eq;

        switch ((fir::ICmpInstrSubType)cmp_instr->get_instr_subtype()) {
        case fir::ICmpInstrSubType::SLT:
          op = dir1 ? Opcode::icmp_slt : Opcode::icmp_sge;
          break;
        case fir::ICmpInstrSubType::ULT:
          op = dir1 ? Opcode::icmp_ult : Opcode::icmp_uge;
          break;
        case fir::ICmpInstrSubType::NE:
          op = dir1 ? Opcode::icmp_ne : Opcode::icmp_eq;
          break;
        case fir::ICmpInstrSubType::EQ:
          op = dir1 ? Opcode::icmp_eq : Opcode::icmp_ne;
          break;
        case fir::ICmpInstrSubType::SGT:
          op = dir1 ? Opcode::icmp_sgt : Opcode::icmp_sle;
          break;
        case fir::ICmpInstrSubType::UGT:
          op = dir1 ? Opcode::icmp_ugt : Opcode::icmp_ule;
          break;
        case fir::ICmpInstrSubType::UGE:
          op = dir1 ? Opcode::icmp_uge : Opcode::icmp_ult;
          break;
        case fir::ICmpInstrSubType::ULE:
          op = dir1 ? Opcode::icmp_ule : Opcode::icmp_ugt;
          break;
        case fir::ICmpInstrSubType::SGE:
          op = dir1 ? Opcode::icmp_sge : Opcode::icmp_slt;
          break;
        case fir::ICmpInstrSubType::SLE:
          op = dir1 ? Opcode::icmp_sle : Opcode::icmp_sgt;
          break;
        case fir::ICmpInstrSubType::INVALID:
          UNREACH();
        case fir::ICmpInstrSubType::MulOverflow:
          if (!dir1) {
            return false;
          }
          op = Opcode::icmp_mul_overflow;
          break;
        case fir::ICmpInstrSubType::AddOverflow:
          if (!dir1) {
            return false;
          }
          op = Opcode::icmp_add_overflow;
          break;
        }
        // Do a little cheating
        res_arg.reg.ty = Type::Int8;
        res.result.emplace_back(op, res_arg, arg1, arg2);

        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {IntCmpNode, SelectNode},
      .edges = {{0, 1, 0}},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        fir::Instr cmp_instr = res.matched_instrs[0];
        fir::Instr slct_instr = res.matched_instrs[1];

        switch ((fir::ICmpInstrSubType)cmp_instr->get_instr_subtype()) {
        case fir::ICmpInstrSubType::MulOverflow:
        case fir::ICmpInstrSubType::AddOverflow:
          // TODO: impl
          return false;
        default:
        }
        auto res_arg =
            valueToArg(fir::ValueR(slct_instr), res.result, data.alloc);
        if (res_arg.is_vec_reg() || res_arg.ty == Type::Int8) {
          return false;
        }
        auto c1 = valueToArg(cmp_instr->args[0], res.result, data.alloc);
        auto c2 = valueToArg(cmp_instr->args[1], res.result, data.alloc);
        auto arg1 = valueToArg(slct_instr->args[1], res.result, data.alloc);
        auto arg2 = valueToArg(slct_instr->args[2], res.result, data.alloc);
        Opcode op = Opcode::cmov;

        switch ((fir::ICmpInstrSubType)cmp_instr->get_instr_subtype()) {
        case fir::ICmpInstrSubType::SGT:
          op = Opcode::cmov_sgt;
          break;
        case fir::ICmpInstrSubType::SLT:
          op = Opcode::cmov_slt;
          break;
        case fir::ICmpInstrSubType::ULT:
          op = Opcode::cmov_ult;
          break;
        case fir::ICmpInstrSubType::SGE:
          op = Opcode::cmov_sge;
          break;
        case fir::ICmpInstrSubType::SLE:
          op = Opcode::cmov_sle;
          break;
        case fir::ICmpInstrSubType::NE:
          op = Opcode::cmov_ne;
          break;
        case fir::ICmpInstrSubType::EQ:
          op = Opcode::cmov_eq;
          break;
        case fir::ICmpInstrSubType::UGT:
          op = Opcode::cmov_ugt;
          break;
        case fir::ICmpInstrSubType::UGE:
          op = Opcode::cmov_uge;
          break;
        case fir::ICmpInstrSubType::ULE:
          op = Opcode::cmov_ule;
          break;
        case fir::ICmpInstrSubType::MulOverflow:
        case fir::ICmpInstrSubType::AddOverflow:
        case fir::ICmpInstrSubType::INVALID:
          UNREACH();
        }

        res.result.emplace_back(Opcode::mov, res_arg, arg2);
        res.result.emplace_back(op, res_arg, arg1, c1, c2);
        return true;
      }});
}
void memory_patterns(IRVec<Pattern> &pats) {
  using Node = Pattern::Node;
  using InstrType = fir::InstrType;
  using NodeType = Pattern::NodeType;

  auto IntAddNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                         (u32)fir::BinaryInstrSubType::IntAdd};
  auto IntMulNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                         (u32)fir::BinaryInstrSubType::IntMul};
  auto StoreNode = Node{NodeType::Instr, InstrType::StoreInstr, 0};
  auto LoadNode = Node{NodeType::Instr, InstrType::LoadInstr, 0};

  pats.push_back(Pattern{
      .nodes = {IntMulNode, IntAddNode, LoadNode},
      .edges = {{0, 1, 1}, {1, 2, 0}},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto mul_instr = res.matched_instrs[0];
        auto add_instr = res.matched_instrs[1];
        auto load_instr = res.matched_instrs[2];
        auto load_ty = convert_type(load_instr.get_type());
        auto add_ty = convert_type(add_instr.get_type());
        if (add_ty >= Type::Float32) {
          // cant do it on vector regs
          return false;
        }
        auto add_ty_size = get_size(add_ty);
        if (add_ty_size != 8 && add_ty_size != 4 && add_ty_size != 2) {
          return false;
        }
        if (!is_reg(add_instr->args[0]) || !is_reg(mul_instr->args[0]) ||
            !mul_instr->args[1].is_constant()) {
          return false;
        }
        auto consti = mul_instr->args[1].as_constant();
        if (!consti->is_int()) {
          return false;
        }
        auto consti_val = consti->as_int();

        switch (consti_val) {
        default: {
          return false;
        }
        case 1:
          consti_val = 0;
          break;
        case 2:
          consti_val = 1;
          break;
        case 4:
          consti_val = 2;
          break;
        case 8:
          consti_val = 3;
          break;
        }

        // $1 = $0 * C
        // R = $2 + $1
        // where $0 and $2 must be regs and C in [1,2,4,8]
        auto res_reg =
            valueToArg(fir::ValueR(load_instr), res.result, data.alloc);
        auto base = valueToArg(add_instr->args[0], res.result, data.alloc);
        auto indx = valueToArg(mul_instr->args[0], res.result, data.alloc);
        ASSERT(base.isReg());
        ASSERT(indx.isReg());
        res.result.emplace_back(
            Opcode::mov, res_reg,
            MArgument::MemBIS(base.reg, indx.reg, consti_val, load_ty));
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {IntMulNode, IntAddNode, StoreNode},
      .edges = {{0, 1, 1}, {1, 2, 0}},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto mul_instr = res.matched_instrs[0];
        auto add_instr = res.matched_instrs[1];
        auto store_instr = res.matched_instrs[2];
        auto store_ty = convert_type(store_instr.get_type());
        auto add_ty = convert_type(add_instr.get_type());
        if (add_ty >= Type::Float32) {
          // cant do it on vector regs
          return false;
        }
        auto add_ty_size = get_size(add_ty);
        if (add_ty_size != 8 && add_ty_size != 4 && add_ty_size != 2) {
          return false;
        }
        if (!is_reg(add_instr->args[0]) || !is_reg(mul_instr->args[0]) ||
            !mul_instr->args[1].is_constant()) {
          return false;
        }
        auto consti = mul_instr->args[1].as_constant();
        if (!consti->is_int()) {
          return false;
        }
        auto consti_val = consti->as_int();

        switch (consti_val) {
        default: {
          return false;
        }
        case 1:
          consti_val = 0;
          break;
        case 2:
          consti_val = 1;
          break;
        case 4:
          consti_val = 2;
          break;
        case 8:
          consti_val = 3;
          break;
        }

        // $1 = $0 * C
        // R = $2 + $1
        // where $0 and $2 must be regs and C in [1,2,4,8]
        auto value = valueToArg(store_instr->args[1], res.result, data.alloc);
        auto base = valueToArg(add_instr->args[0], res.result, data.alloc);
        auto indx = valueToArg(mul_instr->args[0], res.result, data.alloc);
        if (!base.isReg() || !indx.isReg()) {
          return false;
        }
        // ASSERT(base.isReg());
        // ASSERT(indx.isReg());
        res.result.emplace_back(
            Opcode::mov,
            MArgument::MemBIS(base.reg, indx.reg, consti_val, store_ty), value);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {IntAddNode, LoadNode},
      .edges = {{0, 1, 0}},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        ASSERT(res.matched_instrs[0].is_valid());
        ASSERT(res.matched_instrs[1].is_valid());

        auto add_instr = res.matched_instrs[0];
        auto load_instr = res.matched_instrs[1];

        auto res_reg =
            valueToArg(fir::ValueR(load_instr), res.result, data.alloc);
        auto load_ty = convert_type(load_instr.get_type());
        auto add_ty = convert_type(add_instr.get_type());
        if (add_ty >= Type::Float32) {
          // cant do it on vector regs
          return false;
        }

        auto a0 = valueToArg(add_instr->args[0], res.result, data.alloc);

        if (add_instr->args[1].is_constant() && a0.isImm()) {
          auto c1 = add_instr->args[1].as_constant();
          if (c1->is_global()) {
            auto repl =
                valueToArgPtr(add_instr->args[1], Type::Int64, data.alloc);
            ASSERT(repl.type == MArgument::ArgumentType::MemLabel);
            res.result.emplace_back(
                Opcode::mov, res_reg,
                MArgument::MemLO(repl.label, a0.imm, load_ty));
            return true;
          }
        }
        auto a1 = valueToArg(add_instr->args[1], res.result, data.alloc);
        if (add_instr->args[0].is_constant() && a1.isImm()) {
          auto c1 = add_instr->args[0].as_constant();
          if (c1->is_global()) {
            auto repl =
                valueToArgPtr(add_instr->args[0], Type::Int64, data.alloc);
            ASSERT(repl.type == MArgument::ArgumentType::MemLabel);
            res.result.emplace_back(
                Opcode::mov, res_reg,
                MArgument::MemLO(repl.label, a1.imm, load_ty));
            return true;
          }
        }
        // if (a0.isImm() && add_instr->args[0].is_constant() &&
        //     add_instr->args[0].as_constant()->as_int() < 0) {
        //   return false;
        // }
        // if (a1.isImm() && add_instr->args[1].is_constant() &&
        //     add_instr->args[1].as_constant()->as_int() < 0) {
        //   return false;
        // }

        if (a0.isReg() && a1.isImm()) {
          res.result.emplace_back(Opcode::mov, res_reg,
                                  MArgument::MemOB(a1.imm, a0.reg, load_ty));
        } else if (a0.isImm() && a1.isReg()) {
          res.result.emplace_back(Opcode::mov, res_reg,
                                  MArgument::MemOB(a0.imm, a1.reg, load_ty));
        } else if (a0.isReg() && a1.isReg()) {
          auto max_type = std::max(a0.reg.ty, a1.reg.ty);
          auto a0_ext = a0.reg;
          auto a1_ext = a1.reg;
          a0_ext.ty = max_type;
          a1_ext.ty = max_type;
          res.result.emplace_back(Opcode::mov, res_reg,
                                  MArgument::MemBI(a0_ext, a1_ext, load_ty));
        } else {
          return false;
        }
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {IntAddNode, IntAddNode, StoreNode},
      .edges = {{0, 1, 1}, {1, 2, 0}},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        ASSERT(res.matched_instrs[0].is_valid());
        ASSERT(res.matched_instrs[1].is_valid());
        ASSERT(res.matched_instrs[2].is_valid());

        auto add0_instr = res.matched_instrs[0];
        auto add1_instr = res.matched_instrs[1];
        auto store_instr = res.matched_instrs[2];

        auto add_ty = convert_type(add1_instr.get_type());
        if (add_ty >= Type::Float32) {
          // cant do it on vector regs
          return false;
        }
        auto store_ty = convert_type(store_instr.get_type());
        auto a00 = valueToArg(add0_instr->args[0], res.result, data.alloc);
        auto a01 = valueToArg(add0_instr->args[1], res.result, data.alloc);

        auto a10 = valueToArg(add1_instr->args[0], res.result, data.alloc);
        auto value = valueToArg(store_instr->args[1], res.result, data.alloc);

        if (a00.isReg() && a01.isImm() && a10.isReg()) {
          res.result.emplace_back(
              Opcode::mov,
              MArgument::MemOBI(a01.imm, a00.reg, a10.reg, store_ty), value);
        } else if (a00.isImm() && a01.isReg() && a10.isReg()) {
          res.result.emplace_back(
              Opcode::mov,
              MArgument::MemOBI(a00.imm, a01.reg, a10.reg, store_ty), value);
        } else {
          return false;
        }
        return true;
      }});

  pats.push_back(Pattern{
      .nodes = {IntAddNode, StoreNode},
      .edges = {{0, 1, 0}},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        ASSERT(res.matched_instrs[0].is_valid());
        ASSERT(res.matched_instrs[1].is_valid());

        // return false;
        auto add_instr = res.matched_instrs[0];
        auto add_ty = convert_type(add_instr.get_type());
        if (add_ty >= Type::Float32) {
          // cant do it on vector regs
          return false;
        }
        auto store_instr = res.matched_instrs[1];

        auto store_ty = convert_type(store_instr.get_type());
        auto value = valueToArg(store_instr->args[1], res.result, data.alloc);

        auto a0 = valueToArg(add_instr->args[0], res.result, data.alloc);
        if (add_instr->args[1].is_constant() && a0.isImm()) {
          auto c1 = add_instr->args[1].as_constant();
          if (c1->is_global()) {
            auto repl =
                valueToArgPtr(add_instr->args[1], Type::Int64, data.alloc);
            ASSERT(repl.type == MArgument::ArgumentType::MemLabel);
            res.result.emplace_back(
                Opcode::mov, MArgument::MemLO(repl.label, a0.imm, store_ty),
                value);
            return true;
          }
          if (c1->is_int() && c1->as_int() < 0) {
            return false;
          }
        }

        auto a1 = valueToArg(add_instr->args[1], res.result, data.alloc);
        if (add_instr->args[0].is_constant() && a1.isImm()) {
          auto c1 = add_instr->args[0].as_constant();
          if (c1->is_global()) {
            auto repl =
                valueToArgPtr(add_instr->args[0], Type::Int64, data.alloc);
            ASSERT(repl.type == MArgument::ArgumentType::MemLabel);
            res.result.emplace_back(
                Opcode::mov, MArgument::MemLO(repl.label, a1.imm, store_ty),
                value);
            return true;
          }
        }
        if (a0.isImm() && add_instr->args[0].is_constant() &&
            add_instr->args[0].as_constant()->as_int() < 0) {
          return false;
        }
        if (a1.isImm() && add_instr->args[1].is_constant() &&
            add_instr->args[1].as_constant()->as_int() < 0) {
          return false;
        }

        if (a0.isReg() && a1.isImm()) {
          res.result.emplace_back(
              Opcode::mov, MArgument::MemOB(a1.imm, a0.reg, store_ty), value);
        } else if (a0.isImm() && a1.isReg()) {
          res.result.emplace_back(
              Opcode::mov, MArgument::MemOB(a0.imm, a1.reg, store_ty), value);
        } else if (a0.isReg() && a1.isReg()) {
          res.result.emplace_back(
              Opcode::mov, MArgument::MemBI(a0.reg, a1.reg, store_ty), value);
        } else {
          return false;
        }
        return true;
      }});
  // pats.push_back(Pattern{
  //     {LoadNode, IntAddNode},
  //     {{0, 1, 0}},
  //     [](MatchResult &res, ExtraMatchData &data) {
  //       auto load_instr = res.matched_instrs[0];
  //       auto add_instr = res.matched_instrs[1];
  //       auto res_reg =
  //           valueToArg(fir::ValueR(add_instr), res.result, data.alloc);

  //       auto a0 =
  //           valueToArgPtr(load_instr->args[0],
  //                         convert_type(load_instr.get_type()), data.alloc);
  //       a0.ty = convert_type(load_instr.get_type());
  //       auto a1 = valueToArg(add_instr->args[1], res.result, data.alloc);
  //       res.result.emplace_back(Opcode::mov, res_reg, a0);
  //       res.result.emplace_back(Opcode::add2, res_reg, a1);
  //       return true;
  //     }});
}

void cjmp_patterns(IRVec<Pattern> &pats) {
  using Node = Pattern::Node;
  using InstrType = fir::InstrType;
  using NodeType = Pattern::NodeType;
  auto ICMPNode = Node{NodeType::Instr, InstrType::ICmp, 0};
  auto FCMPNode = Node{NodeType::Instr, InstrType::FCmp, 0};
  auto CondBranchNode = Node{NodeType::Instr, InstrType::CondBranchInstr, 0};

  pats.push_back(Pattern{
      .nodes = {ICMPNode, CondBranchNode},
      .edges = {{0, 1, 0}},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto cmp_instr = res.matched_instrs[0];
        auto branch_instr = res.matched_instrs[1];

        auto sub_type = (fir::ICmpInstrSubType)cmp_instr->get_instr_subtype();

        // first we check if we can output a simplified version
        if (sub_type != fir::ICmpInstrSubType::SLT &&
            sub_type != fir::ICmpInstrSubType::SGE &&
            sub_type != fir::ICmpInstrSubType::SLE &&
            sub_type != fir::ICmpInstrSubType::SGT &&
            sub_type != fir::ICmpInstrSubType::NE &&
            sub_type != fir::ICmpInstrSubType::EQ &&
            sub_type != fir::ICmpInstrSubType::ULT &&
            sub_type != fir::ICmpInstrSubType::ULE &&
            sub_type != fir::ICmpInstrSubType::UGT &&
            sub_type != fir::ICmpInstrSubType::UGE) {
          fmt::println("Failed to smartly match cmp {} + branch\n",
                       cmp_instr->get_instr_subtype());
          return false;
        }

        auto &bb_with_args = branch_instr->bbs[0];
        auto target_bb = branch_instr->bbs[0].bb;
        auto v1 = valueToArg(cmp_instr->args[0], res.result, data.alloc);
        auto v2 = valueToArg(cmp_instr->args[1], res.result, data.alloc);

        // auto comp_ty = v1_orig.ty;

        // auto v1_reg = data.alloc.get_new_register(VRegInfo{comp_ty});
        // auto v2_reg = data.alloc.get_new_register(VRegInfo{comp_ty});
        // auto v1 = MArgument{v1_reg, comp_ty};
        // auto v2 = MArgument{v2_reg, comp_ty};

        // TODO: this is a issue with lifetimes
        // res.result.emplace_back(Opcode::mov, v1, v1_orig);
        // res.result.emplace_back(Opcode::mov, v2, v2_orig);

        ASSERT(bb_with_args.args.size() == target_bb->args.size());
        // ASSERT(bb_with_args.args.size() == 0);
        generate_bb_args(bb_with_args, res, data);

        if (sub_type == fir::ICmpInstrSubType::SLT) {
          res.result.push_back(
              MInstr::cJmp_slt(v1, v2, data.bbs[bb_with_args.bb]));
        } else if (sub_type == fir::ICmpInstrSubType::SGT) {
          res.result.push_back(
              MInstr::cJmp_sgt(v1, v2, data.bbs[bb_with_args.bb]));
        } else if (sub_type == fir::ICmpInstrSubType::ULT) {
          res.result.push_back(
              MInstr::cJmp_ult(v1, v2, data.bbs[bb_with_args.bb]));
        } else if (sub_type == fir::ICmpInstrSubType::ULE) {
          res.result.push_back(
              MInstr::cJmp_ule(v1, v2, data.bbs[bb_with_args.bb]));
        } else if (sub_type == fir::ICmpInstrSubType::UGT) {
          res.result.push_back(
              MInstr::cJmp_ugt(v1, v2, data.bbs[bb_with_args.bb]));
        } else if (sub_type == fir::ICmpInstrSubType::UGE) {
          res.result.push_back(
              MInstr::cJmp_uge(v1, v2, data.bbs[bb_with_args.bb]));
        } else if (sub_type == fir::ICmpInstrSubType::SGE) {
          res.result.push_back(
              MInstr::cJmp_sge(v1, v2, data.bbs[bb_with_args.bb]));
        } else if (sub_type == fir::ICmpInstrSubType::SLE) {
          res.result.push_back(
              MInstr::cJmp_sle(v1, v2, data.bbs[bb_with_args.bb]));
        } else if (sub_type == fir::ICmpInstrSubType::EQ) {
          res.result.push_back(
              MInstr::cJmp_eq(v1, v2, data.bbs[bb_with_args.bb]));
        } else if (sub_type == fir::ICmpInstrSubType::NE) {
          res.result.push_back(
              MInstr::cJmp_ne(v1, v2, data.bbs[bb_with_args.bb]));
        } else {
          UNREACH();
        }

        {
          auto bb2_with_args = branch_instr->bbs[1];
          auto target_bb2 = branch_instr->bbs[1].bb;
          ASSERT(bb2_with_args.args.size() == target_bb2->args.size());
          // ASSERT(bb2_with_args.args.size() == 0);
          generate_bb_args(bb2_with_args, res, data);
          res.result.push_back(MInstr::jmp(data.bbs[bb2_with_args.bb]));
        }
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {FCMPNode, CondBranchNode},
      .edges = {{0, 1, 0}},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto cmp_instr = res.matched_instrs[0];
        auto branch_instr = res.matched_instrs[1];

        auto sub_type = (fir::FCmpInstrSubType)cmp_instr->get_instr_subtype();

        auto &bb_with_args = branch_instr->bbs[0];
        auto target_bb = branch_instr->bbs[0].bb;
        auto v1 = valueToArg(cmp_instr->args[0], res.result, data.alloc);
        auto v2 = valueToArg(cmp_instr->args[1], res.result, data.alloc);

        ASSERT(bb_with_args.args.size() == target_bb->args.size());
        generate_bb_args(bb_with_args, res, data);

        // TODO: we can ofcourse support this
        if (sub_type == fir::FCmpInstrSubType::IsNaN) {
          return false;
        }

        res.result.push_back(
            MInstr::cJmp_flt(v1, v2, data.bbs[bb_with_args.bb], sub_type));

        {
          auto bb2_with_args = branch_instr->bbs[1];
          auto target_bb2 = branch_instr->bbs[1].bb;
          ASSERT(bb2_with_args.args.size() == target_bb2->args.size());
          generate_bb_args(bb2_with_args, res, data);
          res.result.push_back(MInstr::jmp(data.bbs[bb2_with_args.bb]));
        }
        return true;
      }});
}

void arith_patterns(IRVec<Pattern> &pats) {
  using Node = Pattern::Node;
  using InstrType = fir::InstrType;
  using NodeType = Pattern::NodeType;

  auto IntAddNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                         (u32)fir::BinaryInstrSubType::IntAdd};
  // auto IntSubNode = Node{NodeType::Instr, InstrType::BinaryInstr,
  //                        (u32)fir::BinaryInstrSubType::IntSub};
  auto IntMulNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                         (u32)fir::BinaryInstrSubType::IntMul};
  auto SRemNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                       (u32)fir::BinaryInstrSubType::IntSRem};
  auto UDivNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                       (u32)fir::BinaryInstrSubType::IntUDiv};
  auto SDivNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                       (u32)fir::BinaryInstrSubType::IntSDiv};
  // auto AndNode = Node{NodeType::Instr, InstrType::BinaryInstr,
  //                     (u32)fir::BinaryInstrSubType::And};
  // auto OrNode = Node{NodeType::Instr, InstrType::BinaryInstr,
  //                    (u32)fir::BinaryInstrSubType::Or};
  // auto XorNode = Node{NodeType::Instr, InstrType::BinaryInstr,
  //                     (u32)fir::BinaryInstrSubType::Xor};
  auto FloatAddNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                           (u32)fir::BinaryInstrSubType::FloatAdd};
  auto FloatMulNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                           (u32)fir::BinaryInstrSubType::FloatMul};
  // auto ShlNode = Node{NodeType::Instr, InstrType::BinaryInstr,
  //                     (u32)fir::BinaryInstrSubType::Shl};
  // auto ShrNode = Node{NodeType::Instr, InstrType::BinaryInstr,
  //                     (u32)fir::BinaryInstrSubType::Shr};
  // auto AShrNode = Node{NodeType::Instr, InstrType::BinaryInstr,
  //                      (u32)fir::BinaryInstrSubType::AShr};
  // auto ConversionNode = Node{NodeType::Instr, InstrType::Conversion, 0};

  pats.push_back(Pattern{
      .nodes = {SDivNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        (void)data;
        auto div_instr = res.matched_instrs[0];
        if (!div_instr->args[1].is_constant()) {
          return false;
        }
        if (!div_instr->args[1].as_constant()->is_int()) {
          return false;
        }

        auto c = div_instr->args[1].as_constant()->as_int();
        auto out_type = convert_type(div_instr->get_type());
        (void)out_type;
        switch (c) {
        default:
          return false;
        case 8: {
          auto res_reg =
              valueToArg(fir::ValueR(div_instr), res.result, data.alloc);
          auto base = valueToArg(div_instr->args[0], res.result, data.alloc);
          // lea eax, [rdi + 7]
          ASSERT(base.isReg());
          res.result.emplace_back(Opcode::lea, res_reg,
                                  MArgument::MemOB(7, base.reg, out_type));
          // test edi, edi
          // cmovns eax, edi
          res.result.emplace_back(Opcode::cmov_ns, res_reg, base, base, base);
          // sar eax, 3
          res.result.emplace_back(Opcode::sar2, res_reg, MArgument((u8)3));
        }
        }

        // res.result.emplace_back(Opcode::mov, res_reg, base);
        // res.result.emplace_back(Opcode::shr2, res_reg,
        // MArgument((u32)power));
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {UDivNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        (void)data;
        auto div_instr = res.matched_instrs[0];
        if (!div_instr->args[1].is_constant()) {
          return false;
        }
        if (!div_instr->args[1].as_constant()->is_int()) {
          return false;
        }

        auto c = div_instr->args[1].as_constant()->as_int();
        if (c <= 0 || c > std::numeric_limits<u32>::max() ||
            (c & (c - 1)) != 0) {
          return false;
        }
        auto power = std::bit_width((u32)c) - 1;

        auto res_reg =
            valueToArg(fir::ValueR(div_instr), res.result, data.alloc);
        auto base = valueToArg(div_instr->args[0], res.result, data.alloc);
        res.result.emplace_back(Opcode::mov, res_reg, base);
        res.result.emplace_back(Opcode::shr2, res_reg, MArgument((u32)power));
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {IntMulNode, IntAddNode},
      .edges = {{0, 1, 1}},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        // x + y * 1|2|4|8
        auto mul_instr = res.matched_instrs[0];
        auto add_instr = res.matched_instrs[1];
        auto add_ty = convert_type(add_instr.get_type());
        if (add_ty >= Type::Float32) {
          // cant do it on vector regs
          return false;
        }
        auto res_ty = convert_type(add_instr.get_type());
        auto res_ty_size = get_size(res_ty);
        if (res_ty_size != 8 && res_ty_size != 4 && res_ty_size != 2) {
          return false;
        }
        if (!is_reg(add_instr->args[0]) || !is_reg(mul_instr->args[0]) ||
            !mul_instr->args[1].is_constant()) {
          return false;
        }
        auto consti = mul_instr->args[1].as_constant();
        if (!consti->is_int()) {
          return false;
        }
        auto consti_val = consti->as_int();

        switch (consti_val) {
        default: {
          return false;
        }
        case 1:
          consti_val = 0;
          break;
        case 2:
          consti_val = 1;
          break;
        case 4:
          consti_val = 2;
          break;
        case 8:
          consti_val = 3;
          break;
        }

        // $1 = $0 * C
        // R = $2 + $1
        // where $0 and $2 must be regs and C in [1,2,4,8]
        auto res_reg =
            valueToArg(fir::ValueR(add_instr), res.result, data.alloc);
        auto base = valueToArg(add_instr->args[0], res.result, data.alloc);
        auto indx = valueToArg(mul_instr->args[0], res.result, data.alloc);
        if (!base.isReg() || !indx.isReg()) {
          return false;
        }
        auto base_reg = base.reg;
        auto indx_reg = indx.reg;
        res.result.emplace_back(
            Opcode::lea, res_reg,
            MArgument::MemBIS(base_reg, indx_reg, consti_val, res_ty));
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {IntAddNode, IntAddNode},
      .edges = {{0, 1, 0}},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        // x + y + c
        // x + c + y
        auto add0_instr = res.matched_instrs[0];
        auto add1_instr = res.matched_instrs[1];
        auto add_ty = convert_type(add1_instr.get_type());
        if (add_ty >= Type::Float32) {
          // cant do it on vector regs
          return false;
        }
        auto res_ty = convert_type(add1_instr.get_type());
        auto res_ty_size = get_size(res_ty);
        if (res_ty_size != 8 && res_ty_size != 4 && res_ty_size != 2) {
          return false;
        }
        // TODO: handle x + c +y
        if (!is_reg(add1_instr->args[0]) || !is_reg(add0_instr->args[0]) ||
            !add0_instr->args[1].is_constant()) {
          return false;
        }
        auto consti = add0_instr->args[1].as_constant();
        if (!consti->is_int()) {
          return false;
        }
        auto consti_val = consti->as_int();

        if (consti_val > 128 || consti_val < 128) {
          return false;
        }
        auto res_reg =
            valueToArg(fir::ValueR(add1_instr), res.result, data.alloc);
        auto a = valueToArg(add0_instr->args[0], res.result, data.alloc);
        auto b = valueToArg(add1_instr->args[0], res.result, data.alloc);
        if (!a.isReg() || !b.isReg()) {
          return false;
        }
        res.result.emplace_back(
            Opcode::lea, res_reg,
            MArgument::MemOBI((u8)consti_val, a.reg, b.reg, res_ty));
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {IntMulNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        // x*c where c is either 2 4 8  or 3 5 9
        auto mul_instr = res.matched_instrs[0];
        auto res_ty = convert_type(mul_instr.get_type());
        auto res_ty_size = get_size(res_ty);
        if (res_ty_size != 8 && res_ty_size != 4 && res_ty_size != 2) {
          return false;
        }
        if (!is_reg(mul_instr->args[0]) || !mul_instr->args[1].is_constant()) {
          return false;
        }
        auto consti = mul_instr->args[1].as_constant();
        if (!consti->is_int()) {
          return false;
        }
        auto consti_val = consti->as_int();
        bool mul1More = false;
        bool mul1Less = false;

        switch (consti_val) {
        default: {
          return false;
        }
        case 1:
          consti_val = 0;
          break;
        case 2:
          consti_val = 1;
          break;
        case 3:
          consti_val = 1;
          mul1More = true;
          break;
        case 4:
          consti_val = 2;
          break;
        case 5:
          consti_val = 2;
          mul1More = true;
          break;
        case 6: {
          auto res_reg =
              valueToArg(fir::ValueR(mul_instr), res.result, data.alloc);
          auto helper_reg = data.alloc.get_new_register(res_ty);
          auto helper_arg = MArgument(helper_reg, res_ty);
          auto base = valueToArg(mul_instr->args[0], res.result, data.alloc);
          res.result.emplace_back(Opcode::mov, helper_arg, base);
          res.result.emplace_back(Opcode::add2, helper_arg, helper_arg);
          res.result.emplace_back(
              Opcode::lea, res_reg,
              MArgument::MemBIS(helper_reg, helper_reg, 2, res_ty));
          return true;
        }
        case 7:
          consti_val = 3;
          mul1Less = true;
          break;
        case 8:
          consti_val = 3;
          break;
        case 9:
          consti_val = 3;
          mul1More = true;
          break;
        }

        // $1 = $0 * c
        // where $0 must be reg and C in [1,2,3,4,5,8,9]
        auto res_reg =
            valueToArg(fir::ValueR(mul_instr), res.result, data.alloc);
        auto base = valueToArg(mul_instr->args[0], res.result, data.alloc);
        ASSERT(base.isReg());
        if (mul1More) {
          res.result.emplace_back(
              Opcode::lea, res_reg,
              MArgument::MemBIS(base.reg, base.reg, consti_val, res_ty));
        } else if (mul1Less) {
          res.result.emplace_back(
              Opcode::lea, res_reg,
              MArgument::MemOIS(0, base.reg, consti_val, res_ty));
          res.result.emplace_back(Opcode::sub2, res_reg, base);
        } else {
          res.result.emplace_back(
              Opcode::lea, res_reg,
              MArgument::MemOIS(0, base.reg, consti_val, res_ty));
        }
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {IntMulNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        // x*c where c is a power of 2
        auto mul_instr = res.matched_instrs[0];
        auto res_ty = convert_type(mul_instr.get_type());
        auto res_ty_size = get_size(res_ty);
        if (res_ty_size != 8 && res_ty_size != 4 && res_ty_size != 2) {
          return false;
        }
        if (!is_reg(mul_instr->args[0]) || !mul_instr->args[1].is_constant()) {
          return false;
        }
        auto consti = mul_instr->args[1].as_constant();
        if (!consti->is_int()) {
          return false;
        }
        auto consti_val = consti->as_int();
        if (consti_val <= 0) {
          return false;
        }

        // TODO: if off by 1 or similar could do shift and then use a add
        if (__builtin_popcount(consti_val) != 1) {
          return false;
        }
        auto x = consti_val;
        u16 shift_width = 0;
        for (shift_width = 0; x != 1; x >>= 1, shift_width++) {
        }
        // auto  =
        //     sizeof(i128) * CHAR_BIT - __builtin_clzg((u128)consti_val) - 1;

        ASSERT(shift_width < 256);
        auto res_reg =
            valueToArg(fir::ValueR(mul_instr), res.result, data.alloc);
        auto base = valueToArg(mul_instr->args[0], res.result, data.alloc);
        ASSERT(base.isReg());
        res.result.emplace_back(Opcode::mov, res_reg, base);
        res.result.emplace_back(Opcode::shl2, res_reg,
                                MArgument((u8)shift_width));
        return true;
      }});

  pats.push_back(Pattern{
      .nodes = {FloatMulNode, FloatAddNode},
      .edges = {{0, 1, 0}},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto mul_instr = res.matched_instrs[0];
        auto add_instr = res.matched_instrs[1];
        auto res_reg =
            valueToArg(fir::ValueR(add_instr), res.result, data.alloc);
        auto mul_arg1 = valueToArg(mul_instr->args[0], res.result, data.alloc);
        auto mul_arg2 = valueToArg(mul_instr->args[1], res.result, data.alloc);
        auto add_arg2 = valueToArg(add_instr->args[1], res.result, data.alloc);

        if (res_reg == add_arg2 && add_arg2.isReg() && mul_arg1.isReg() &&
            (mul_arg2.isReg() || mul_arg2.isMem())) {
          res.result.emplace_back(Opcode::ffmadd231, res_reg, mul_arg1,
                                  mul_arg2);
        } else if (res_reg == mul_arg1 && mul_arg1.isReg() &&
                   mul_arg2.isReg() && (add_arg2.isReg() || add_arg2.isMem())) {
          res.result.emplace_back(Opcode::ffmadd231, mul_arg1, mul_arg2,

                                  add_arg2);
        } else if (res_reg == mul_arg2 && mul_arg1.isReg() &&
                   mul_arg2.isReg() && (add_arg2.isReg() || add_arg2.isMem())) {
          res.result.emplace_back(Opcode::ffmadd231, mul_arg2, mul_arg1,

                                  add_arg2);
        } else if (res_reg == mul_arg1 && mul_arg1.isReg() &&
                   add_arg2.isReg() && (mul_arg2.isReg() || mul_arg2.isMem())) {
          res.result.emplace_back(Opcode::ffmadd132, mul_arg1, add_arg2,
                                  mul_arg2);
        } else if (res_reg == mul_arg2 && mul_arg2.isReg() &&
                   add_arg2.isReg() && (mul_arg1.isReg() || mul_arg1.isMem())) {
          res.result.emplace_back(Opcode::ffmadd132, mul_arg2, add_arg2,
                                  mul_arg1);
        } else {
          // res.result.emplace_back(Opcode::mov, res_reg, add_arg2);
          // res.result.emplace_back(Opcode::ffmadd231, res_reg, mul_arg1,
          //                         mul_arg2);
          // res.result.emplace_back(Opcode::mov, res_reg, mul_arg1);
          // res.result.emplace_back(Opcode::ffmadd132, res_reg, add_arg2,
          //                         mul_arg2);
          res.result.emplace_back(Opcode::fmul, res_reg, mul_arg1, mul_arg2);
          res.result.emplace_back(Opcode::vadd, res_reg, res_reg, add_arg2);
        }
        return true;
      }});
  pats.push_back(
      Pattern{.nodes = {SRemNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                auto srem_instr = res.matched_instrs[0];
                if (!srem_instr->args[1].is_constant()) {
                  return false;
                }
                // auto res_reg =
                //     valueToArg(fir::ValueR(srem_instr), res.result,
                //     data.alloc);
                // auto arg = valueToArg(srem_instr->args[0], res.result,
                // data.alloc);
                auto const_arg =
                    valueToArg(srem_instr->args[1], res.result, data.alloc);

                if (!const_arg.isImm()) {
                  return false;
                }
                if (srem_instr.get_type()->as_int() != 32) {
                  return false;
                }
                fmt::println("Could have optimized the matchign of srem");
                // TODO("impl");

                return false;
              }});
}

void base_patterns(IRVec<Pattern> &pats) {
  using Node = Pattern::Node;
  using InstrType = fir::InstrType;
  using NodeType = Pattern::NodeType;

  auto UnreachNode = Node{NodeType::Instr, InstrType::Unreachable, 0};
  auto NotNode = Node{NodeType::Instr, InstrType::UnaryInstr,
                      (u32)fir::UnaryInstrSubType::Not};
  auto NegateNode = Node{NodeType::Instr, InstrType::UnaryInstr,
                         (u32)fir::UnaryInstrSubType::IntNeg};
  auto IntAddNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                         (u32)fir::BinaryInstrSubType::IntAdd};
  auto IntSubNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                         (u32)fir::BinaryInstrSubType::IntSub};
  auto IntMulNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                         (u32)fir::BinaryInstrSubType::IntMul};
  auto SRemNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                       (u32)fir::BinaryInstrSubType::IntSRem};
  auto SDivNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                       (u32)fir::BinaryInstrSubType::IntSDiv};
  auto UDivNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                       (u32)fir::BinaryInstrSubType::IntUDiv};
  auto AndNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                      (u32)fir::BinaryInstrSubType::And};
  auto OrNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                     (u32)fir::BinaryInstrSubType::Or};
  auto XorNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                      (u32)fir::BinaryInstrSubType::Xor};
  auto FloatAddNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                           (u32)fir::BinaryInstrSubType::FloatAdd};
  auto FloatSubNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                           (u32)fir::BinaryInstrSubType::FloatSub};
  auto FloatMulNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                           (u32)fir::BinaryInstrSubType::FloatMul};
  auto FloatDivNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                           (u32)fir::BinaryInstrSubType::FloatDiv};
  auto FloatNegNode = Node{NodeType::Instr, InstrType::UnaryInstr,
                           (u32)fir::UnaryInstrSubType::FloatNeg};
  auto ShlNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                      (u32)fir::BinaryInstrSubType::Shl};
  auto ShrNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                      (u32)fir::BinaryInstrSubType::Shr};
  auto AShrNode = Node{NodeType::Instr, InstrType::BinaryInstr,
                       (u32)fir::BinaryInstrSubType::AShr};
  auto ConversionNode = Node{NodeType::Instr, InstrType::Conversion, 0};
  auto ICMPNode = Node{NodeType::Instr, InstrType::ICmp, 0};
  auto FCMPNode = Node{NodeType::Instr, InstrType::FCmp, 0};
  auto BranchNode = Node{NodeType::Instr, InstrType::BranchInstr, 0};
  auto CondBranchNode = Node{NodeType::Instr, InstrType::CondBranchInstr, 0};
  auto SwitchNode = Node{NodeType::Instr, InstrType::SwitchInstr, 0};
  auto ReturnNode = Node{NodeType::Instr, InstrType::ReturnInstr, 0};
  auto CallNode = Node{NodeType::Instr, InstrType::CallInstr, 0};
  auto StoreNode = Node{NodeType::Instr, InstrType::StoreInstr, 0};
  auto LoadNode = Node{NodeType::Instr, InstrType::LoadInstr, 0};
  auto AllocaNode = Node{NodeType::Instr, InstrType::AllocaInstr, 0};
  auto SExtNode = Node{NodeType::Instr, InstrType::SExt, 0};
  auto ZExtNode = Node{NodeType::Instr, InstrType::ZExt, 0};
  auto ITruncNode = Node{NodeType::Instr, InstrType::ITrunc, 0};
  auto SelectNode = Node{NodeType::Instr, InstrType::SelectInstr, 0};
  auto BroadcastNode = Node{NodeType::Instr, InstrType::VectorInstr,
                            (u32)fir::VectorISubType::Broadcast};

  pats.push_back(
      Pattern{.nodes = {AllocaNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                // TODO: this should be done once for all allocas that only
                // get executed once
                auto alloca_instr = res.matched_instrs[0];
                auto rsp_reg = VReg::RSP();
                auto rsp_arg = MArgument{rsp_reg, Type::Int64};

                auto res_reg = valueToArg(fir::ValueR(alloca_instr), res.result,
                                          data.alloc);
                if (!alloca_instr->args[0].is_constant()) {
                  return false;
                }

                auto size = (u64)alloca_instr->args[0].as_constant()->as_int();
                // TODO: this is inefficient for many stack allocations
                // TODO: this also depends on the calling conv
                if (size % 16 != 0) {
                  size = size + (16 - (size % 16));
                }

                res.result.emplace_back(Opcode::sub2, rsp_arg, size);
                res.result.emplace_back(Opcode::mov, res_reg, rsp_arg);
                return true;
              }});
  pats.push_back(
      Pattern{.nodes = {LoadNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                auto load_instr = res.matched_instrs[0];
                auto res_reg =
                    valueToArg(fir::ValueR(load_instr), res.result, data.alloc);
                auto arg = valueToArgPtr(load_instr->args[0],
                                         convert_type(load_instr.get_type()),
                                         data.alloc);
                arg.ty = convert_type(load_instr.get_type());
                res.result.emplace_back(Opcode::mov, res_reg, arg);
                return true;
              }});
  pats.push_back(Pattern{
      .nodes = {StoreNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto store_instr = res.matched_instrs[0];
        auto value = valueToArg(store_instr->args[1], res.result, data.alloc);

        auto ptr_target =
            valueToArgPtr(store_instr->args[0],
                          convert_type(store_instr.get_type()), data.alloc);
        ptr_target.ty = convert_type(store_instr.get_type());
        res.result.emplace_back(Opcode::mov, ptr_target, value);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {IntAddNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto add_instr = res.matched_instrs[0];
        auto res_reg =
            valueToArg(fir::ValueR(add_instr), res.result, data.alloc);
        auto a0 = valueToArg(add_instr->args[0], res.result, data.alloc);

        auto res_ty = convert_type(add_instr.get_type());
        if (res_ty >= Type::Float32) {
          // int vector add has different 3 oeprand operation
          auto a1 = valueToArg(add_instr->args[1], res.result, data.alloc);
          res.result.emplace_back(Opcode::vadd, res_reg, a0, a1);
          return true;
        }
        if (res_reg.ty != a0.ty) {
          auto res_reg = data.alloc.get_new_register(res_ty);
          auto helper_reg0 = MArgument(res_reg, res_ty);

          res.result.emplace_back(Opcode::mov, helper_reg0, a0);
          a0 = helper_reg0;
        }

        auto a1 = valueToArg(add_instr->args[1], res.result, data.alloc);
        if (a1.isImm()) {
          // then we gucci
        } else if (res_reg.ty != a1.ty) {
          auto res_reg = data.alloc.get_new_register(res_ty);
          auto helper_reg1 = MArgument(res_reg, res_ty);

          res.result.emplace_back(Opcode::mov, helper_reg1, a1);
          a1 = helper_reg1;
        }

        res.result.emplace_back(Opcode::mov, res_reg, a0);
        res.result.emplace_back(Opcode::add2, res_reg, a1);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {SelectNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto select_instr = res.matched_instrs[0];
        auto res_reg =
            valueToArg(fir::ValueR(select_instr), res.result, data.alloc);
        auto cond = valueToArg(select_instr->args[0], res.result, data.alloc);
        auto a = valueToArg(select_instr->args[1], res.result, data.alloc);
        auto b = valueToArg(select_instr->args[2], res.result, data.alloc);

        res.result.emplace_back(Opcode::mov, res_reg, b);
        res.result.emplace_back(Opcode::cmov, res_reg, cond, a);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {NotNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto not_instr = res.matched_instrs[0];
        auto res_reg =
            valueToArg(fir::ValueR(not_instr), res.result, data.alloc);

        if (res_reg.is_fp()) {
          TODO("impl");
        } else {
          auto bitwidth = not_instr.get_type()->as_int();
          if (bitwidth == 1) {
            res.result.emplace_back(
                Opcode::mov, res_reg,
                valueToArg(not_instr->args[0], res.result, data.alloc));
            res.result.emplace_back(Opcode::lxor2, res_reg, MArgument((u8)0x1));
            return true;
          }

          ASSERT(bitwidth == 4 || bitwidth == 8);
          res.result.emplace_back(
              Opcode::mov, res_reg,
              valueToArg(not_instr->args[0], res.result, data.alloc));
          res.result.emplace_back(Opcode::not1, res_reg);
        }
        return true;
      }});
  pats.push_back(
      Pattern{.nodes = {NegateNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                auto negate_instr = res.matched_instrs[0];
                auto res_reg = valueToArg(fir::ValueR(negate_instr), res.result,
                                          data.alloc);

                res.result.emplace_back(
                    Opcode::mov, res_reg,
                    valueToArg(negate_instr->args[0], res.result, data.alloc));
                res.result.emplace_back(Opcode::neg1, res_reg);
                return true;
              }});
  pats.push_back(Pattern{
      .nodes = {BroadcastNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto broad_instr = res.matched_instrs[0];
        auto res_reg =
            valueToArg(fir::ValueR(broad_instr), res.result, data.alloc);
        auto arg = valueToArg(broad_instr->args[0], res.result, data.alloc);
        if (arg.isImm() && ((!arg.is_fp() && arg.imm == 0) ||
                            (arg.is_fp() && arg.immf == 0))) {
          res.result.emplace_back(Opcode::fxor, res_reg, res_reg, res_reg);
          return true;
        }
        // TODO: better to use if we know that its the n lowest bits that are
        // set pcmpeqd       xmm0, xmm0 psrld xmm0, 32-n

        auto res_reg_smoll = res_reg;
        bool can_pshuf = false;
        bool can_punpckl = false;
        bool can_vbroadcast = false;
        switch (res_reg.ty) {
        case Type::INVALID:
        case Type::Int32x4:
        case Type::Int32x8:
        case Type::Float32x8:
        case Type::Float32x4:
          can_pshuf = true;
          res_reg_smoll.ty = Type::Float32;
          res_reg_smoll.reg.ty = Type::Float32;
          break;
        case Type::Int64x2:
        case Type::Float64x2:
          can_punpckl = true;
          res_reg_smoll.ty = Type::Float64;
          res_reg_smoll.reg.ty = Type::Float64;
          break;
        case Type::Int64x4:
        case Type::Float64x4:
          can_vbroadcast = true;
          res_reg_smoll.ty = Type::Float64;
          res_reg_smoll.reg.ty = Type::Float64;
          break;
        default:
          TODO("UNREACH");
        }
        if (can_pshuf) {
          res.result.emplace_back(Opcode::mov, res_reg_smoll, arg);
          res.result.emplace_back(Opcode::vpshuf, res_reg, res_reg,
                                  MArgument((u8)0));
          return true;
        }
        if (can_punpckl) {
          res.result.emplace_back(Opcode::mov, res_reg_smoll, arg);
          res.result.emplace_back(Opcode::punpckl, res_reg, res_reg, res_reg);
          return true;
        }
        if (can_vbroadcast) {
          res.result.emplace_back(Opcode::mov, res_reg_smoll, arg);
          res.result.emplace_back(Opcode::vbroadcast, res_reg, res_reg,
                                  res_reg);
          return true;
        }
        TODO("IMPL broadcast");
        return false;
      }});
  pats.push_back(Pattern{
      .nodes = {IntSubNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto sub_instr = res.matched_instrs[0];
        auto res_reg =
            valueToArg(fir::ValueR(sub_instr), res.result, data.alloc);
        auto res_ty = convert_type(sub_instr.get_type());
        if (res_ty >= Type::Float32) {
          // int vector add has different 3 oeprand operation
          auto a0 = valueToArg(sub_instr->args[0], res.result, data.alloc);
          auto a1 = valueToArg(sub_instr->args[1], res.result, data.alloc);
          res.result.emplace_back(Opcode::vsub, res_reg, a0, a1);
          return true;
        }
        auto a0 = valueToArg(sub_instr->args[0], res.result, data.alloc);
        if (a0.isImm()) {
          // then we gucci
        } else if (res_reg.ty != a0.ty) {
          auto res_reg = data.alloc.get_new_register(res_ty);
          auto helper_reg1 = MArgument(res_reg, res_ty);
          res.result.emplace_back(Opcode::mov, helper_reg1, a0);
          a0 = helper_reg1;
        }

        auto a1 = valueToArg(sub_instr->args[1], res.result, data.alloc);
        if (a1.isImm()) {
          // then we gucci
        } else if (res_reg.ty != a1.ty) {
          auto res_reg = data.alloc.get_new_register(res_ty);
          auto helper_reg1 = MArgument(res_reg, res_ty);
          res.result.emplace_back(Opcode::mov, helper_reg1, a1);
          a1 = helper_reg1;
        }

        res.result.emplace_back(Opcode::mov, res_reg, a0);
        res.result.emplace_back(Opcode::sub2, res_reg, a1);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {ShlNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto shift_instr = res.matched_instrs[0];
        auto res_reg =
            valueToArg(fir::ValueR(shift_instr), res.result, data.alloc);

        auto a = valueToArg(shift_instr->args[0], res.result, data.alloc);
        auto b = valueToArg(shift_instr->args[1], res.result, data.alloc);

        if (b.isImm()) {
          res.result.emplace_back(Opcode::mov, res_reg, a);
          res.result.emplace_back(Opcode::shl2, res_reg, b);
        } else {
          auto shift_reg = VReg::CL();
          auto shift_reg_arg = MArgument(shift_reg, Type::Int8);
          if (b.ty == Type::Int8) {
            res.result.emplace_back(Opcode::mov, shift_reg_arg, b);
          } else {
            res.result.emplace_back(Opcode::itrunc, shift_reg_arg, b);
          }
          res.result.emplace_back(Opcode::mov, res_reg, a);
          res.result.emplace_back(Opcode::shl2, res_reg, shift_reg_arg);
        }
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {ShrNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto shift_instr = res.matched_instrs[0];
        auto res_reg =
            valueToArg(fir::ValueR(shift_instr), res.result, data.alloc);

        auto a = valueToArg(shift_instr->args[0], res.result, data.alloc);
        auto b = valueToArg(shift_instr->args[1], res.result, data.alloc);

        if (b.isImm()) {
          res.result.emplace_back(Opcode::mov, res_reg, a);
          res.result.emplace_back(Opcode::shr2, res_reg, b);
        } else {
          auto shift_reg = VReg::CL();
          auto shift_reg_arg = MArgument(shift_reg, Type::Int8);
          if (b.ty == Type::Int8) {
            res.result.emplace_back(Opcode::mov, shift_reg_arg, b);
          } else {
            res.result.emplace_back(Opcode::itrunc, shift_reg_arg, b);
          }
          res.result.emplace_back(Opcode::mov, res_reg, a);
          res.result.emplace_back(Opcode::shr2, res_reg, shift_reg_arg);
        }
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {AShrNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto shift_instr = res.matched_instrs[0];
        auto res_reg =
            valueToArg(fir::ValueR(shift_instr), res.result, data.alloc);

        auto a = valueToArg(shift_instr->args[0], res.result, data.alloc);
        auto b = valueToArg(shift_instr->args[1], res.result, data.alloc);

        if (b.isImm()) {
          res.result.emplace_back(Opcode::mov, res_reg, a);
          res.result.emplace_back(Opcode::sar2, res_reg, b);
        } else {
          auto shift_reg = VReg::CL();
          auto shift_reg_arg = MArgument(shift_reg, Type::Int8);
          if (b.ty == Type::Int8) {
            res.result.emplace_back(Opcode::mov, shift_reg_arg, b);
          } else {
            res.result.emplace_back(Opcode::itrunc, shift_reg_arg, b);
          }
          res.result.emplace_back(Opcode::mov, res_reg, a);
          res.result.emplace_back(Opcode::sar2, res_reg, shift_reg_arg);
        }
        return true;
      }});
  pats.push_back(
      Pattern{.nodes = {IntMulNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                auto add_instr = res.matched_instrs[0];
                auto res_reg =
                    valueToArg(fir::ValueR(add_instr), res.result, data.alloc);

                res.result.emplace_back(
                    Opcode::mov, res_reg,
                    valueToArg(add_instr->args[0], res.result, data.alloc));
                res.result.emplace_back(
                    Opcode::mul2, res_reg,
                    valueToArg(add_instr->args[1], res.result, data.alloc));
                return true;
              }});
  pats.push_back(
      Pattern{.nodes = {OrNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                auto or_instr = res.matched_instrs[0];
                auto res_reg =
                    valueToArg(fir::ValueR(or_instr), res.result, data.alloc);

                if (res_reg.is_fp()) {
                  res.result.emplace_back(
                      Opcode::fOr, res_reg,
                      valueToArg(or_instr->args[0], res.result, data.alloc),
                      valueToArg(or_instr->args[1], res.result, data.alloc));
                } else {
                  res.result.emplace_back(
                      Opcode::mov, res_reg,
                      valueToArg(or_instr->args[0], res.result, data.alloc));
                  res.result.emplace_back(
                      Opcode::lor2, res_reg,
                      valueToArg(or_instr->args[1], res.result, data.alloc));
                }
                return true;
              }});
  pats.push_back(
      Pattern{.nodes = {AndNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                auto and_instr = res.matched_instrs[0];
                auto res_reg =
                    valueToArg(fir::ValueR(and_instr), res.result, data.alloc);

                if (res_reg.is_fp()) {
                  res.result.emplace_back(
                      Opcode::fAnd, res_reg,
                      valueToArg(and_instr->args[0], res.result, data.alloc),
                      valueToArg(and_instr->args[1], res.result, data.alloc));
                } else {
                  res.result.emplace_back(
                      Opcode::mov, res_reg,
                      valueToArg(and_instr->args[0], res.result, data.alloc));
                  res.result.emplace_back(
                      Opcode::land2, res_reg,

                      valueToArg(and_instr->args[1], res.result, data.alloc));
                }
                return true;
              }});
  pats.push_back(
      Pattern{.nodes = {XorNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                auto xor_instr = res.matched_instrs[0];
                auto res_reg =
                    valueToArg(fir::ValueR(xor_instr), res.result, data.alloc);

                if (res_reg.is_fp()) {
                  res.result.emplace_back(
                      Opcode::fxor, res_reg,
                      valueToArg(xor_instr->args[0], res.result, data.alloc),
                      valueToArg(xor_instr->args[1], res.result, data.alloc));
                } else {
                  res.result.emplace_back(
                      Opcode::mov, res_reg,
                      valueToArg(xor_instr->args[0], res.result, data.alloc));
                  res.result.emplace_back(
                      Opcode::lxor2, res_reg,
                      valueToArg(xor_instr->args[1], res.result, data.alloc));
                }
                return true;
              }});
  pats.push_back(
      Pattern{.nodes = {SRemNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                auto srem_instr = res.matched_instrs[0];
                // FIXME: variable size
                auto res_div = VReg::EAX();
                auto res_rem = VReg::EDX();
                auto res_reg =
                    valueToArg(fir::ValueR(srem_instr), res.result, data.alloc);
                auto res_div_arg =
                    MArgument(res_div, convert_type(srem_instr.get_type()));
                auto res_rem_arg =
                    MArgument(res_rem, convert_type(srem_instr.get_type()));

                res.result.emplace_back(
                    Opcode::idiv, res_div_arg, res_rem_arg,
                    valueToArg(srem_instr->args[0], res.result, data.alloc),
                    valueToArg(srem_instr->args[1], res.result, data.alloc));
                res.result.emplace_back(Opcode::mov, res_reg, res_rem_arg);
                return true;
              }});
  pats.push_back(
      Pattern{.nodes = {SDivNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                auto sdiv_instr = res.matched_instrs[0];
                // FIXME: variable size
                auto res_div = VReg::EAX();
                auto res_rem = VReg::EDX();
                auto res_reg =
                    valueToArg(fir::ValueR(sdiv_instr), res.result, data.alloc);
                auto res_div_arg =
                    MArgument(res_div, convert_type(sdiv_instr.get_type()));
                auto res_rem_arg =
                    MArgument(res_rem, convert_type(sdiv_instr.get_type()));

                res.result.emplace_back(
                    Opcode::idiv, res_div_arg, res_rem_arg,
                    valueToArg(sdiv_instr->args[0], res.result, data.alloc),
                    valueToArg(sdiv_instr->args[1], res.result, data.alloc));
                res.result.emplace_back(Opcode::mov, res_reg, res_div_arg);
                return true;
              }});
  pats.push_back(
      Pattern{.nodes = {UDivNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                auto sdiv_instr = res.matched_instrs[0];
                // FIXME: variable size
                auto res_div = VReg::EAX();
                auto res_rem = VReg::EDX();
                auto res_reg =
                    valueToArg(fir::ValueR(sdiv_instr), res.result, data.alloc);
                auto res_div_arg =
                    MArgument(res_div, convert_type(sdiv_instr.get_type()));
                auto res_rem_arg =
                    MArgument(res_rem, convert_type(sdiv_instr.get_type()));

                res.result.emplace_back(
                    Opcode::udiv, res_div_arg, res_rem_arg,
                    valueToArg(sdiv_instr->args[0], res.result, data.alloc),
                    valueToArg(sdiv_instr->args[1], res.result, data.alloc));
                res.result.emplace_back(Opcode::mov, res_reg, res_div_arg);
                return true;
              }});
  pats.push_back(Pattern{
      .nodes = {FCMPNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto cmp_instr = res.matched_instrs[0];
        auto res_reg = data.alloc.get_register(fir::ValueR(cmp_instr));

        auto res_arg = MArgument(res_reg, convert_type(cmp_instr.get_type()));

        auto arg1 = valueToArg(cmp_instr->args[0], res.result, data.alloc);
        auto arg2 = valueToArg(cmp_instr->args[1], res.result, data.alloc);

        Opcode op = Opcode::fcmp_oeq;

        switch ((fir::FCmpInstrSubType)cmp_instr->get_instr_subtype()) {
        case fir::FCmpInstrSubType::IsNaN:
          op = Opcode::fcmp_isNaN;
          break;
        case fir::FCmpInstrSubType::OEQ:
          op = Opcode::fcmp_oeq;
          break;
        case fir::FCmpInstrSubType::OGT:
          op = Opcode::fcmp_ogt;
          break;
        case fir::FCmpInstrSubType::OGE:
          op = Opcode::fcmp_oge;
          break;
        case fir::FCmpInstrSubType::OLT:
          op = Opcode::fcmp_olt;
          break;
        case fir::FCmpInstrSubType::OLE:
          op = Opcode::fcmp_ole;
          break;
        case fir::FCmpInstrSubType::ONE:
          op = Opcode::fcmp_one;
          break;
        case fir::FCmpInstrSubType::ORD:
          op = Opcode::fcmp_ord;
          break;
        case fir::FCmpInstrSubType::UNO:
          op = Opcode::fcmp_uno;
          break;
        case fir::FCmpInstrSubType::UEQ:
          op = Opcode::fcmp_ueq;
          break;
        case fir::FCmpInstrSubType::UGT:
          op = Opcode::fcmp_ugt;
          break;
        case fir::FCmpInstrSubType::UGE:
          op = Opcode::fcmp_uge;
          break;
        case fir::FCmpInstrSubType::ULT:
          op = Opcode::fcmp_ult;
          break;
        case fir::FCmpInstrSubType::ULE:
          op = Opcode::fcmp_ule;
          break;
        case fir::FCmpInstrSubType::UNE:
          op = Opcode::fcmp_une;
          break;
        case fir::FCmpInstrSubType::INVALID:
        case fir::FCmpInstrSubType::AlwFalse:
        case fir::FCmpInstrSubType::AlwTrue:
          IMPL("");
          break;
        }
        res.result.emplace_back(op, res_arg, arg1, arg2);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {ICMPNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto cmp_instr = res.matched_instrs[0];
        // TODO: kinda sus
        auto res_reg = data.alloc.get_register(fir::ValueR(cmp_instr));

        auto res_arg = MArgument(res_reg, convert_type(cmp_instr.get_type()));

        auto arg1 = valueToArg(cmp_instr->args[0], res.result, data.alloc);
        auto arg2 = valueToArg(cmp_instr->args[1], res.result, data.alloc);

        Opcode op = Opcode::icmp_eq;

        switch ((fir::ICmpInstrSubType)cmp_instr->get_instr_subtype()) {
        case fir::ICmpInstrSubType::SLT:
          op = Opcode::icmp_slt;
          break;
        case fir::ICmpInstrSubType::ULT:
          op = Opcode::icmp_ult;
          break;
        case fir::ICmpInstrSubType::NE:
          op = Opcode::icmp_ne;
          break;
        case fir::ICmpInstrSubType::EQ:
          op = Opcode::icmp_eq;
          break;
        case fir::ICmpInstrSubType::SGT:
          op = Opcode::icmp_sgt;
          break;
        case fir::ICmpInstrSubType::UGT:
          op = Opcode::icmp_ugt;
          break;
        case fir::ICmpInstrSubType::UGE:
          op = Opcode::icmp_uge;
          break;
        case fir::ICmpInstrSubType::ULE:
          op = Opcode::icmp_ule;
          break;
        case fir::ICmpInstrSubType::SGE:
          op = Opcode::icmp_sge;
          break;
        case fir::ICmpInstrSubType::SLE:
          op = Opcode::icmp_sle;
          break;
        case fir::ICmpInstrSubType::MulOverflow:
          op = Opcode::icmp_mul_overflow;
          break;
        case fir::ICmpInstrSubType::AddOverflow:
          op = Opcode::icmp_add_overflow;
          break;
        case fir::ICmpInstrSubType::INVALID:
          UNREACH();
        }
        res.result.emplace_back(op, res_arg, arg1, arg2);
        return true;
      }});
  pats.push_back(
      Pattern{.nodes = {BranchNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                auto branch_instr = res.matched_instrs[0];
                auto bb_with_args = branch_instr->bbs[0];
                auto target_bb = branch_instr->bbs[0].bb;
                ASSERT(bb_with_args.args.size() == target_bb->args.size());
                generate_bb_args(bb_with_args, res, data);
                res.result.push_back(MInstr::jmp(data.bbs[bb_with_args.bb]));
                return true;
              }});
  pats.push_back(Pattern{
      .nodes = {CondBranchNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto branch_instr = res.matched_instrs[0];
        auto cond = valueToArg(branch_instr->args[0], res.result, data.alloc);
        {
          auto &bb_with_args = branch_instr->bbs[0];
          auto target_bb = branch_instr->bbs[0].bb;
          ASSERT(bb_with_args.args.size() == target_bb->args.size());
          generate_bb_args(bb_with_args, res, data);
          res.result.push_back(MInstr::cJmp(cond, data.bbs[bb_with_args.bb]));
        }

        {
          auto &bb2_with_args = branch_instr->bbs[1];
          auto target_bb2 = branch_instr->bbs[1].bb;
          ASSERT(bb2_with_args.args.size() == target_bb2->args.size());
          generate_bb_args(bb2_with_args, res, data);
          res.result.push_back(MInstr::jmp(data.bbs[bb2_with_args.bb]));
        }
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {SwitchNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto branch_instr = res.matched_instrs[0];
        auto value =
            valueToArg(branch_instr->args.back(), res.result, data.alloc);
        for (size_t instr_id = 0; instr_id < branch_instr->args.size() - 1;
             instr_id++) {
          auto &bb_with_args = branch_instr->bbs[instr_id];
          auto target_bb = branch_instr->bbs[instr_id].bb;
          ASSERT(bb_with_args.args.size() == target_bb->args.size());
          generate_bb_args(bb_with_args, res, data);
          auto cond_val =
              valueToArg(branch_instr->args[instr_id], res.result, data.alloc);
          res.result.push_back(
              MInstr::cJmp_eq(value, cond_val, data.bbs[bb_with_args.bb]));
        }
        {
          size_t instr_id = branch_instr->args.size() - 1;
          auto &bb_with_args = branch_instr->bbs[instr_id];
          auto target_bb = branch_instr->bbs[instr_id].bb;
          ASSERT(bb_with_args.args.size() == target_bb->args.size());
          generate_bb_args(bb_with_args, res, data);
          // auto cond_val =
          //     valueToArg(branch_instr->args[instr_id], res.result,
          //     data.alloc);
          // res.result.push_back(
          //     MInstr::cJmp_eq(value, cond_val, data.bbs[bb_with_args.bb]));
          res.result.push_back(MInstr::jmp(data.bbs[bb_with_args.bb]));
        }
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {ReturnNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto ret_instr = res.matched_instrs[0];
        if (data.static_alloca_size > 0) {
          if (data.static_alloca_size < 255) {
            res.result.emplace_back(Opcode::add2,
                                    MArgument(VReg::RSP(), Type::Int64),
                                    MArgument((u8)data.static_alloca_size));
          } else {
            res.result.emplace_back(Opcode::add2,
                                    MArgument(VReg::RSP(), Type::Int64),
                                    MArgument(data.static_alloca_size));
          }
        }
        if (ret_instr->has_args()) {
          auto ret_val = valueToArg(ret_instr->args[0], res.result, data.alloc);
          auto is_float_val = ret_val.is_fp();

          if (!is_float_val &&
              (!ret_val.isReg() || !ret_val.reg.is_concrete() ||
               ret_val.reg.c_reg() != CReg::A)) {
            auto converted_type = convert_type(ret_instr.get_type());
            auto res_reg = VReg{CReg::A, converted_type};
            auto res_arg = MArgument(res_reg, converted_type);
            res.result.emplace_back(Opcode::mov, res_arg, ret_val);
            res.result.emplace_back(Opcode::ret, res_arg);
          } else if (is_float_val &&
                     (!ret_val.isReg() || !ret_val.reg.is_concrete() ||
                      ret_val.reg.c_reg() != CReg::mm0)) {
            auto converted_type = convert_type(ret_instr.get_type());
            auto res_reg = VReg{CReg::mm0, converted_type};
            auto res_arg = MArgument(res_reg, converted_type);
            res.result.emplace_back(Opcode::mov, res_arg, ret_val);
            res.result.emplace_back(Opcode::ret, res_arg);
          } else {
            res.result.emplace_back(Opcode::ret, ret_val);
          }
        } else {
          res.result.emplace_back(Opcode::ret);
        }
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {SExtNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto sext_instr = res.matched_instrs[0];
        auto val = valueToArg(sext_instr->args[0], res.result, data.alloc);
        auto res_reg =
            valueToArg(fir::ValueR(sext_instr), res.result, data.alloc);

        res.result.emplace_back(Opcode::mov_sx, res_reg, val);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {ZExtNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto zext_instr = res.matched_instrs[0];
        auto val = valueToArg(zext_instr->args[0], res.result, data.alloc);
        auto res_reg =
            valueToArg(fir::ValueR(zext_instr), res.result, data.alloc);

        res.result.emplace_back(Opcode::mov_zx, res_reg, val);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {ConversionNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto conversion_instr = res.matched_instrs[0];
        auto val =
            valueToArg(conversion_instr->args[0], res.result, data.alloc);
        auto res_reg =
            valueToArg(fir::ValueR(conversion_instr), res.result, data.alloc);
        auto res_opcode = Opcode::FL2SI;
        switch ((fir::ConversionSubType)conversion_instr->subtype) {
        case fir::ConversionSubType::INVALID:
          UNREACH();
        case fir::ConversionSubType::FPTOUI:
          res_opcode = Opcode::FL2UI;
          break;
        case fir::ConversionSubType::FPTOSI:
          res_opcode = Opcode::FL2SI;
          break;
        case fir::ConversionSubType::UITOFP:
          res_opcode = Opcode::UI2FL;
          break;
        case fir::ConversionSubType::SITOFP:
          res_opcode = Opcode::SI2FL;
          break;
        case fir::ConversionSubType::PtrToInt:
        case fir::ConversionSubType::IntToPtr:
          res_opcode = Opcode::mov;
          break;
        case fir::ConversionSubType::FPEXT:
          res_opcode = Opcode::F64_ext;
          break;
        case fir::ConversionSubType::FPTRUNC:
          res_opcode = Opcode::F32_trunc;
          break;
        }

        res.result.emplace_back(res_opcode, res_reg, val);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {ITruncNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto itrunc_instr = res.matched_instrs[0];
        auto val = valueToArg(itrunc_instr->args[0], res.result, data.alloc);
        auto res_reg =
            valueToArg(fir::ValueR(itrunc_instr), res.result, data.alloc);
        res.result.emplace_back(Opcode::itrunc, res_reg, val);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {CallNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto call_instr = res.matched_instrs[0];
        setup_callargs(call_instr, res, data);

        MArgument calee;
        bool is_var_arg = false;
        if (call_instr->args[0].is_constant()) {
          calee = valueToArgPtr(call_instr->args[0], Type::Int64, data.alloc);
          is_var_arg = call_instr->args[0].as_constant()->as_func()->variadic;
        } else {
          calee = valueToArg(call_instr->args[0], res.result, data.alloc);
        }

        auto res_type = call_instr.get_type();
        if (res_type->is_void() || call_instr->get_n_uses() == 0) {
          res.result.emplace_back(Opcode::invoke, calee);
          res.result.back().is_var_arg_call = is_var_arg;
          return true;
        }
        if (res_type->is_int() || res_type->is_ptr()) {
          auto res_reg =
              valueToArg(fir::ValueR(call_instr), res.result, data.alloc);
          if (get_size(res_reg.ty) == 8) {
            auto ax_reg = VReg::RAX();
            auto ax_arg = MArgument{ax_reg, res_reg.ty};
            res.result.emplace_back(Opcode::invoke, calee, ax_arg);
            res.result.back().is_var_arg_call = is_var_arg;
            res.result.emplace_back(Opcode::mov, res_reg, ax_arg);
          } else if (get_size(res_reg.ty) <= 4) {
            auto ax_reg = VReg::EAX();
            auto ax_arg = MArgument{ax_reg, res_reg.ty};
            res.result.emplace_back(Opcode::invoke, calee, ax_arg);
            res.result.back().is_var_arg_call = is_var_arg;
            res.result.emplace_back(Opcode::mov, res_reg, ax_arg);
          } else {
            res.result.emplace_back(Opcode::invoke, calee, res_reg);
            res.result.back().is_var_arg_call = is_var_arg;
          }
          return true;
        }
        if (res_type->is_float()) {
          auto res_reg =
              valueToArg(fir::ValueR(call_instr), res.result, data.alloc);
          res.result.emplace_back(Opcode::invoke, calee, res_reg);
          res.result.back().is_var_arg_call = is_var_arg;
          return true;
        }
        TODO("impl ret value");
      }});
  pats.push_back(Pattern{
      .nodes = {FloatAddNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto f_add_instr = res.matched_instrs[0];
        auto a1 = valueToArg(f_add_instr->args[0], res.result, data.alloc);
        auto a2 = valueToArg(f_add_instr->args[1], res.result, data.alloc);
        auto res_reg =
            valueToArg(fir::ValueR(f_add_instr), res.result, data.alloc);

        res.result.emplace_back(Opcode::vadd, res_reg, a1, a2);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {FloatNegNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto f_neg_instr = res.matched_instrs[0];
        auto a1 = valueToArg(f_neg_instr->args[0], res.result, data.alloc);
        auto res_reg =
            valueToArg(fir::ValueR(f_neg_instr), res.result, data.alloc);

        MArgument a2;
        if (res_reg.ty == Type::Float64) {
          u64 val = 0x8000000000000000UL;
          f64 v;
          std::memcpy(&v, &val, sizeof(f64));
          a2 = MArgument{v};
        } else {
          u32 val = 0x80000000ULL;
          f32 v;
          std::memcpy(&v, &val, sizeof(f32));
          a2 = MArgument{v};
        }
        res.result.emplace_back(Opcode::fxor, res_reg, a1, a2);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {FloatSubNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto f_sub_instr = res.matched_instrs[0];
        auto a1 = valueToArg(f_sub_instr->args[0], res.result, data.alloc);
        auto a2 = valueToArg(f_sub_instr->args[1], res.result, data.alloc);
        auto res_reg =
            valueToArg(fir::ValueR(f_sub_instr), res.result, data.alloc);

        res.result.emplace_back(Opcode::vsub, res_reg, a1, a2);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {FloatMulNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto f_mul_instr = res.matched_instrs[0];
        auto a1 = valueToArg(f_mul_instr->args[0], res.result, data.alloc);
        auto a2 = valueToArg(f_mul_instr->args[1], res.result, data.alloc);
        auto res_reg =
            valueToArg(fir::ValueR(f_mul_instr), res.result, data.alloc);

        res.result.emplace_back(Opcode::fmul, res_reg, a1, a2);
        return true;
      }});
  pats.push_back(Pattern{
      .nodes = {FloatDivNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto f_mul_instr = res.matched_instrs[0];
        auto a1 = valueToArg(f_mul_instr->args[0], res.result, data.alloc);
        auto a2 = valueToArg(f_mul_instr->args[1], res.result, data.alloc);
        auto res_reg =
            valueToArg(fir::ValueR(f_mul_instr), res.result, data.alloc);

        res.result.emplace_back(Opcode::fdiv, res_reg, a1, a2);
        return true;
      }});
  pats.push_back(
      Pattern{.nodes = {UnreachNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                (void)data;
                (void)res;
                // TODO: prob nicer way to handle this
                res.result.emplace_back(Opcode::ret);
                return true;
              }});
}
void intrin_patterns(IRVec<Pattern> &pats) {
  using Node = Pattern::Node;
  using InstrType = fir::InstrType;
  using NodeType = Pattern::NodeType;

  auto ctlzNode = Node{NodeType::Instr, InstrType::Intrinsic,
                       (u32)fir::IntrinsicSubType::CTLZ};
  auto va_endNode = Node{NodeType::Instr, InstrType::Intrinsic,
                         (u32)fir::IntrinsicSubType::VA_end};
  auto va_startNode = Node{NodeType::Instr, InstrType::Intrinsic,
                           (u32)fir::IntrinsicSubType::VA_start};

  pats.push_back(Pattern{
      .nodes = {ctlzNode},
      .edges = {},
      .generator = [](MatchResult &res, ExtraMatchData &data) {
        auto instr = res.matched_instrs[0];
        auto res_reg = valueToArg(fir::ValueR(instr), res.result, data.alloc);
        auto arg = valueToArg(instr->args[0], res.result, data.alloc);
        res.result.emplace_back(Opcode::lzcnt, res_reg, arg);
        return true;
      }});
  pats.push_back(
      Pattern{.nodes = {va_startNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                setup_va_start(res.matched_instrs[0], res, data);
                return true;
              }});
  pats.push_back(
      Pattern{.nodes = {va_endNode},
              .edges = {},
              .generator = [](MatchResult &res, ExtraMatchData &data) {
                setup_va_end(res.matched_instrs[0], res, data);
                return true;
              }});
}
} // namespace foptim::fmir
