config_version = 1

# ------------------------------------------------------------------------------------------------
# Target setup

[target]
name = "x86_64-linux"

[target.features]
avx512f = false
avx512bw = false
avx512cd = false
avx512dq = false
avx512vl = false
bmi2 = true

# ------------------------------------------------------------------------------------------------
# Optimizations

[optimize]
fir_pipeline = "default_release"
mir_pipeline = "default_release"
# makes everything interal if possible
all_linkage_internal = false
# assumes that calls to functions named like strlen and other cstdlib function
# beheave like in the cstdlib
assume_cstdlib_beheaviour = true

[optimize.float]
no_nans = false
no_infinites = false
associative_math = false
reciprocal_math = false
no_signed_zeros = false
no_math_errno = false
no_trapping_math = false
#equiv of fno-rounding-math
no_rounding_mode = false
#equiv to ffp-contract=fast
fast_contract = false
#equiv to fapprox-func
approx_func = false

# ------------------------------------------------------------------------------------------------
# FIR Pipeline

[pipeline.fir.default_release_early]
passes = [
        "DCE", "LegalizeStructs", "LLVMIntrinsicLowering", "SORA", "Mem2Reg", "DoubleLoadElim",
        "DCE", "IntrinSimplify", "InstSimplify", "DCE", "SimplifyCFG", "LVN", "DCE",
        "FuncPropAnnotator", "GlobalPromotion", "ArgPromotion", "GDCE"
]

[pipeline.fir.default_release_middle]
passes = [
      "DCE", "CmpKnownValProp", "SimplifyCFG", "TailRecElim", "LICM", "LoopRotate",
      "LoopSimplify", "DCE", "LVN", "SCCP", "IntrinSimplify", "InstSimplify",
      "DoubleLoadElim", "DCE", "SimplifyCFG", "StackKnownBits", "SORA", "Mem2Reg",
      "SimplifyCFG", "DCE", "LVN", "InstSimplify", "ConstLoopEval", "LoopSimplify",
      "InstSimplify", "SimplifyCFG", "FuncPropAnnotator", "IPCP", "GlobalPromotion", "Inline", "Inline", "Inline",
      "ArgPromotion", "GDCE", "FunctionDedupSame", "GDCE", "FuncPropAnnotator", "SimplifyCFG", "CmpKnownValProp",
      "InstSimplify", "SimplifyCFG", "LICM", "DCE", "LoopSimplify", "LoopUnswitch", "LoopUnroll", "SimplifyCFG", "DCE", "SLPVectorizer",
      "LVN", "SCCP", "IntrinSimplify", "InstSimplify", "ConstLoopEval", "InstSimplify",
      "CmpKnownValProp", "SimplifyCFG", "DCE","FuncPropAnnotator", "IPCP", "GlobalPromotion", "Inline", "Inline", "Inline",
      "ArgPromotion", "FunctionDedupSame", "GDCE", "FuncPropAnnotator", "SimplifyCFG", "InstSimplify",
      "SimplifyCFG", "TailRecElim", "SimplifyCFG", "DCE", "LoopSimplify", "LoopUnswitch", "IntrinSimplify", "InstSimplify", "DCE",
      "StackKnownBits", "SORA", "Mem2Reg", "SimplifyCFG", "DCE",
]

[pipeline.fir.default_release_late]
passes = [
      "ArgPromotion", "FuncPropAnnotator", "FunctionDedupDiff", "GDCE", "IPCP",
      "GlobalPromotion", "Inline", "Inline", "GDCE", "FuncPropAnnotator",
      "LVN", "SCCP", "DoubleLoadElim", "DCE", "IntrinSimplify", "InstSimplify",
      "CmpKnownValProp", "SimplifyCFG", "SCCP",
      "ArgPromotion", "FuncPropAnnotator", "FunctionDedupDiff", "Inline", "Inline",
      "Inline", "GDCE", "IPCP", "FuncPropAnnotator",
      "SimplifyCFG", "LVN", "SCCP", "DoubleLoadElim", "DCE", "IntrinSimplify", "SimplifyCFG",
      "InstSimplify", "SCCP", "DCE", "InstSimplify", "ConstLoopEval", "LoopSimplify",
      "LoopUnswitch", "LoopUnroll", "SimplifyCFG", "DCE", "SLPVectorizer", "InstSimplify",
      "SimplifyCFG",
      "ArgPromotion", "FuncPropAnnotator", "FunctionDedupDiff", "Inline", "Inline",
      "GDCE", "IPCP", "FuncPropAnnotator",
      "SimplifyCFG", "LVN", "SCCP", "DCE", "IntrinSimplify", "InstSimplify", "DCE",
      "SLPVectorizer", "InstSimplify", "SimplifyCFG",
      "LegalizeVecs", "SCCP", "LVN", "InstSimplify", "DCE", "LVN", "InstSimplify", "DCE",  
]

[pipeline.fir.default_release_cleanup]
passes = [
  "MergeAlloca", "LVN", "InstSimplify", "SCCP", "DCE", "LVN",
  "InstSimplify", "SimplifyCFG", "DCE", "LegalizeVecs", "InstSimplify",
  "SCCP", "LegalizeVecs", "DCE",
]

[pipeline.fir.default_release]
passes = [
  "pipeline:default_release_early",
  "pipeline:default_release_middle",
  "pipeline:default_release_late",
  "pipeline:default_release_cleanup",
]

# ------------------------------------------------------------------------------------------------
# FIR Passes

#module
[pass.fir.Inline]
recursive = true
[pass.fir.LoopUnroll]
maxUnroll = 32
maxInstr = 32
[pass.fir.FuncPropAnnotator]
[pass.fir.GlobalPromotion]
[pass.fir.ArgPromotion]
[pass.fir.GDCE]
[pass.fir.IPCP]
[pass.fir.FunctionDedupSame]
[pass.fir.FunctionDedupDiff]
[pass.fir.LoopUnswitch]
# [pass.PrintModule]
# [pass.VerifyModule]

#func
[pass.fir.SLPVectorizer]
reductions = true
[pass.fir.DCE]
[pass.fir.LegalizeStructs]
[pass.fir.LLVMIntrinsicLowering]
[pass.fir.SORA]
[pass.fir.Mem2Reg]
[pass.fir.DoubleLoadElim]
[pass.fir.IntrinSimplify]
[pass.fir.InstSimplify]
[pass.fir.SimplifyCFG]
[pass.fir.LVN]
[pass.fir.CmpKnownValProp]
[pass.fir.TailRecElim]
[pass.fir.LICM]
[pass.fir.LoopRotate]
[pass.fir.LoopSimplify]
[pass.fir.SCCP]
[pass.fir.StackKnownBits]
[pass.fir.ConstLoopEval]
[pass.fir.MergeAlloca]
[pass.fir.LegalizeVecs]
[pass.fir.PrintFunc]
[pass.fir.VerifyFunc]


# ------------------------------------------------------------------------------------------------
# MIR Pipeline
[pipeline.mir.default_release_early]
passes = [
  "LegalizeBBForm",
  "DCE",
  "CopyPropagation",
  "DCE",
]

[pipeline.mir.default_release_middle]
passes = [
  "LVN",
  "BBReordering",
  "CopyPropagation",
  "LVN",
  "DCE",
  "InstSimplifyEarly",
  "LifetimeShortening",
  "CopyPropagation",
  "InstSimplifyEarly",
  "DCE",
]

[pipeline.mir.default_release_CC1]
passes = [
  "CallingConv_FirstStage",
  "Legalizer",
  "InstSimplifyEarly",
  "RegisterJoining",
  "InstSimplifyEarly",
]

[pipeline.mir.default_release_RegAlloc]
passes = [
  "RegAlloc",
]

[pipeline.mir.default_release_CC2]
passes = [
  "CallingConv_SecondStage",
]

[pipeline.mir.default_release_Cleanup]
passes = [
  "StackSlotLowering",
  "StackOptim",
  "InstSimplify",
  "InstSimplify",
  "BBReordering",
]

[pipeline.mir.default_release]
passes = [
 "pipeline:default_release_early",
 "pipeline:default_release_middle",
 "pipeline:default_release_CC1",
 "pipeline:default_release_RegAlloc",
 "pipeline:default_release_CC2",
 "pipeline:default_release_Cleanup",
]

# ------------------------------------------------------------------------------------------------
# MIR Passes

# func
[pass.mir.LegalizeBBForm]
[pass.mir.DCE]
[pass.mir.CopyPropagation]
[pass.mir.BBReordering]
[pass.mir.LVN]
[pass.mir.InstSimplifyEarly]
[pass.mir.InstSimplify]
[pass.mir.LifetimeShortening]
[pass.mir.CallingConv_FirstStage]
[pass.mir.Legalizer]
[pass.mir.RegisterJoining]
[pass.mir.RegAlloc]
[pass.mir.CallingConv_SecondStage]
[pass.mir.StackSlotLowering]
[pass.mir.StackOptim]


# ------------------------------------------------------------------------------------------------
# Debug

[debug]
print_between_passes = false
print_optimization_failure_reasons = true
print_color = true
verify_between_passes = false
bisect = 0

