; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Values that live across a call can not stay in caller saved registers.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

declare void @sink(i64)

define i64 @keep_alive(i64 %a, i64 %b) {
; CHECK: func keep_alive ($2: i64, $3: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    push($rsi: i64, )
; CHECK-NEXT:    push($rdi: i64, )
; CHECK-NEXT:    call(sink, )
; CHECK-NEXT:    pop($rdi: i64, )
; CHECK-NEXT:    pop($rsi: i64, )
; CHECK-NEXT:    $rdi: i64 += $rsi: i64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    ret($rax: i64, )
  call void @sink(i64 %a)
  %r = add i64 %a, %b
  ret i64 %r
}

define double @keep_alive_float(double %a, double %b) {
; CHECK: func keep_alive_float ($2: f64, $3: f64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    push($mm0: f64, )
; CHECK-NEXT:    push($mm1: f64, )
; CHECK-NEXT:    clear $rdi: i64
; CHECK-NEXT:    call(sink, )
; CHECK-NEXT:    pop($mm1: f64, )
; CHECK-NEXT:    pop($mm0: f64, )
; CHECK-NEXT:    $mm0: f64 = $mm0: f64 + $mm1: f64
; CHECK-NEXT:    ret($mm0: f64, )
  call void @sink(i64 0)
  %r = fadd double %a, %b
  ret double %r
}

; The call runs every iteration so the values that live across it belong into
; callee saved registers (saved once in the prologue) and not into registers
; that have to be pushed and popped around the call on every iteration.
define i64 @call_in_loop(i64 %n, i64 %a, i64 %b) {
; CHECK: func call_in_loop ($2: i64, $3: i64, $4: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r15: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $r15: i64 = $rdx: i64
; CHECK-NEXT:    $r14: i64 = $rsi: i64
; CHECK-NEXT:    $r13: i64 = $rdi: i64
; CHECK-NEXT:    clear $r12: i64
; CHECK-NEXT:    clear $rbx: i64
; CHECK-NEXT:    jmp() -> 1
; CHECK-NEXT:  1:
; CHECK-NEXT:    $rdi: i64 = $r12: i64
; CHECK-NEXT:    call(sink, )
; CHECK-NEXT:    $rbx: i64 += $r14: i64
; CHECK-NEXT:    $rbx: i64 ^= $r15: i64
; CHECK-NEXT:    $r12: i64 += 1: i64
; CHECK-NEXT:    cjmp_int_eq($r12: i64, $r13: i64, ) -> 3
; CHECK-NEXT:    jmp() -> 2
; CHECK-NEXT:  2:
; CHECK-NEXT:    jmp() -> 1
; CHECK-NEXT:  3:
; CHECK-NEXT:    $rax: i64 = $rbx: i64
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($r15: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %s = phi i64 [ 0, %entry ], [ %s.next, %loop ]
  call void @sink(i64 %i)
  %t = add i64 %s, %a
  %s.next = xor i64 %t, %b
  %i.next = add i64 %i, 1
  %done = icmp eq i64 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret i64 %s.next
}
