; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Moves between a value and a fixed register (argument passing, return value)
; make the allocator prefer that register so the move turns into a no-op.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

define i64 @passthrough(i64 %a, i64 %b) {
; CHECK: func passthrough ($2: i64, $3: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += $rsi: i64
; CHECK-NEXT:    ret($rax: i64, )
  %r = add i64 %a, %b
  ret i64 %r
}

define i64 @forward_args(i64 %a, i64 %b) {
; CHECK: func forward_args ($2: i64, $3: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    call(callee, )
; CHECK-NEXT:    ret($rax: i64, )
  %r = call i64 @callee(i64 %a, i64 %b)
  ret i64 %r
}

declare i64 @callee(i64, i64)
