; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Integer and floating point values live at the same time are allocated from
; different register files, one kind of pressure must not spill the other.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

define double @int_and_float(ptr %pi, ptr %pf) {
; CHECK: func int_and_float ($2: i64, $3: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rcx: i64 = $rsi: i64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rax: i64 += 8: i64
; CHECK-NEXT:    $xmm0: f64x2 = [$rcx]: f64x2
; CHECK-NEXT:    $rdx: i64 = $rdi: i64
; CHECK-NEXT:    $rdx: i64 += 16: i64
; CHECK-NEXT:    $rcx: i64 += 16: i64
; CHECK-NEXT:    HAdd($mm0: f64, $xmm0: f64x2, )
; CHECK-NEXT:    $mm0: f64 = $mm0: f64 + [$rcx]: f64
; CHECK-NEXT:    $rcx: i64 = [$rdi]: i64
; CHECK-NEXT:    $rcx: i64 += [$rax]: i64
; CHECK-NEXT:    $rcx: i64 += [$rdx]: i64
; CHECK-NEXT:    SI2FL($mm1: f64, $rcx: i64, )
; CHECK-NEXT:    $mm0: f64 = $mm0: f64 + $mm1: f64
; CHECK-NEXT:    ret($mm0: f64, )
  %i0 = load volatile i64, ptr %pi
  %f0 = load volatile double, ptr %pf
  %pi1 = getelementptr i64, ptr %pi, i64 1
  %i1 = load volatile i64, ptr %pi1
  %pf1 = getelementptr double, ptr %pf, i64 1
  %f1 = load volatile double, ptr %pf1
  %pi2 = getelementptr i64, ptr %pi, i64 2
  %i2 = load volatile i64, ptr %pi2
  %pf2 = getelementptr double, ptr %pf, i64 2
  %f2 = load volatile double, ptr %pf2
  %fs0 = fadd double %f0, %f1
  %fs1 = fadd double %fs0, %f2
  %is0 = add i64 %i0, %i1
  %is1 = add i64 %is0, %i2
  %conv = sitofp i64 %is1 to double
  %r = fadd double %fs1, %conv
  ret double %r
}
