; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Register pressure that fits into the 14 allocatable GPRs: no value may be
; spilled to the stack. Volatile loads keep every value live until the sums.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

define i64 @live_10(ptr %p) {
; CHECK: func live_10 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $rcx: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 += 8: i64
; CHECK-NEXT:    $rdx: i64 = $rdi: i64
; CHECK-NEXT:    $rdx: i64 += 16: i64
; CHECK-NEXT:    $rsi: i64 = $rdi: i64
; CHECK-NEXT:    $rsi: i64 += 24: i64
; CHECK-NEXT:    $r8: i64 = $rdi: i64
; CHECK-NEXT:    $r8: i64 += 32: i64
; CHECK-NEXT:    $r9: i64 = $rdi: i64
; CHECK-NEXT:    $r9: i64 += 40: i64
; CHECK-NEXT:    $r10: i64 = $rdi: i64
; CHECK-NEXT:    $r10: i64 += 48: i64
; CHECK-NEXT:    $r11: i64 = $rdi: i64
; CHECK-NEXT:    $r11: i64 += 56: i64
; CHECK-NEXT:    $rbx: i64 = $rdi: i64
; CHECK-NEXT:    $rbx: i64 += 64: i64
; CHECK-NEXT:    $r12: i64 = $rdi: i64
; CHECK-NEXT:    $r12: i64 += 72: i64
; CHECK-NEXT:    $rax: i64 = [$rdi]: i64
; CHECK-NEXT:    $rax: i64 += [$rcx]: i64
; CHECK-NEXT:    $rax: i64 += [$rdx]: i64
; CHECK-NEXT:    $rax: i64 += [$rsi]: i64
; CHECK-NEXT:    $rax: i64 += [$r8]: i64
; CHECK-NEXT:    $rax: i64 += [$r9]: i64
; CHECK-NEXT:    $rax: i64 += [$r10]: i64
; CHECK-NEXT:    $rax: i64 += [$r11]: i64
; CHECK-NEXT:    $rax: i64 += [$rbx]: i64
; CHECK-NEXT:    $rax: i64 += [$r12]: i64
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %a0 = load volatile i64, ptr %p
  %p1 = getelementptr i64, ptr %p, i64 1
  %a1 = load volatile i64, ptr %p1
  %p2 = getelementptr i64, ptr %p, i64 2
  %a2 = load volatile i64, ptr %p2
  %p3 = getelementptr i64, ptr %p, i64 3
  %a3 = load volatile i64, ptr %p3
  %p4 = getelementptr i64, ptr %p, i64 4
  %a4 = load volatile i64, ptr %p4
  %p5 = getelementptr i64, ptr %p, i64 5
  %a5 = load volatile i64, ptr %p5
  %p6 = getelementptr i64, ptr %p, i64 6
  %a6 = load volatile i64, ptr %p6
  %p7 = getelementptr i64, ptr %p, i64 7
  %a7 = load volatile i64, ptr %p7
  %p8 = getelementptr i64, ptr %p, i64 8
  %a8 = load volatile i64, ptr %p8
  %p9 = getelementptr i64, ptr %p, i64 9
  %a9 = load volatile i64, ptr %p9
  %s1 = add i64 %a0, %a1
  %s2 = add i64 %s1, %a2
  %s3 = add i64 %s2, %a3
  %s4 = add i64 %s3, %a4
  %s5 = add i64 %s4, %a5
  %s6 = add i64 %s5, %a6
  %s7 = add i64 %s6, %a7
  %s8 = add i64 %s7, %a8
  %s9 = add i64 %s8, %a9
  ret i64 %s9
}
