; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Callee saved registers are only saved in the block that needs them, the early
; exit that does not touch them must not push/pop anything.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

declare i64 @work(i64)

define i64 @early_exit(i64 %a, ptr %p) {
; CHECK: func early_exit ($2: i64, $3: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    cjmp_int_eq($rdi: i64, 0: i64, ) -> 2
; CHECK-NEXT:    jmp() -> 1
; CHECK-NEXT:  1:
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    $rbx: i64 = [$rsi]: i64
; CHECK-NEXT:    $rsp: i64 -= 8: i32
; CHECK-NEXT:    push($rdi: i64, )
; CHECK-NEXT:    call(work, )
; CHECK-NEXT:    pop($rdi: i64, )
; CHECK-NEXT:    $rsp: i64 += 8: i32
; CHECK-NEXT:    push($rax: i64, )
; CHECK-NEXT:    push($rdi: i64, )
; CHECK-NEXT:    $rdi: i64 = $rbx: i64
; CHECK-NEXT:    call(work, )
; CHECK-NEXT:    $rcx: i64 = $rax: i64
; CHECK-NEXT:    pop($rdi: i64, )
; CHECK-NEXT:    pop($rax: i64, )
; CHECK-NEXT:    $rax: i64 += $rdi: i64
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    $rax: i64 += $rbx: i64
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
; CHECK-NEXT:  2:
; CHECK-NEXT:    clear $rax: i64
; CHECK-NEXT:    ret($rax: i64, )
entry:
  %c = icmp eq i64 %a, 0
  br i1 %c, label %done, label %slow

slow:
  %b = load i64, ptr %p
  %x = call i64 @work(i64 %a)
  %y = call i64 @work(i64 %b)
  %z = add i64 %x, %a
  %w = add i64 %z, %y
  %v = add i64 %w, %b
  br label %done2

done2:
  ret i64 %v

done:
  ret i64 0
}

; the work is in a loop that is entered from the entry, the push must stay out
; of the loop
define i64 @loop_body(i64 %m, ptr %p) {
; CHECK: func loop_body ($2: i64, $3: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    cjmp_int_eq($rdi: i64, 0: i64, ) -> 4
; CHECK-NEXT:    jmp() -> 1
; CHECK-NEXT:  1:
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $r14: i64 = $rsi: i64
; CHECK-NEXT:    clear $r12: i64
; CHECK-NEXT:    clear $rbx: i64
; CHECK-NEXT:    jmp() -> 2
; CHECK-NEXT:  2:
; CHECK-NEXT:    $r13: i64 = [$r14]: i64
; CHECK-NEXT:    $rdi: i64 = $r12: i64
; CHECK-NEXT:    call(work, )
; CHECK-NEXT:    $rax: i64 += $rbx: i64
; CHECK-NEXT:    $r12: i64 += 1: i64
; CHECK-NEXT:    cjmp_int_eq($r12: i64, $r13: i64, ) -> 5
; CHECK-NEXT:    jmp() -> 3
; CHECK-NEXT:  3:
; CHECK-NEXT:    $rbx: i64 = $rax: i64
; CHECK-NEXT:    jmp() -> 2
; CHECK-NEXT:  4:
; CHECK-NEXT:    clear $rax: i64
; CHECK-NEXT:    ret($rax: i64, )
; CHECK-NEXT:  5:
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
entry:
  %c = icmp eq i64 %m, 0
  br i1 %c, label %done, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %s = phi i64 [ 0, %entry ], [ %s.next, %loop ]
  %n = load i64, ptr %p
  %r = call i64 @work(i64 %i)
  %s.next = add i64 %s, %r
  %i.next = add i64 %i, 1
  %d = icmp eq i64 %i.next, %n
  br i1 %d, label %exit, label %loop

exit:
  ret i64 %s.next

done:
  ret i64 0
}
