; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; The callee saved registers are pushed in a block behind the entry block, which
; already did the `sub rsp` for the static alloca. The exits have to pop before
; the `add rsp`, otherwise the pops read the alloca instead of the saved values.
; The entry must not move rsp into a callee saved register either (the copy
; cannot be sunk behind the pushes).
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

declare i64 @work(i64)
declare void @use(ptr)

define i64 @early_exit(i64 %a, ptr %p) {
; CHECK: func early_exit ($2: i64, $3: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rsp: i64 -= 16: i64
; CHECK-NEXT:    $rdi: i64 = $rsp: i64
; CHECK-NEXT:    cjmp_int_eq($rax: i64, 0: i64, ) -> 2
; CHECK-NEXT:    jmp() -> 1
; CHECK-NEXT:  1:
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 -= 8: i32
; CHECK-NEXT:    push($rsi: i64, )
; CHECK-NEXT:    call(use, )
; CHECK-NEXT:    pop($rsi: i64, )
; CHECK-NEXT:    $rsp: i64 += 8: i32
; CHECK-NEXT:    $rbx: i64 = [$rsi]: i64
; CHECK-NEXT:    $rdi: i64 = [$rsi]: i64
; CHECK-NEXT:    call(work, )
; CHECK-NEXT:    $rsp: i64 -= 8: i32
; CHECK-NEXT:    push($rax: i64, )
; CHECK-NEXT:    $rdi: i64 = $rax: i64
; CHECK-NEXT:    call(work, )
; CHECK-NEXT:    $rcx: i64 = $rax: i64
; CHECK-NEXT:    pop($rax: i64, )
; CHECK-NEXT:    $rsp: i64 += 8: i32
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    $rax: i64 += $rbx: i64
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 16: i8
; CHECK-NEXT:    ret($rax: i64, )
; CHECK-NEXT:  2:
; CHECK-NEXT:    $rsp: i64 += 16: i8
; CHECK-NEXT:    clear $rax: i64
; CHECK-NEXT:    ret($rax: i64, )
entry:
  %buf = alloca [16 x i8], align 8
  %c = icmp eq i64 %a, 0
  br i1 %c, label %done, label %slow

slow:
  call void @use(ptr %buf)
  %b = load i64, ptr %p
  %x = call i64 @work(i64 %b)
  %y = call i64 @work(i64 %x)
  %z = add i64 %x, %y
  %w = add i64 %z, %b
  ret i64 %w

done:
  ret i64 0
}
