; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-mir --no-reorder-funcs --passes "LLVMIntrinsicLowering" | FileCheck %s
; The bit count instructions have no immediate source operand.

define i32 @lz() {
; CHECK: func lz ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = 10: i32
; CHECK-NEXT:    lzcnt($eax: i32, $eax: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %r = call i32 @llvm.ctlz.i32(i32 10, i1 false)
  ret i32 %r
}
define i32 @tz() {
; CHECK: func tz ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = 10: i32
; CHECK-NEXT:    tzcnt($eax: i32, $eax: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %r = call i32 @llvm.cttz.i32(i32 10, i1 false)
  ret i32 %r
}
declare i32 @llvm.ctlz.i32(i32, i1)
declare i32 @llvm.cttz.i32(i32, i1)
