; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Regression test: a load that is only used as call argument must not be folded
; into the argument setup when a store to the same address sits in between,
; the call would see the new value.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

declare void @use(ptr, ptr)

define void @f(ptr %slot, ptr %p) {
; CHECK: func f ($2: i64, $3: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rdi: i64 = [$rax]: i64
; CHECK-NEXT:    clear $rcx: i64
; CHECK-NEXT:    [$rax]: i64 = $rcx: i64
; CHECK-NEXT:    call(use, )
; CHECK-NEXT:    ret()
  %v = load ptr, ptr %slot, align 8
  store ptr null, ptr %slot, align 8
  call void @use(ptr %v, ptr %p)
  ret void
}
