; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

define i32 @udiv_i32_1(i32 %x) {
; CHECK: func udiv_i32_1 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    shr2($eax: i32, 0: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 1
  ret i32 %res
}

define i32 @udiv_i32_2(i32 %x) {
; CHECK: func udiv_i32_2 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    shr2($eax: i32, 1: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 2
  ret i32 %res
}

define i32 @udiv_i32_3(i32 %x) {
; CHECK: func udiv_i32_3 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 3: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 3
  ret i32 %res
}

define i32 @udiv_i32_4(i32 %x) {
; CHECK: func udiv_i32_4 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    shr2($eax: i32, 2: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 4
  ret i32 %res
}

define i32 @udiv_i32_5(i32 %x) {
; CHECK: func udiv_i32_5 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 5: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 5
  ret i32 %res
}

define i32 @udiv_i32_6(i32 %x) {
; CHECK: func udiv_i32_6 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 6: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 6
  ret i32 %res
}

define i32 @udiv_i32_7(i32 %x) {
; CHECK: func udiv_i32_7 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 7: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 7
  ret i32 %res
}

define i32 @udiv_i32_8(i32 %x) {
; CHECK: func udiv_i32_8 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    shr2($eax: i32, 3: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 8
  ret i32 %res
}

define i32 @udiv_i32_9(i32 %x) {
; CHECK: func udiv_i32_9 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 9: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 9
  ret i32 %res
}

define i32 @udiv_i32_10(i32 %x) {
; CHECK: func udiv_i32_10 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 10: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 10
  ret i32 %res
}

define i32 @udiv_i32_12(i32 %x) {
; CHECK: func udiv_i32_12 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 12: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 12
  ret i32 %res
}

define i32 @udiv_i32_16(i32 %x) {
; CHECK: func udiv_i32_16 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    shr2($eax: i32, 4: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 16
  ret i32 %res
}

define i32 @udiv_i32_25(i32 %x) {
; CHECK: func udiv_i32_25 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 25: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 25
  ret i32 %res
}

define i32 @udiv_i32_100(i32 %x) {
; CHECK: func udiv_i32_100 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 100: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 100
  ret i32 %res
}

define i32 @udiv_i32_255(i32 %x) {
; CHECK: func udiv_i32_255 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 255: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 255
  ret i32 %res
}

define i32 @udiv_i32_256(i32 %x) {
; CHECK: func udiv_i32_256 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    shr2($eax: i32, 8: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 256
  ret i32 %res
}

define i32 @udiv_i32_641(i32 %x) {
; CHECK: func udiv_i32_641 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 641: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 641
  ret i32 %res
}

define i32 @udiv_i32_1000(i32 %x) {
; CHECK: func udiv_i32_1000 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 1000: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 1000
  ret i32 %res
}

define i32 @udiv_i32_65535(i32 %x) {
; CHECK: func udiv_i32_65535 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 65535: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 65535
  ret i32 %res
}

define i32 @udiv_i32_65536(i32 %x) {
; CHECK: func udiv_i32_65536 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    shr2($eax: i32, 16: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 65536
  ret i32 %res
}

define i32 @udiv_i32_2147483647(i32 %x) {
; CHECK: func udiv_i32_2147483647 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 2147483647: i32
; CHECK-NEXT:    udiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = udiv i32 %x, 2147483647
  ret i32 %res
}

define i32 @sdiv_i32_1(i32 %x) {
; CHECK: func sdiv_i32_1 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 1: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 1
  ret i32 %res
}

define i32 @sdiv_i32_2(i32 %x) {
; CHECK: func sdiv_i32_2 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    shr2($eax: i32, 31: i8, )
; CHECK-NEXT:    $eax: i32 += $edi: i32
; CHECK-NEXT:    cmov_ns($eax: i32, $edi: i32, $edi: i32, $edi: i32, )
; CHECK-NEXT:    sar2($eax: i32, 1: i8, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 2
  ret i32 %res
}

define i32 @sdiv_i32_3(i32 %x) {
; CHECK: func sdiv_i32_3 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 3: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 3
  ret i32 %res
}

define i32 @sdiv_i32_4(i32 %x) {
; CHECK: func sdiv_i32_4 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    lea($eax: i32, [$edi + 3]: i32, )
; CHECK-NEXT:    cmov_ns($eax: i32, $edi: i32, $edi: i32, $edi: i32, )
; CHECK-NEXT:    sar2($eax: i32, 2: i8, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 4
  ret i32 %res
}

define i32 @sdiv_i32_5(i32 %x) {
; CHECK: func sdiv_i32_5 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 5: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 5
  ret i32 %res
}

define i32 @sdiv_i32_6(i32 %x) {
; CHECK: func sdiv_i32_6 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 6: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 6
  ret i32 %res
}

define i32 @sdiv_i32_7(i32 %x) {
; CHECK: func sdiv_i32_7 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 7: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 7
  ret i32 %res
}

define i32 @sdiv_i32_8(i32 %x) {
; CHECK: func sdiv_i32_8 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    lea($eax: i32, [$edi + 7]: i32, )
; CHECK-NEXT:    cmov_ns($eax: i32, $edi: i32, $edi: i32, $edi: i32, )
; CHECK-NEXT:    sar2($eax: i32, 3: i8, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 8
  ret i32 %res
}

define i32 @sdiv_i32_9(i32 %x) {
; CHECK: func sdiv_i32_9 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 9: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 9
  ret i32 %res
}

define i32 @sdiv_i32_10(i32 %x) {
; CHECK: func sdiv_i32_10 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    mov_sx($rax: i64, $edi: i32, )
; CHECK-NEXT:    smul3($rax: i64, $rax: i64, 1717986919: i32, )
; CHECK-NEXT:    $rcx: i64 = $rax: i64
; CHECK-NEXT:    shr2($rcx: i64, 63: i8, )
; CHECK-NEXT:    sar2($rax: i64, 34: i8, )
; CHECK-NEXT:    $eax: i32 += $ecx: i32
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 10
  ret i32 %res
}

define i32 @sdiv_i32_12(i32 %x) {
; CHECK: func sdiv_i32_12 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 12: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 12
  ret i32 %res
}

define i32 @sdiv_i32_16(i32 %x) {
; CHECK: func sdiv_i32_16 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    lea($eax: i32, [$edi + 15]: i32, )
; CHECK-NEXT:    cmov_ns($eax: i32, $edi: i32, $edi: i32, $edi: i32, )
; CHECK-NEXT:    sar2($eax: i32, 4: i8, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 16
  ret i32 %res
}

define i32 @sdiv_i32_25(i32 %x) {
; CHECK: func sdiv_i32_25 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 25: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 25
  ret i32 %res
}

define i32 @sdiv_i32_100(i32 %x) {
; CHECK: func sdiv_i32_100 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 100: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 100
  ret i32 %res
}

define i32 @sdiv_i32_255(i32 %x) {
; CHECK: func sdiv_i32_255 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 255: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 255
  ret i32 %res
}

define i32 @sdiv_i32_256(i32 %x) {
; CHECK: func sdiv_i32_256 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 256: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 256
  ret i32 %res
}

define i32 @sdiv_i32_641(i32 %x) {
; CHECK: func sdiv_i32_641 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 641: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 641
  ret i32 %res
}

define i32 @sdiv_i32_1000(i32 %x) {
; CHECK: func sdiv_i32_1000 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 1000: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 1000
  ret i32 %res
}

define i32 @sdiv_i32_65535(i32 %x) {
; CHECK: func sdiv_i32_65535 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 65535: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 65535
  ret i32 %res
}

define i32 @sdiv_i32_65536(i32 %x) {
; CHECK: func sdiv_i32_65536 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 65536: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 65536
  ret i32 %res
}

define i32 @sdiv_i32_2147483647(i32 %x) {
; CHECK: func sdiv_i32_2147483647 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = 2147483647: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, 2147483647
  ret i32 %res
}

define i32 @sdiv_i32_m1(i32 %x) {
; CHECK: func sdiv_i32_m1 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = -1: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, -1
  ret i32 %res
}

define i32 @sdiv_i32_m2(i32 %x) {
; CHECK: func sdiv_i32_m2 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = -2: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, -2
  ret i32 %res
}

define i32 @sdiv_i32_m3(i32 %x) {
; CHECK: func sdiv_i32_m3 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = -3: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, -3
  ret i32 %res
}

define i32 @sdiv_i32_m7(i32 %x) {
; CHECK: func sdiv_i32_m7 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = -7: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, -7
  ret i32 %res
}

define i32 @sdiv_i32_m8(i32 %x) {
; CHECK: func sdiv_i32_m8 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = -8: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, -8
  ret i32 %res
}

define i32 @sdiv_i32_m1000(i32 %x) {
; CHECK: func sdiv_i32_m1000 ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $ecx: i32 = -1000: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
  %res = sdiv i32 %x, -1000
  ret i32 %res
}

define i64 @udiv_i64_3(i64 %x) {
; CHECK: func udiv_i64_3 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 3: i64
; CHECK-NEXT:    udiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = udiv i64 %x, 3
  ret i64 %res
}

define i64 @udiv_i64_7(i64 %x) {
; CHECK: func udiv_i64_7 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 7: i64
; CHECK-NEXT:    udiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = udiv i64 %x, 7
  ret i64 %res
}

define i64 @udiv_i64_10(i64 %x) {
; CHECK: func udiv_i64_10 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 10: i64
; CHECK-NEXT:    udiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = udiv i64 %x, 10
  ret i64 %res
}

define i64 @udiv_i64_1000(i64 %x) {
; CHECK: func udiv_i64_1000 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 1000: i64
; CHECK-NEXT:    udiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = udiv i64 %x, 1000
  ret i64 %res
}

define i64 @udiv_i64_4294967296(i64 %x) {
; CHECK: func udiv_i64_4294967296 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 4294967296: i64
; CHECK-NEXT:    udiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = udiv i64 %x, 4294967296
  ret i64 %res
}

define i64 @udiv_i64_4294967297(i64 %x) {
; CHECK: func udiv_i64_4294967297 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 4294967297: i64
; CHECK-NEXT:    udiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = udiv i64 %x, 4294967297
  ret i64 %res
}

define i64 @udiv_i64_1000000007(i64 %x) {
; CHECK: func udiv_i64_1000000007 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 1000000007: i64
; CHECK-NEXT:    udiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = udiv i64 %x, 1000000007
  ret i64 %res
}

define i64 @sdiv_i64_3(i64 %x) {
; CHECK: func sdiv_i64_3 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 3: i64
; CHECK-NEXT:    idiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = sdiv i64 %x, 3
  ret i64 %res
}

define i64 @sdiv_i64_7(i64 %x) {
; CHECK: func sdiv_i64_7 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 7: i64
; CHECK-NEXT:    idiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = sdiv i64 %x, 7
  ret i64 %res
}

define i64 @sdiv_i64_10(i64 %x) {
; CHECK: func sdiv_i64_10 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 10: i64
; CHECK-NEXT:    idiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = sdiv i64 %x, 10
  ret i64 %res
}

define i64 @sdiv_i64_1000(i64 %x) {
; CHECK: func sdiv_i64_1000 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 1000: i64
; CHECK-NEXT:    idiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = sdiv i64 %x, 1000
  ret i64 %res
}

define i64 @sdiv_i64_4294967296(i64 %x) {
; CHECK: func sdiv_i64_4294967296 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 4294967296: i64
; CHECK-NEXT:    idiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = sdiv i64 %x, 4294967296
  ret i64 %res
}

define i64 @sdiv_i64_4294967297(i64 %x) {
; CHECK: func sdiv_i64_4294967297 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 4294967297: i64
; CHECK-NEXT:    idiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = sdiv i64 %x, 4294967297
  ret i64 %res
}

define i64 @sdiv_i64_1000000007(i64 %x) {
; CHECK: func sdiv_i64_1000000007 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = 1000000007: i64
; CHECK-NEXT:    idiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = sdiv i64 %x, 1000000007
  ret i64 %res
}

define i64 @sdiv_i64_m3(i64 %x) {
; CHECK: func sdiv_i64_m3 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = -3: i64
; CHECK-NEXT:    idiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = sdiv i64 %x, -3
  ret i64 %res
}

define i64 @sdiv_i64_m1000(i64 %x) {
; CHECK: func sdiv_i64_m1000 ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    $rcx: i64 = -1000: i64
; CHECK-NEXT:    idiv($rax: i64, $rdx: i64, $rax: i64, $rcx: i64, )
; CHECK-NEXT:    ret($rax: i64, )
  %res = sdiv i64 %x, -1000
  ret i64 %res
}
