; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Regression test: extractelement lane i of a <4 x i64> has to read lane i
; (lane 0 -> low, 1 -> vpextr 1, 2 -> high half low, 3 -> high half vpextr 1).
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

@g = global [4 x i64] [i64 10, i64 20, i64 30, i64 40]
define i64 @pick(i32 %i) noinline {
; CHECK: func pick ($2: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $ymm1: i64x4 = [g]: i64x4
; CHECK-NEXT:    $rdi: i64 = $xmm1: i64x2
; CHECK-NEXT:    vpextr($rcx: i64, $xmm1: i64x2, 1: i8, )
; CHECK-NEXT:    vextract128($xmm0: i64x2, $ymm1: i64x4, 1: i8, )
; CHECK-NEXT:    $rsi: i64 = $xmm0: i64x2
; CHECK-NEXT:    vextract128($xmm0: i64x2, $ymm1: i64x4, 1: i8, )
; CHECK-NEXT:    vpextr($rax: i64, $xmm0: i64x2, 1: i8, )
; CHECK-NEXT:    $rcx: i64 += $rcx: i64
; CHECK-NEXT:    lea($rdx: i64, [$rcx + $rcx *4]: i64, )
; CHECK-NEXT:    $rsi: i64 *= 1000: i64
; CHECK-NEXT:    $rax: i64 *= 100000: i64
; CHECK-NEXT:    $rdi: i64 += $rdx: i64
; CHECK-NEXT:    $rsi: i64 += $rax: i64
; CHECK-NEXT:    $rdi: i64 += $rsi: i64
; CHECK-NEXT:    $rax: i64 = $rdi: i64
; CHECK-NEXT:    ret($rax: i64, )
  %v = load <4 x i64>, ptr @g
  %a = extractelement <4 x i64> %v, i32 0
  %b = extractelement <4 x i64> %v, i32 1
  %c = extractelement <4 x i64> %v, i32 2
  %d = extractelement <4 x i64> %v, i32 3
  %s1 = mul i64 %a, 1
  %s2 = mul i64 %b, 10
  %s3 = mul i64 %c, 1000
  %s4 = mul i64 %d, 100000
  %t1 = add i64 %s1, %s2
  %t2 = add i64 %s3, %s4
  %t = add i64 %t1, %t2
  ret i64 %t
}
