; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

define double @sel(i1 %c, double %a, double %b) {
; CHECK: func sel ($2: i8, $3: f64, $4: f64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $mm2: f64 = $mm1: f64
; CHECK-NEXT:    mov_zx($rax: i64, $ldi: i8, )
; CHECK-NEXT:    neg1($rax: i64, )
; CHECK-NEXT:    $mm1: f64 = $rax: i64
; CHECK-NEXT:    vblendv($mm0: f64, $mm2: f64, $mm0: f64, $mm1: f64, )
; CHECK-NEXT:    ret($mm0: f64, )
  %r = select i1 %c, double %a, double %b
  ret double %r
}
