; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Regression test: GEP indices narrower than 64 bit must be sign extended to
; pointer width, otherwise the address uses a 32 bit index register that cannot be encoded.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s
; RUN: %foffcc %s %t.o

define i32 @var_idx(ptr %p, i32 %i) {
; CHECK: func var_idx ($2: i64, $3: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    mov_sx($rax: i64, $esi: i32, )
; CHECK-NEXT:    $eax: i32 = [$rdi + $rax *4]: i32
; CHECK-NEXT:    ret($eax: i32, )
  %g = getelementptr i32, ptr %p, i32 %i
  %v = load i32, ptr %g
  ret i32 %v
}

define i32 @neg_const_idx(ptr %p) {
; CHECK: func neg_const_idx ($2: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = [$rdi + -8]: i32
; CHECK-NEXT:    ret($eax: i32, )
  %g = getelementptr i32, ptr %p, i32 -2
  %v = load i32, ptr %g
  ret i32 %v
}
