; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

; (alloca + 128) + 16 must not be folded into a three operand lea that adds
; the base twice.

define ptr @f() {
; CHECK: func f ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 160: i64
; CHECK-NEXT:    $rcx: i64 = $rsp: i64
; CHECK-NEXT:    $rcx: i64 += 128: i64
; CHECK-NEXT:    $rax: i64 = $rcx: i64
; CHECK-NEXT:    $rax: i64 += 16: i64
; CHECK-NEXT:    clear $rdx: i64
; CHECK-NEXT:    [$rcx + 16]: i64 = $rdx: i64
; CHECK-NEXT:    $rsp: i64 += 160: i8
; CHECK-NEXT:    ret($rax: i64, )
  %a = alloca [160 x i8], align 8
  %p = getelementptr inbounds i8, ptr %a, i64 128
  %q = getelementptr inbounds i8, ptr %p, i64 16
  store i64 0, ptr %q
  ret ptr %q
}
