; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Arguments beyond the sixth are passed on the stack: the caller pushes them last
; to first (the 7th ends up at the lowest address) and the callee reads them
; relative to rbp, independent of stack slots, alignment and saved registers.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

declare i64 @ext(i64)

define i64 @callee(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f, i64 %g, i64 %h) noinline {
; CHECK: func callee ($2: i64, $3: i64, $4: i64, $5: i64, $6: i64, $7: i64, $8: i64, $9: i64, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 16: i64
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    push($r15: i64, )
; CHECK-NEXT:    push($r14: i64, )
; CHECK-NEXT:    push($r13: i64, )
; CHECK-NEXT:    push($r12: i64, )
; CHECK-NEXT:    $rax: i64 = [$rbp + 24]: i64
; CHECK-NEXT:    [$rbp + -16]: i64 = $rax: i64
; CHECK-NEXT:    $r15: i64 = [$rbp + 16]: i64
; CHECK-NEXT:    $r14: i64 = $r9: i64
; CHECK-NEXT:    $r13: i64 = $r8: i64
; CHECK-NEXT:    $r12: i64 = $rcx: i64
; CHECK-NEXT:    $rbx: i64 = $rdi: i64
; CHECK-NEXT:    $rsp: i64 -= 8: i32
; CHECK-NEXT:    push($rdx: i64, )
; CHECK-NEXT:    $rdi: i64 = $rsi: i64
; CHECK-NEXT:    call(ext, )
; CHECK-NEXT:    $rcx: i64 = $rax: i64
; CHECK-NEXT:    pop($rdx: i64, )
; CHECK-NEXT:    push($rcx: i64, )
; CHECK-NEXT:    $rdi: i64 = $rdx: i64
; CHECK-NEXT:    call(ext, )
; CHECK-NEXT:    pop($rcx: i64, )
; CHECK-NEXT:    $rsp: i64 += 8: i32
; CHECK-NEXT:    $rcx: i64 += $rax: i64
; CHECK-NEXT:    $rcx: i64 += $rbx: i64
; CHECK-NEXT:    $rcx: i64 += $r12: i64
; CHECK-NEXT:    $rax: i64 = $rcx: i64
; CHECK-NEXT:    $rax: i64 += $r13: i64
; CHECK-NEXT:    $rax: i64 += $r14: i64
; CHECK-NEXT:    $r15: i64 *= 100: i64
; CHECK-NEXT:    $rcx: i64 = [$rbp + -16]: i64
; CHECK-NEXT:    $rcx: i64 *= 1000: i64
; CHECK-NEXT:    $rax: i64 += $r15: i64
; CHECK-NEXT:    $rax: i64 += $rcx: i64
; CHECK-NEXT:    pop($r12: i64, )
; CHECK-NEXT:    pop($r13: i64, )
; CHECK-NEXT:    pop($r14: i64, )
; CHECK-NEXT:    pop($r15: i64, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    $rsp: i64 += 16: i64
; CHECK-NEXT:    ret($rax: i64, )
  %slot = alloca i64
  store i64 %a, ptr %slot
  %x = call i64 @ext(i64 %b)
  %y = call i64 @ext(i64 %c)
  %l = load i64, ptr %slot
  %s0 = add i64 %x, %y
  %s1 = add i64 %s0, %l
  %s2 = add i64 %s1, %d
  %s3 = add i64 %s2, %e
  %s4 = add i64 %s3, %f
  %g100 = mul i64 %g, 100
  %h1000 = mul i64 %h, 1000
  %s5 = add i64 %s4, %g100
  %s6 = add i64 %s5, %h1000
  ret i64 %s6
}

define i64 @caller() {
; CHECK: func caller ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    push(8: i64, )
; CHECK-NEXT:    push(7: i64, )
; CHECK-NEXT:    $rdi: i64 = 1: i64
; CHECK-NEXT:    $rsi: i64 = 2: i64
; CHECK-NEXT:    $rdx: i64 = 3: i64
; CHECK-NEXT:    $rcx: i64 = 4: i64
; CHECK-NEXT:    $r8: i64 = 5: i64
; CHECK-NEXT:    $r9: i64 = 6: i64
; CHECK-NEXT:    call(callee, )
; CHECK-NEXT:    $rsp: i64 += 16: i32
; CHECK-NEXT:    ret($rax: i64, )
  %r = call i64 @callee(i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8)
  ret i64 %r
}
