; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

define <4 x i64> @zext(<4 x i32> %v) {
; CHECK: func zext ($2: i32x4, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    mov_zx($ymm0: i64x4, $xmm0: i32x4, )
; CHECK-NEXT:    ret($ymm0: i64x4, )
  %r = zext <4 x i32> %v to <4 x i64>
  ret <4 x i64> %r
}

define <4 x i64> @sext(<4 x i32> %v) {
; CHECK: func sext ($2: i32x4, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    mov_sx($ymm0: i64x4, $xmm0: i32x4, )
; CHECK-NEXT:    ret($ymm0: i64x4, )
  %r = sext <4 x i32> %v to <4 x i64>
  ret <4 x i64> %r
}
