; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s
; xor of integer vectors must be a vector xor, not the scalar two address xor.

define <4 x i32> @xor_v4i32(<4 x i32> %a, <4 x i32> %b) {
; CHECK: func xor_v4i32 ($2: i32x4, $3: i32x4, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $xmm0: i32x4 = $xmm0: i32x4 ^ $xmm1: i32x4
; CHECK-NEXT:    ret($xmm0: i32x4, )
  %r = xor <4 x i32> %a, %b
  ret <4 x i32> %r
}
