; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Lane order tests: lane i of a vector has to be read/written at lane i of the register.
; Each function reads from a global with distinct lane values, so a wrong lane gives a wrong value.
; (<4 x double> lanes 1 and 3 and i64 insertelement are missing, see known-issues.md)
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s

@gi4 = global [4 x i64] [i64 10, i64 20, i64 30, i64 40]
@gi2 = global [2 x i64] [i64 10, i64 20]
@gd4 = global [4 x double] [double 10.0, double 20.0, double 30.0, double 40.0]
@gf4 = global [4 x float] [float 10.0, float 20.0, float 30.0, float 40.0]

define i64 @ext_v4i64_0() {
; CHECK: func ext_v4i64_0 ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $ymm0: i64x4 = [gi4]: i64x4
; CHECK-NEXT:    $rax: i64 = $xmm0: i64x2
; CHECK-NEXT:    ret($rax: i64, )
  %v = load <4 x i64>, ptr @gi4
  %a = extractelement <4 x i64> %v, i32 0
  ret i64 %a
}

define i64 @ext_v4i64_1() {
; CHECK: func ext_v4i64_1 ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $ymm0: i64x4 = [gi4]: i64x4
; CHECK-NEXT:    vpextr($rax: i64, $xmm0: i64x2, 1: i8, )
; CHECK-NEXT:    ret($rax: i64, )
  %v = load <4 x i64>, ptr @gi4
  %a = extractelement <4 x i64> %v, i32 1
  ret i64 %a
}

define i64 @ext_v4i64_2() {
; CHECK: func ext_v4i64_2 ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $ymm0: i64x4 = [gi4]: i64x4
; CHECK-NEXT:    vextract128($xmm0: i64x2, $ymm0: i64x4, 1: i8, )
; CHECK-NEXT:    $rax: i64 = $xmm0: i64x2
; CHECK-NEXT:    ret($rax: i64, )
  %v = load <4 x i64>, ptr @gi4
  %a = extractelement <4 x i64> %v, i32 2
  ret i64 %a
}

define i64 @ext_v4i64_3() {
; CHECK: func ext_v4i64_3 ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $ymm0: i64x4 = [gi4]: i64x4
; CHECK-NEXT:    vextract128($xmm0: i64x2, $ymm0: i64x4, 1: i8, )
; CHECK-NEXT:    vpextr($rax: i64, $xmm0: i64x2, 1: i8, )
; CHECK-NEXT:    ret($rax: i64, )
  %v = load <4 x i64>, ptr @gi4
  %a = extractelement <4 x i64> %v, i32 3
  ret i64 %a
}

define i64 @ext_v2i64_0() {
; CHECK: func ext_v2i64_0 ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $xmm0: i64x2 = [gi2]: i64x2
; CHECK-NEXT:    $rax: i64 = $xmm0: i64x2
; CHECK-NEXT:    ret($rax: i64, )
  %v = load <2 x i64>, ptr @gi2
  %a = extractelement <2 x i64> %v, i32 0
  ret i64 %a
}

define i64 @ext_v2i64_1() {
; CHECK: func ext_v2i64_1 ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $xmm0: i64x2 = [gi2]: i64x2
; CHECK-NEXT:    vpextr($rax: i64, $xmm0: i64x2, 1: i8, )
; CHECK-NEXT:    ret($rax: i64, )
  %v = load <2 x i64>, ptr @gi2
  %a = extractelement <2 x i64> %v, i32 1
  ret i64 %a
}

define double @ext_v4f64_0() {
; CHECK: func ext_v4f64_0 ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $ymm0: f64x4 = [gd4]: f64x4
; CHECK-NEXT:    $mm0: f64 = $xmm0: f64x2
; CHECK-NEXT:    ret($mm0: f64, )
  %v = load <4 x double>, ptr @gd4
  %a = extractelement <4 x double> %v, i32 0
  ret double %a
}

define double @ext_v4f64_2() {
; CHECK: func ext_v4f64_2 ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $ymm0: f64x4 = [gd4]: f64x4
; CHECK-NEXT:    vextract128($xmm0: f64x2, $ymm0: f64x4, 1: i8, )
; CHECK-NEXT:    $mm0: f64 = $xmm0: f64x2
; CHECK-NEXT:    ret($mm0: f64, )
  %v = load <4 x double>, ptr @gd4
  %a = extractelement <4 x double> %v, i32 2
  ret double %a
}

define float @ext_v4f32_0() {
; CHECK: func ext_v4f32_0 ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $xmm0: f32x4 = [gf4]: f32x4
; CHECK-NEXT:    $mm0: f32 = $xmm0: f32x4
; CHECK-NEXT:    ret($mm0: f32, )
  %v = load <4 x float>, ptr @gf4
  %a = extractelement <4 x float> %v, i32 0
  ret float %a
}

define void @ins_v4f32_0(ptr %out, float %x) {
; CHECK: func ins_v4f32_0 ($2: i64, $3: f32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $mm1: f32 = $mm0: f32
; CHECK-NEXT:    $xmm0: f32x4 = [gf4]: f32x4
; CHECK-NEXT:    vinsertps($xmm0: f32x4, $xmm0: f32x4, $xmm1: f32x4, 0: i8, )
; CHECK-NEXT:    [$rdi]: f32x4 = $xmm0: f32x4
; CHECK-NEXT:    ret()
  %v = load <4 x float>, ptr @gf4
  %w = insertelement <4 x float> %v, float %x, i32 0
  store <4 x float> %w, ptr %out
  ret void
}

define float @ext_v4f32_1() {
; CHECK: func ext_v4f32_1 ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $xmm1: f32x4 = [gf4]: f32x4
; CHECK-NEXT:    clear $xmm0: f32x4
; CHECK-NEXT:    vinsertps($xmm0: f32x4, $xmm0: f32x4, $xmm1: f32x4, 78: i8, )
; CHECK-NEXT:    ret($mm0: f32, )
  %v = load <4 x float>, ptr @gf4
  %a = extractelement <4 x float> %v, i32 1
  ret float %a
}

define void @ins_v4f32_1(ptr %out, float %x) {
; CHECK: func ins_v4f32_1 ($2: i64, $3: f32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $mm1: f32 = $mm0: f32
; CHECK-NEXT:    $xmm0: f32x4 = [gf4]: f32x4
; CHECK-NEXT:    vinsertps($xmm0: f32x4, $xmm0: f32x4, $xmm1: f32x4, 16: i8, )
; CHECK-NEXT:    [$rdi]: f32x4 = $xmm0: f32x4
; CHECK-NEXT:    ret()
  %v = load <4 x float>, ptr @gf4
  %w = insertelement <4 x float> %v, float %x, i32 1
  store <4 x float> %w, ptr %out
  ret void
}

define float @ext_v4f32_2() {
; CHECK: func ext_v4f32_2 ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $xmm1: f32x4 = [gf4]: f32x4
; CHECK-NEXT:    clear $xmm0: f32x4
; CHECK-NEXT:    vinsertps($xmm0: f32x4, $xmm0: f32x4, $xmm1: f32x4, 142: i8, )
; CHECK-NEXT:    ret($mm0: f32, )
  %v = load <4 x float>, ptr @gf4
  %a = extractelement <4 x float> %v, i32 2
  ret float %a
}

define void @ins_v4f32_2(ptr %out, float %x) {
; CHECK: func ins_v4f32_2 ($2: i64, $3: f32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $mm1: f32 = $mm0: f32
; CHECK-NEXT:    $xmm0: f32x4 = [gf4]: f32x4
; CHECK-NEXT:    vinsertps($xmm0: f32x4, $xmm0: f32x4, $xmm1: f32x4, 32: i8, )
; CHECK-NEXT:    [$rdi]: f32x4 = $xmm0: f32x4
; CHECK-NEXT:    ret()
  %v = load <4 x float>, ptr @gf4
  %w = insertelement <4 x float> %v, float %x, i32 2
  store <4 x float> %w, ptr %out
  ret void
}

define float @ext_v4f32_3() {
; CHECK: func ext_v4f32_3 ()
; CHECK-NEXT:  0:
; CHECK-NEXT:    $xmm1: f32x4 = [gf4]: f32x4
; CHECK-NEXT:    clear $xmm0: f32x4
; CHECK-NEXT:    vinsertps($xmm0: f32x4, $xmm0: f32x4, $xmm1: f32x4, 206: i8, )
; CHECK-NEXT:    ret($mm0: f32, )
  %v = load <4 x float>, ptr @gf4
  %a = extractelement <4 x float> %v, i32 3
  ret float %a
}

define void @ins_v4f32_3(ptr %out, float %x) {
; CHECK: func ins_v4f32_3 ($2: i64, $3: f32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $mm1: f32 = $mm0: f32
; CHECK-NEXT:    $xmm0: f32x4 = [gf4]: f32x4
; CHECK-NEXT:    vinsertps($xmm0: f32x4, $xmm0: f32x4, $xmm1: f32x4, 48: i8, )
; CHECK-NEXT:    [$rdi]: f32x4 = $xmm0: f32x4
; CHECK-NEXT:    ret()
  %v = load <4 x float>, ptr @gf4
  %w = insertelement <4 x float> %v, float %x, i32 3
  store <4 x float> %w, ptr %out
  ret void
}

