; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s
; Per lane right shifts of vectors must use vpsrlv/vpsravd, not the scalar cl path.

define <4 x i32> @lshr_v4i32(<4 x i32> %a, <4 x i32> %b) {
; CHECK: func lshr_v4i32 ($2: i32x4, $3: i32x4, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    vShr($xmm0: i32x4, $xmm0: i32x4, $xmm1: i32x4, )
; CHECK-NEXT:    ret($xmm0: i32x4, )
  %r = lshr <4 x i32> %a, %b
  ret <4 x i32> %r
}

define <4 x i32> @ashr_v4i32(<4 x i32> %a, <4 x i32> %b) {
; CHECK: func ashr_v4i32 ($2: i32x4, $3: i32x4, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    vSar($xmm0: i32x4, $xmm0: i32x4, $xmm1: i32x4, )
; CHECK-NEXT:    ret($xmm0: i32x4, )
  %r = ashr <4 x i32> %a, %b
  ret <4 x i32> %r
}

define <2 x i64> @lshr_v2i64(<2 x i64> %a, <2 x i64> %b) {
; CHECK: func lshr_v2i64 ($2: i64x2, $3: i64x2, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    vShr($xmm0: i64x2, $xmm0: i64x2, $xmm1: i64x2, )
; CHECK-NEXT:    ret($xmm0: i64x2, )
  %r = lshr <2 x i64> %a, %b
  ret <2 x i64> %r
}
