config_version = 1

# ------------------------------------------------------------------------------------------------
# Target setup

[target]
name = "x86_64-linux"

[target.features]
avx512 = false
bmi2 = true

# ------------------------------------------------------------------------------------------------
# Optimizations

[optimize]
pipeline = "default_release"

[pipeline.default_release_early]
fir_passes = [
        "DCE", "LegalizeStructs", "LLVMIntrinsicLowering", "SORA", "Mem2Reg", "DoubleLoadElim",
        "DCE", "IntrinSimplify", "InstSimplify", "DCE", "SimplifyCFG", "LVN", "DCE",
        "FuncPropAnnotator", "GlobalPromotion", "ArgPromotion", "GDCE"
]

[pipeline.default_release_middle]
fir_passes = [
      "DCE", "CmpKnownValProp", "SimplifyCFG", "TailRecElim", "LICM", "LoopRotate",
      "LoopSimplify", "DCE", "LVN", "SCCP", "IntrinSimplify", "InstSimplify",
      "DoubleLoadElim", "DCE", "SimplifyCFG", "StackKnownBits", "SORA", "Mem2Reg",
      "SimplifyCFG", "DCE", "LVN", "InstSimplify", "ConstLoopEval", "LoopSimplify",
      "InstSimplify", "SimplifyCFG", "FuncPropAnnotator", "IPCP", "GlobalPromotion", "Inline", "Inline", "Inline",
      "ArgPromotion", "GDCE", "FunctionDedupSame", "GDCE", "FuncPropAnnotator", "SimplifyCFG", "CmpKnownValProp",
      "InstSimplify", "SimplifyCFG", "LICM", "DCE", "LoopSimplify", "LoopUnswitch", "LoopUnroll", "SimplifyCFG", "DCE", "SLPVectorizer",
      "LVN", "SCCP", "IntrinSimplify", "InstSimplify", "ConstLoopEval", "InstSimplify",
      "CmpKnownValProp", "SimplifyCFG", "DCE","FuncPropAnnotator", "IPCP", "GlobalPromotion", "Inline", "Inline", "Inline",
      "ArgPromotion", "FunctionDedupSame", "GDCE", "FuncPropAnnotator", "SimplifyCFG", "InstSimplify",
      "SimplifyCFG", "TailRecElim", "SimplifyCFG", "DCE", "LoopSimplify", "LoopUnswitch", "IntrinSimplify", "InstSimplify", "DCE",
  		"StackKnownBits", "SORA", "Mem2Reg", "SimplifyCFG", "DCE",
]

[pipeline.default_release_late]
fir_passes = [
      "ArgPromotion", "FuncPropAnnotator", "FunctionDedupDiff", "GDCE", "IPCP",
      "GlobalPromotion", "Inline", "Inline", "GDCE", "FuncPropAnnotator",
      "LVN", "SCCP", "DoubleLoadElim", "DCE", "IntrinSimplify", "InstSimplify",
      "CmpKnownValProp", "SimplifyCFG", "SCCP",
      "ArgPromotion", "FuncPropAnnotator", "FunctionDedupDiff", "Inline", "Inline",
      "Inline", "GDCE", "IPCP", "FuncPropAnnotator",
      "SimplifyCFG", "LVN", "SCCP", "DoubleLoadElim", "DCE", "IntrinSimplify", "SimplifyCFG",
      "InstSimplify", "SCCP", "DCE", "InstSimplify", "ConstLoopEval", "LoopSimplify",
      "LoopUnswitch", "LoopUnroll", "SimplifyCFG", "DCE", "SLPVectorizer", "InstSimplify",
      "SimplifyCFG",
      "ArgPromotion", "FuncPropAnnotator", "FunctionDedupDiff", "Inline", "Inline",
      "GDCE", "IPCP", "FuncPropAnnotator",
      "SimplifyCFG", "LVN", "SCCP", "DCE", "IntrinSimplify", "InstSimplify", "DCE",
      "SLPVectorizer", "InstSimplify", "SimplifyCFG",
      "LegalizeVecs", "SCCP", "LVN", "InstSimplify", "DCE", "LVN", "InstSimplify", "DCE",  
]

[pipeline.default_release_cleanup]
fir_passes = [
  "MergeAlloca", "LVN", "InstSimplify", "SCCP", "DCE", "LVN",
  "InstSimplify", "SimplifyCFG", "DCE", "LegalizeVecs", "InstSimplify",
  "SCCP", "LegalizeVecs", "DCE",
]

[pipeline.default_release]
fir_passes = [
  "pipeline:default_release_early",
  "pipeline:default_release_middle",
  "pipeline:default_release_late",
  "pipeline:default_release_cleanup",
]

# ------------------------------------------------------------------------------------------------
# Passes

#module
[pass.Inline]
recursive = true
[pass.LoopUnroll]
maxUnroll = 32
maxInstr = 32
[pass.FuncPropAnnotator]
[pass.GlobalPromotion]
[pass.ArgPromotion]
[pass.GDCE]
[pass.IPCP]
[pass.FunctionDedupSame]
[pass.FunctionDedupDiff]
[pass.LoopUnswitch]

#func
[pass.SLPVectorizer]
reductions = true
[pass.DCE]
[pass.LegalizeStructs]
[pass.LLVMIntrinsicLowering]
[pass.SORA]
[pass.Mem2Reg]
[pass.DoubleLoadElim]
[pass.IntrinSimplify]
[pass.InstSimplify]
[pass.SimplifyCFG]
[pass.LVN]
[pass.CmpKnownValProp]
[pass.TailRecElim]
[pass.LICM]
[pass.LoopRotate]
[pass.LoopSimplify]
[pass.SCCP]
[pass.StackKnownBits]
[pass.ConstLoopEval]
[pass.MergeAlloca]
[pass.LegalizeVecs]
[pass.PrintFunc]
[pass.VerifyFunc]

# ------------------------------------------------------------------------------------------------
# Debug

[debug]
print_between_passes = false
print_color = true
verify_between_passes = false
bisect = 0
