config_version = 1
include = [
  "Default",
  # "FastMath",
]

[pipeline.fir.default_release]
passes = [
  "pipeline:default_release_early",
  "pipeline:default_release_middle",
  "pipeline:default_release_late",
  "pipeline:default_release_cleanup",
  # "PrintFunc",
]
# ------------------------------------------------------------------------------------------------
# Optimizations

# mir_passes = []


#########
# TOOD potential futures stuff

# like include but gets applied afterwards
# overwrite = [
#   "default",
# ]
# [debug]
# color = true
# print_missed_optim = true

# [remarks]
# output = "remarks.yaml"
# passes = ["SLPVectorizer"]
# filter = "hot"
# missed = true   

# [pass.UnrollEarly]
# extends = "unroll"
# max_unroll = 2

# [pass.FuncDedupLate]
# extends = "func_dedup"
# when = "is_hot"
# merge_partial_matches = true

# [[pass_override]]
# filter = "annotation:always_inline"
# pass = "inline"
# always_inline = true


