; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Cold blocks (ending in unreachable) are sunk below the hot path and the loop
; body stays contiguous.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s
; RUN: %foffcc %s %t.o

declare void @abort() noreturn

define i32 @sum(ptr %p, i32 %n) {
; CHECK: func sum ($2: i64, $3: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $rsp: i64 -= 8: i64
; CHECK-NEXT:    push($rbx: i64, )
; CHECK-NEXT:    $r8: i64 = $rdi: i64
; CHECK-NEXT:    mov_sx($rdi: i64, $esi: i32, )
; CHECK-NEXT:    clear $rcx: i64
; CHECK-NEXT:    clear $ebx: i32
; CHECK-NEXT:    cjmp_int_sgt($esi: i32, 0: i32, ) -> 3
; CHECK-NEXT:    jmp() -> 1
; CHECK-NEXT:  1:
; CHECK-NEXT:    clear $eax: i32
; CHECK-NEXT:    jmp() -> 2
; CHECK-NEXT:  2:
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    ret($eax: i32, )
; CHECK-NEXT:  3:
; CHECK-NEXT:    $eax: i32 = [$r8 + $rcx *4]: i32
; CHECK-NEXT:    cjmp_int_slt($eax: i32, 0: i32, ) -> 6
; CHECK-NEXT:    jmp() -> 4
; CHECK-NEXT:  4:
; CHECK-NEXT:    $edx: i32 = $eax: i32
; CHECK-NEXT:    $edx: i32 += $ebx: i32
; CHECK-NEXT:    $rbx: i64 = $rcx: i64
; CHECK-NEXT:    $rbx: i64 += 1: i64
; CHECK-NEXT:    $eax: i32 = $edx: i32
; CHECK-NEXT:    cjmp_int_eq($rbx: i64, $rdi: i64, ) -> 2
; CHECK-NEXT:    jmp() -> 5
; CHECK-NEXT:  5:
; CHECK-NEXT:    $rcx: i64 = $rbx: i64
; CHECK-NEXT:    $ebx: i32 = $edx: i32
; CHECK-NEXT:    jmp() -> 3
; CHECK-NEXT:  6:
; CHECK-NEXT:    call(abort, )
; CHECK-NEXT:    pop($rbx: i64, )
; CHECK-NEXT:    unreach()
entry:
  %c = icmp sgt i32 %n, 0
  br i1 %c, label %loop, label %exit
bad:
  call void @abort()
  unreachable
loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %latch ]
  %s = phi i32 [ 0, %entry ], [ %s.next, %latch ]
  %g = getelementptr i32, ptr %p, i64 %i
  %v = load i32, ptr %g
  %neg = icmp slt i32 %v, 0
  br i1 %neg, label %bad, label %latch
latch:
  %s.next = add i32 %s, %v
  %i.next = add i64 %i, 1
  %nn = sext i32 %n to i64
  %d = icmp eq i64 %i.next, %nn
  br i1 %d, label %exit, label %loop
exit:
  %r = phi i32 [ 0, %entry ], [ %s.next, %latch ]
  ret i32 %r
}
