; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; If/else diamond: the jmp target of the branch is placed next and the join follows both arms.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s
; RUN: %foffcc %s %t.o

define i32 @diamond(i32 %a, i32 %b) {
; CHECK: func diamond ($2: i32, $3: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    cjmp_int_slt($eax: i32, $esi: i32, ) -> 2
; CHECK-NEXT:    jmp() -> 1
; CHECK-NEXT:  1:
; CHECK-NEXT:    $eax: i32 -= $esi: i32
; CHECK-NEXT:    ret($eax: i32, )
; CHECK-NEXT:  2:
; CHECK-NEXT:    lea($eax: i32, [$eax + $eax *2]: i32, )
; CHECK-NEXT:    ret($eax: i32, )
entry:
  %c = icmp slt i32 %a, %b
  br i1 %c, label %then, label %else
then:
  %t = mul i32 %a, 3
  br label %join
else:
  %e = sub i32 %a, %b
  br label %join
join:
  %r = phi i32 [ %t, %then ], [ %e, %else ]
  ret i32 %r
}
