; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Early exit through a noreturn call is moved to the end of the function.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s
; RUN: %foffcc %s %t.o

declare void @fail(i32) noreturn

define i32 @checked(i32 %a, i32 %b) {
; CHECK: func checked ($2: i32, $3: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    cjmp_int_eq($esi: i32, 0: i32, ) -> 2
; CHECK-NEXT:    jmp() -> 1
; CHECK-NEXT:  1:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    idiv($eax: i32, $edx: i32, $eax: i32, $esi: i32, )
; CHECK-NEXT:    $ecx: i32 = $eax: i32
; CHECK-NEXT:    $eax: i32 = 100: i32
; CHECK-NEXT:    cmov_sgt($eax: i32, $ecx: i32, $eax: i32, $ecx: i32, )
; CHECK-NEXT:    ret($eax: i32, )
; CHECK-NEXT:  2:
; CHECK-NEXT:    call(fail, )
; CHECK-NEXT:    unreach()
entry:
  %z = icmp eq i32 %b, 0
  br i1 %z, label %err, label %ok
err:
  call void @fail(i32 %a)
  unreachable
ok:
  %q = sdiv i32 %a, %b
  %c = icmp sgt i32 %q, 100
  br i1 %c, label %big, label %small
big:
  ret i32 100
small:
  ret i32 %q
}
