; NOTE: Assertions have been autogenerated by utils/update_mir_tests.py UTC_ARGS: --version 6
; Nested loops: inner loop stays contiguous, loop exits come after the loop body.
; RUN: %foffcc %s --print-mir --no-reorder-funcs | FileCheck %s
; RUN: %foffcc %s %t.o

define i32 @nested(i32 %n, i32 %m) {
; CHECK: func nested ($2: i32, $3: i32, )
; CHECK-NEXT:  0:
; CHECK-NEXT:    $r8d: i32 = $esi: i32
; CHECK-NEXT:    $r9d: i32 = $edi: i32
; CHECK-NEXT:    clear $ecx: i32
; CHECK-NEXT:    clear $esi: i32
; CHECK-NEXT:    cjmp_int_sgt($r9d: i32, 0: i32, ) -> 3
; CHECK-NEXT:    jmp() -> 1
; CHECK-NEXT:  1:
; CHECK-NEXT:    clear $eax: i32
; CHECK-NEXT:    jmp() -> 2
; CHECK-NEXT:  2:
; CHECK-NEXT:    ret($eax: i32, )
; CHECK-NEXT:  3:
; CHECK-NEXT:    $edi: i32 = $ecx: i32
; CHECK-NEXT:    clear $edx: i32
; CHECK-NEXT:    jmp() -> 4
; CHECK-NEXT:  4:
; CHECK-NEXT:    $eax: i32 = $edi: i32
; CHECK-NEXT:    $eax: i32 *= $edx: i32
; CHECK-NEXT:    $eax: i32 += $esi: i32
; CHECK-NEXT:    $ecx: i32 = $edx: i32
; CHECK-NEXT:    $ecx: i32 += 1: i32
; CHECK-NEXT:    $edx: i32 += 1: i32
; CHECK-NEXT:    $esi: i32 = $eax: i32
; CHECK-NEXT:    cjmp_int_slt($ecx: i32, $r8d: i32, ) -> 4
; CHECK-NEXT:    jmp() -> 5
; CHECK-NEXT:  5:
; CHECK-NEXT:    $edi: i32 += 1: i32
; CHECK-NEXT:    $ecx: i32 = $edi: i32
; CHECK-NEXT:    $esi: i32 = $eax: i32
; CHECK-NEXT:    cjmp_int_slt($edi: i32, $r9d: i32, ) -> 3
; CHECK-NEXT:    jmp() -> 6
; CHECK-NEXT:  6:
; CHECK-NEXT:    jmp() -> 2
entry:
  br label %outer
outer:
  %i = phi i32 [ 0, %entry ], [ %i.next, %outer.latch ]
  %acc = phi i32 [ 0, %entry ], [ %acc.in, %outer.latch ]
  %oc = icmp slt i32 %i, %n
  br i1 %oc, label %inner, label %done
inner:
  %j = phi i32 [ 0, %outer ], [ %j.next, %inner ]
  %a = phi i32 [ %acc, %outer ], [ %a.next, %inner ]
  %p = mul i32 %i, %j
  %a.next = add i32 %a, %p
  %j.next = add i32 %j, 1
  %ic = icmp slt i32 %j.next, %m
  br i1 %ic, label %inner, label %outer.latch
outer.latch:
  %acc.in = phi i32 [ %a.next, %inner ]
  %i.next = add i32 %i, 1
  br label %outer
done:
  ret i32 %acc
}
